## Conda environment.yml generated by `tvbo workflow` from the experiment's
## SimulationExperiment.environment.requirements. Inputs: plan (WorkflowPlan), now (str).
<%
    env_name = "{}-{}".format(plan.study_key, plan.experiment_key).replace(" ", "_")
%>\
# Conda environment for the ${plan.backend.name} kit — generated ${now}
name: ${env_name}
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip
  - pip:
% for spec in plan.pip_specs:
      - ${spec}
% endfor
