## README shipped inside an emitted kit.
## Inputs (all resolved by the emitter — no lookups or formatting logic here):
##   engine       str        slurm | snakemake | nextflow
##   artefact     str        the engine's artefact filename
##   plans        list       one plan per frozen experiment (>1 ⇒ a study kit)
##   head         plan       plans[0]; the kit-wide backend/container/overrides
##   study        bool       len(plans) > 1
##   script_relpath str|None frozen backend script, when the engine ships one
##   spec_layout  str        where the frozen specs actually live
# ${head.study_key}${"" if study else " / " + head.experiment_key}

Generated by `tvbo workflow ${engine}` on ${now}.

## Layout

- `${artefact}` — workflow artefact (run with the engine below)
% if script_relpath:
- `${script_relpath}` — frozen backend code (`${head.backend.name}`); has a `__main__` block, runnable with `python`
% endif
% if study:
- `${spec_layout}` — frozen YAML snapshot, one per experiment (${len(plans)}: ${", ".join(p.experiment_key for p in plans)})
% else:
- `${spec_layout}` — frozen YAML snapshot of the experiment
% endif

## Run

```bash
% if engine == "slurm":
sbatch ${artefact}
% elif engine == "snakemake":
# On a SLURM cluster (login node) — submits each rule to the scheduler:
#   needs:  pip install snakemake-executor-plugin-slurm
snakemake --profile profile        # or: tvbo workflow submit <this kit>

# Local (laptop / one interactive node) — no scheduler:
# snakemake --cores all
% elif engine == "nextflow":
nextflow run main.nf
% endif
```

## Reproducibility

- backend       : `${head.backend.name}` (${head.backend.label})
- container     : `${head.container or '(none)'}`
% if study:
## The Snakefile's global `container:` is keyed on the first experiment, so the line
## above matches it; per-experiment fan-out differs and gets its own row below. Both
## cell counts are reported: a fully backend-vectorized sweep has one workflow cell but
## many simulations inside it (a 4x39x10 grid is 1 job, 1560 cells), so workflow cells
## alone would understate the study by 1000x.
- experiments   : ${len(plans)}
- workflow cells: ${sum(p.n_workflow_cells for p in plans)} (jobs; ${sum(p.n_workflow_cells * p.n_vectorize_cells for p in plans)} simulation cells once each job's vectorized axes are expanded)

| experiment | jobs | vectorized cells | vectorize_axes | workflow_axes |
| --- | --- | --- | --- | --- |
% for p in plans:
| `${p.experiment_key}` | ${p.n_workflow_cells} | ${p.n_vectorize_cells} | ${", ".join(ax.name for ax in p.vectorize_axes) or "—"} | ${", ".join(ax.name for ax in p.workflow_axes) or "—"} |
% endfor
% else:
- workflow cells: ${head.n_workflow_cells} (chunk=${head.chunk}, array tasks=${head.n_array_tasks})
- vectorize_axes: ${[ax.name for ax in head.vectorize_axes]}
- workflow_axes : ${[ax.name for ax in head.workflow_axes]}
% endif
% if head.overrides:

### CLI overrides
## Parsed once and merged into every experiment's spec.

% for o in head.overrides:
- `${o['key']}` = `${o['value']}` (${o['source']})
% endfor
% endif
