## pip requirements.txt generated by `tvbo workflow` from the experiment's
## SimulationExperiment.environment.requirements. Inputs: plan (WorkflowPlan), now (str).
# pip requirements for the ${plan.backend.name} kit — generated ${now}
% for spec in plan.pip_specs:
${spec}
% endfor
