## One-time kit setup — generated by `tvbo workflow` when a `container` AND `requirements`
## are both declared. Layers the study's declared requirements onto the base image without
## rebuilding it, via a `--system-site-packages` venv (pip resolves against the image and
## installs only the delta; native wheels compile with the image's own interpreter, so the
## layer is ABI-correct). Run ONCE from the kit dir before running the workflow:
##   `bash setup.sh`  — it is idempotent. Each task then prepends the venv to PYTHONPATH.
## Inputs: plan (WorkflowPlan), now (str).
<%
    prefix = "singularity exec " + (plan.container_exec_flags + " " if plan.container_exec_flags else "") + plan.container
%>\
#!/bin/bash
# Generated by tvbo workflow — ${now}
#   base image : ${plan.container}
#   layers     : ${", ".join(plan.pip_specs)}
set -euo pipefail
cd "$(dirname "$0")"

VENV="${plan.container_extras_venv}"
if [ ! -x "${'$'}{VENV}/bin/python" ]; then
    echo "creating --system-site-packages venv ${'$'}{VENV} on top of ${plan.container}"
    ${prefix} python -m venv --system-site-packages "${'$'}{VENV}"
fi
echo "installing declared requirements into ${'$'}{VENV} (delta over the image)"
${prefix} "${'$'}{VENV}/bin/pip" install --no-input -r requirements.txt
echo "done — each task will prepend ${'$'}{VENV}'s site-packages to PYTHONPATH"
