## One-time kit setup — generated by `tvbo workflow` when `requirements` are declared.
## Provisions the study's declared requirements into a `--system-site-packages` venv (pip
## resolves against the surrounding interpreter and installs only the delta; native wheels
## compile with it, so the layer is ABI-correct) — a NATIVE venv when no container is
## declared, or one built via `singularity exec` ON the base image (layering the deps
## without rebuilding it) when there is. `tvbo workflow submit` runs this automatically
## before submitting, so the whole cluster step is one command; it is also runnable by hand
## (`bash setup.sh`) and idempotent. Each task then prepends the venv to PYTHONPATH.
## Inputs: plan (WorkflowPlan), now (str).
<%
    # Build the venv on the image when a container is declared, else in the host env.
    prefix = ("singularity exec " + (plan.container_exec_flags + " " if plan.container_exec_flags else "")
              + plan.container + " ") if plan.container else ""
    base = plan.container or "the surrounding environment"
%>\
#!/bin/bash
# Generated by tvbo workflow — ${now}
#   base       : ${base}
#   layers     : ${", ".join(plan.pip_specs)}
set -euo pipefail
cd "$(dirname "$0")"

VENV="${plan.container_extras_venv}"
if [ ! -x "${'$'}{VENV}/bin/python" ]; then
    echo "creating --system-site-packages venv ${'$'}{VENV} on ${base}"
    ${prefix}python -m venv --system-site-packages "${'$'}{VENV}"
fi
echo "installing declared requirements into ${'$'}{VENV} (delta over ${base})"
${prefix}"${'$'}{VENV}/bin/pip" install --no-input -r requirements.txt
echo "done — each task will prepend ${'$'}{VENV}'s site-packages to PYTHONPATH"
