"""The generated datamodel must match the schema and the generator it is generated from.

``tvbo/datamodel/`` is a build artifact, untracked and regenerated by ``hatch_build.py``. An editable install keeps whatever was generated last, so pulling or switching to a branch whose ``schema/`` or ``hatch_build.py`` differs leaves a module that describes the *previous* schema, or lacks the generator's rewrites, while every other file describes the current one.

Nothing about that failure names its cause. A removed slot keeps materialising its default, so every database dump gains a key and the golden corpus reports the published record as changed; a class that gained a behaviour mixin raises ``AttributeError`` for a method that plainly exists in ``tvbo/behaviour/``; a slot that gained an alias rejects the spelling the schema promises. Each reads as a real regression in whatever code happens to touch it first.

So the digest is checked once per session, before the suites that would otherwise report the symptom.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
SCHEMA = REPO / "schema"


def _digest() -> str:
    """Content hash of the schema sources and the generator, by ``hatch_build._schema_digest`` itself."""
    spec = importlib.util.spec_from_file_location("hatch_build", REPO / "hatch_build.py")
    hatch_build = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(hatch_build)
    return hatch_build._schema_digest(REPO)


def test_the_generated_datamodel_matches_the_schema():
    if not SCHEMA.is_dir():
        pytest.skip("installed without the schema sources, so there is nothing to compare against")
    try:
        from tvbo.datamodel._stamp import SCHEMA_DIGEST
    except ImportError:
        pytest.fail(
            "tvbo/datamodel/ carries no schema stamp, so it predates this check and its age cannot be "
            "established. Regenerate it: python hatch_build.py"
        )

    assert SCHEMA_DIGEST == _digest(), (
        "tvbo/datamodel/ was generated from a different schema/ or hatch_build.py than the one in this tree. It is a build "
        "artifact, so a pull or branch switch leaves it behind. Regenerate it before reading anything else "
        "into a failure elsewhere: python hatch_build.py"
    )
