"""
End-to-end tests: TVBO NetworkDynamics.jl backend vs original Julia reference.

These tests compare the numerical output of TVBO's NetworkDynamics.jl code
generation + execution against pre-computed reference data from the original
NetworkDynamics.jl tutorials.

Reference data is stored in HDF5 files generated by:
    julia tests/reference_data/generate_nd_references.jl

The tests verify that TVBO-generated Julia code, when run with pyjulia,
produces results numerically close to the original examples.

Requires: h5py, numpy, pytest
Optional: pyjulia (for live execution tests)
"""
import os
import numpy as np
import pytest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
HERE = os.path.dirname(os.path.abspath(__file__))
REF_DIR = os.path.join(HERE, "reference_data")
EXAMPLES_DIR = os.path.join(
    os.path.dirname(HERE), "docs", "Interoperability", "NetworkDynamics.jl"
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _h5_exists(name):
    """Check if the HDF5 reference file exists."""
    return os.path.isfile(os.path.join(REF_DIR, f"{name}_reference.h5"))


def _load_reference(name):
    """Load reference data from HDF5."""
    import h5py
    path = os.path.join(REF_DIR, f"{name}_reference.h5")
    with h5py.File(path, "r") as f:
        data = {
            "t": f["t"][:],
            "u": f["u"][:],
            "x0": f["x0"][:],
        }
        if "adjacency" in f:
            data["adjacency"] = f["adjacency"][:]
        if "omega0" in f:
            data["omega0"] = f["omega0"][:]
        if "G" in f:
            data["G"] = f["G"][:]
        if "edge_weights" in f:
            data["edge_weights"] = f["edge_weights"][:]
        if "vertex_types" in f:
            data["vertex_types"] = [s.decode() if isinstance(s, bytes) else s
                                    for s in f["vertex_types"][:]]
        # Read attributes
        data["attrs"] = dict(f.attrs)
    return data


def _julia_available():
    """Check if pyjulia is available and working."""
    try:
        from tvbo.run.julia import init_julia
        init_julia()
        return True
    except Exception:
        return False


julia_available = pytest.mark.skipif(
    not _julia_available(),
    reason="pyjulia not available"
)

ref_data_available = pytest.mark.skipif(
    not any(_h5_exists(n) for n in ["diffusion", "kuramoto", "fitzhugh_nagumo"]),
    reason="HDF5 reference data not generated (run generate_nd_references.jl)"
)


# ===========================================================================
# Test 1: Code generation (no Julia needed)
# ===========================================================================
class TestCodeGeneration:
    """Verify that TVBO generates valid Julia code from YAML specs."""

    @pytest.fixture(params=["diffusion", "kuramoto", "fitzhugh_nagumo"])
    def example(self, request):
        return request.param

    @pytest.fixture(params=[
        "diffusion", "kuramoto", "fitzhugh_nagumo",
        "diffusion_2d", "heterogeneous_kuramoto",
    ])
    def all_examples(self, request):
        return request.param

    def test_render_code_produces_julia(self, example):
        """render_code('networkdynamics') returns non-empty Julia code."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, f"{example}.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert isinstance(code, str)
        assert len(code) > 100
        assert "using NetworkDynamics" in code
        assert "using Graphs" in code

    def test_code_has_vertex_model(self, example):
        """Generated code defines a VertexModel."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, f"{example}.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "VertexModel" in code

    def test_code_has_edge_model(self, example):
        """Generated code defines an EdgeModel."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, f"{example}.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "EdgeModel" in code

    def test_code_has_ode_problem(self, example):
        """Generated code creates an ODEProblem."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, f"{example}.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "ODEProblem" in code

    def test_code_has_solve(self, example):
        """Generated code calls solve()."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, f"{example}.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "solve(" in code

    def test_diffusion_uses_barabasi_albert(self):
        """Diffusion example uses Barabasi-Albert graph generator."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "barabasi_albert" in code

    def test_kuramoto_uses_watts_strogatz(self):
        """Kuramoto example uses Watts-Strogatz graph generator."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "watts_strogatz" in code

    def test_fhn_uses_weighted_digraph(self):
        """FHN example uses SimpleWeightedDiGraph from connectivity file."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "fitzhugh_nagumo.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "SimpleWeightedDiGraph" in code or "readdlm" in code

    def test_fhn_uses_directed_coupling(self):
        """FHN example uses Directed edge coupling (not AntiSymmetric)."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "fitzhugh_nagumo.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "Directed(" in code

    def test_diffusion_uses_antisymmetric(self):
        """Diffusion example uses AntiSymmetric edge coupling."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "AntiSymmetric(" in code

    # -- 2D Diffusion specific tests --

    def test_diffusion_2d_multidim_coupling(self):
        """2D diffusion: vertex outputs 2 coupling variables via StateMask(1:2)."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion_2d.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "StateMask(1:2)" in code
        assert "sym = [:x, :phi]" in code

    def test_diffusion_2d_broadcasting_edge(self):
        """2D diffusion: edge uses broadcasting (e_dst .= v_src .- v_dst)."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion_2d.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "e_dst .=" in code
        assert "outsym = [:flow_x, :flow_phi]" in code

    def test_diffusion_2d_no_variable_shadowing(self):
        """2D diffusion: function arg doesn't shadow state var 'x'."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion_2d.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "function Diffusion2D_f!(dx, _x, esum" in code
        assert "x, phi = _x" in code

    def test_diffusion_2d_uses_barabasi_albert_10(self):
        """2D diffusion: 10-node Barabási-Albert network."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion_2d.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 10
        code = exp.render_code("networkdynamics")
        assert "barabasi_albert(10, 4)" in code

    # -- Heterogeneous Kuramoto specific tests --

    def test_heterogeneous_kuramoto_vertex_types(self):
        """Heterogeneous Kuramoto: generates 3 vertex model types."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "vertex_Kuramoto" in code
        assert "vertex_StaticNode" in code
        assert "vertex_KuramotoInertia" in code

    def test_heterogeneous_kuramoto_vertex_array(self):
        """Heterogeneous Kuramoto: builds VertexModel[] array with per-node assignment."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "vertex_array = VertexModel[" in code
        assert "vertex_array[1] = vertex_StaticNode" in code
        assert "vertex_array[5] = vertex_KuramotoInertia" in code

    def test_heterogeneous_kuramoto_static_no_feedforward(self):
        """Static vertex uses NoFeedForward() and outputs :theta."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "ff = NoFeedForward()" in code
        assert "outsym = [:theta]" in code

    def test_heterogeneous_kuramoto_inertia_2d(self):
        """Inertia vertex has 2 state vars but only 1 coupling output."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        # KuramotoInertia has sym = [:theta, :omega] but g = StateMask(1:1)
        assert "sym = [:theta, :omega]" in code
        # Should be in the KuramotoInertia section
        inertia_section = code.split("vertex_KuramotoInertia")[1]
        # g=1:1 means only theta is output
        assert "StateMask(1:1)" in code

    def test_heterogeneous_kuramoto_per_node_params(self):
        """Per-node omega0 parameters are set via NWState."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        # Check that per-node omega0 values are set
        assert "s.p.v[2, :omega0] = -0.3125" in code
        assert "s.p.v[8, :omega0] = 0.4375" in code
        # Static node gets theta_fix parameter
        assert "s.p.v[1, :theta_fix] = -0.4375" in code

    def test_heterogeneous_kuramoto_dealias(self):
        """Heterogeneous Network uses dealias=true."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "dealias=true" in code


# ===========================================================================
# Test 2: YAML specification correctness
# ===========================================================================
class TestYAMLSpecs:
    """Verify YAML specifications match original tutorial parameters."""

    def test_diffusion_yaml(self):
        """Diffusion YAML matches original: 20 nodes, BA(k=4), Tsit5, t=[0,2]."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 20
        assert exp.integration.duration == 2.0

    def test_kuramoto_yaml(self):
        """Kuramoto YAML matches original: 8 nodes, WS(k=2,p=0), K=3, t=[0,10]."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 8
        assert exp.integration.duration == 10.0

    def test_fhn_yaml(self):
        """FHN YAML matches original: 90 nodes, a=0.5, eps=0.05, sigma=0.5, t=[0,200]."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "fitzhugh_nagumo.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 90
        assert exp.integration.duration == 200.0

    def test_fhn_equations_match_original(self):
        """FHN equations match original ND.jl code (not the description)."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "fitzhugh_nagumo.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        svs = exp.local_dynamics.state_variables
        # du/dt = u - u^3/3 - v + coupling  (NOT divided by epsilon)
        u_rhs = svs["u"].equation.rhs
        assert "/ epsilon" not in u_rhs, \
            f"u equation should NOT divide by epsilon: {u_rhs}"
        # dv/dt = (u - a) * epsilon  (matches code, not math description)
        v_rhs = svs["v"].equation.rhs
        assert "a" in v_rhs and "epsilon" in v_rhs, \
            f"v equation should contain a and epsilon: {v_rhs}"

    def test_diffusion_2d_yaml(self):
        """2D Diffusion YAML: 10 nodes, BA(k=4), t=[0,3], 2 SVs, both coupling vars."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion_2d.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 10
        assert exp.integration.duration == 3.0
        svs = exp.local_dynamics.state_variables
        assert len(svs) == 2
        assert "x" in svs and "phi" in svs
        for sv in svs.values():
            assert getattr(sv, "coupling_variable", False) is True

    def test_heterogeneous_kuramoto_yaml(self):
        """Heterogeneous Kuramoto YAML: 8 nodes, 3 vertex types, per-node assignment."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 8
        assert exp.integration.duration == 10.0
        # Default dynamics is Kuramoto
        assert exp.local_dynamics.name == "Kuramoto"
        # Additional dynamics in library
        assert "StaticNode" in exp.dynamics
        assert "KuramotoInertia" in exp.dynamics
        # Nodes with per-node assignments
        nodes = exp.network.nodes
        assert len(nodes) == 8
        # Node 0 has StaticNode dynamics
        assert str(nodes[0].dynamics) == "StaticNode"
        # Node 4 has KuramotoInertia
        assert str(nodes[4].dynamics) == "KuramotoInertia"


# ===========================================================================
# Test 3: Live execution + numerical comparison (requires pyjulia + HDF5)
# ===========================================================================
@julia_available
class TestNumericalComparison:
    """Run TVBO-generated code in Julia and compare with reference data."""

    @pytest.fixture
    def julia_runner(self):
        """Provide Julia code execution capability."""
        from tvbo.run.julia import run_julia_code, extract_ode_solution
        return run_julia_code, extract_ode_solution

    @pytest.mark.skipif(
        not _h5_exists("diffusion"),
        reason="diffusion_reference.h5 not found"
    )
    def test_diffusion_numerical(self, julia_runner):
        """Diffusion: TVBO result matches original within tolerance."""
        ref = _load_reference("diffusion")
        run_julia_code, extract_ode_solution = julia_runner

        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        ts = exp.run(format="networkdynamics")

        # Check shape: should have 20 nodes, 1 state variable
        assert ts.data.shape[2] == 20, f"Expected 20 nodes, got {ts.data.shape[2]}"
        # Check convergence: all nodes should converge to same value
        final_states = ts.data[-1, 0, :, 0]
        assert np.std(final_states) < 0.1, \
            f"Diffusion should converge: std={np.std(final_states):.4f}"

    @pytest.mark.skipif(
        not _h5_exists("kuramoto"),
        reason="kuramoto_reference.h5 not found"
    )
    def test_kuramoto_numerical(self, julia_runner):
        """Kuramoto: TVBO result has correct shape and reasonable dynamics."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        ts = exp.run(format="networkdynamics")

        # Check shape: 8 nodes, 1 state variable (theta)
        assert ts.data.shape[2] == 8, f"Expected 8 nodes, got {ts.data.shape[2]}"
        # Phases should grow over time (oscillators)
        assert ts.data[-1, 0, 0, 0] != ts.data[0, 0, 0, 0], \
            "Phase should change over time"

    @pytest.mark.skipif(
        not _h5_exists("fitzhugh_nagumo"),
        reason="fitzhugh_nagumo_reference.h5 not found"
    )
    def test_fhn_numerical(self, julia_runner):
        """FHN: TVBO result has correct shape and shows synchronization."""
        from tvbo import SimulationExperiment
        yaml_path = os.path.join(EXAMPLES_DIR, "fitzhugh_nagumo.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        ts = exp.run(format="networkdynamics")

        # Check shape: 90 nodes, 2 state variables (u, v)
        assert ts.data.shape[2] == 90, f"Expected 90 nodes, got {ts.data.shape[2]}"
        assert ts.data.shape[3] == 2, f"Expected 2 state vars, got {ts.data.shape[3]}"
        # u variables should be bounded (no numerical explosion)
        u_data = ts.data[:, 0, :, 0]
        assert np.all(np.abs(u_data) < 50), \
            f"u should be bounded: max={np.max(np.abs(u_data)):.1f}"


# ===========================================================================
# Test 4: Reference data validation (no Julia needed, only HDF5)
# ===========================================================================
class TestReferenceData:
    """Validate the HDF5 reference data itself for consistency."""

    @pytest.mark.skipif(not _h5_exists("diffusion"),
                        reason="diffusion_reference.h5 not found")
    def test_diffusion_reference_shape(self):
        ref = _load_reference("diffusion")
        assert ref["t"].shape == (201,)
        assert ref["u"].shape[1] == 20  # 20 nodes
        assert ref["u"].shape[0] == 201  # 201 time points
        assert ref["x0"].shape == (20,)

    @pytest.mark.skipif(not _h5_exists("diffusion"),
                        reason="diffusion_reference.h5 not found")
    def test_diffusion_reference_convergence(self):
        """Diffusion should converge toward uniform state."""
        ref = _load_reference("diffusion")
        final = ref["u"][-1, :]  # last timestep, all nodes
        assert np.std(final) < 0.15, \
            f"Diffusion should converge: std={np.std(final):.6f}"

    @pytest.mark.skipif(not _h5_exists("kuramoto"),
                        reason="kuramoto_reference.h5 not found")
    def test_kuramoto_reference_shape(self):
        ref = _load_reference("kuramoto")
        assert ref["t"].shape == (201,)
        assert ref["u"].shape[1] == 8
        assert ref["u"].shape[0] == 201
        assert ref["omega0"].shape == (8,)

    @pytest.mark.skipif(not _h5_exists("kuramoto"),
                        reason="kuramoto_reference.h5 not found")
    def test_kuramoto_reference_frequencies(self):
        """Omega0 should be centered and span [1/N, 1]."""
        ref = _load_reference("kuramoto")
        ω = ref["omega0"]
        assert abs(np.sum(ω)) < 1e-10, f"ω should be centered: sum={np.sum(ω)}"
        assert ω.shape == (8,)

    @pytest.mark.skipif(not _h5_exists("fitzhugh_nagumo"),
                        reason="fitzhugh_nagumo_reference.h5 not found")
    def test_fhn_reference_shape(self):
        ref = _load_reference("fitzhugh_nagumo")
        assert ref["t"].shape == (501,)
        # 90 nodes × 2 state vars = 180 states
        assert ref["u"].shape[1] == 180
        assert ref["u"].shape[0] == 501

    @pytest.mark.skipif(not _h5_exists("fitzhugh_nagumo"),
                        reason="fitzhugh_nagumo_reference.h5 not found")
    def test_fhn_reference_bounded(self):
        """FHN states should be bounded (no numerical explosion)."""
        ref = _load_reference("fitzhugh_nagumo")
        assert np.all(np.isfinite(ref["u"])), "All states should be finite"
        assert np.max(np.abs(ref["u"])) < 50, \
            f"States should be bounded: max={np.max(np.abs(ref['u'])):.1f}"

    @pytest.mark.skipif(not _h5_exists("fitzhugh_nagumo"),
                        reason="fitzhugh_nagumo_reference.h5 not found")
    def test_fhn_connectivity_matrix(self):
        """FHN connectivity matrix should be 90×90 with correct sparsity."""
        ref = _load_reference("fitzhugh_nagumo")
        G = ref["G"]
        assert G.shape == (90, 90)
        # Not fully connected, not empty
        n_edges = np.count_nonzero(G)
        assert 1000 < n_edges < 8100, f"Expected ~7793 edges, got {n_edges}"

    # -- 2D Diffusion reference data --

    @pytest.mark.skipif(not _h5_exists("diffusion_2d"),
                        reason="diffusion_2d_reference.h5 not found")
    def test_diffusion_2d_reference_shape(self):
        """2D Diffusion reference: 301 timesteps, 20 states (10 nodes × 2 SVs)."""
        ref = _load_reference("diffusion_2d")
        assert ref["t"].shape == (301,)
        # 10 nodes × 2 state vars = 20 interleaved states
        assert ref["u"].shape[0] == 301
        assert ref["u"].shape[1] == 20

    @pytest.mark.skipif(not _h5_exists("diffusion_2d"),
                        reason="diffusion_2d_reference.h5 not found")
    def test_diffusion_2d_reference_convergence(self):
        """2D Diffusion: both state variables should converge."""
        ref = _load_reference("diffusion_2d")
        final = ref["u"][-1, :]  # last timestep, all states
        # x states (even indices), phi states (odd indices)
        x_final = final[0::2]
        phi_final = final[1::2]
        assert np.std(x_final) < 0.5, \
            f"x should converge: std={np.std(x_final):.4f}"
        assert np.std(phi_final) < 0.5, \
            f"phi should converge: std={np.std(phi_final):.4f}"

    # -- Heterogeneous Kuramoto reference data --

    @pytest.mark.skipif(not _h5_exists("heterogeneous_kuramoto"),
                        reason="heterogeneous_kuramoto_reference.h5 not found")
    def test_heterogeneous_kuramoto_reference_shape(self):
        """Heterogeneous Kuramoto reference: 201 timesteps, mixed state dim."""
        ref = _load_reference("heterogeneous_kuramoto")
        assert ref["t"].shape == (201,)
        # Node dimensions: 0(static)=0, 1-3(kuramoto)=1, 4(inertia)=2, 5-7(kuramoto)=1
        # Total: 0 + 1+1+1 + 2 + 1+1+1 = 8 states
        assert ref["u"].shape[0] == 201

    @pytest.mark.skipif(not _h5_exists("heterogeneous_kuramoto"),
                        reason="heterogeneous_kuramoto_reference.h5 not found")
    def test_heterogeneous_kuramoto_reference_bounded(self):
        """Heterogeneous Kuramoto: all states should be finite and bounded."""
        ref = _load_reference("heterogeneous_kuramoto")
        assert np.all(np.isfinite(ref["u"])), "All states should be finite"

    @pytest.mark.skipif(not _h5_exists("heterogeneous_kuramoto"),
                        reason="heterogeneous_kuramoto_reference.h5 not found")
    def test_heterogeneous_kuramoto_vertex_types_data(self):
        """Heterogeneous Kuramoto: vertex types are correctly stored."""
        ref = _load_reference("heterogeneous_kuramoto")
        if "vertex_types" in ref:
            vtypes = ref["vertex_types"]
            assert len(vtypes) == 8


# ===========================================================================
# Test 5: URL validation (no Julia needed)
# ===========================================================================
class TestDocURLs:
    """Verify that documentation URLs in YAML files are valid."""

    @pytest.fixture(params=[
        "diffusion", "kuramoto", "fitzhugh_nagumo",
        "diffusion_2d", "heterogeneous_kuramoto",
    ])
    def yaml_path(self, request):
        return os.path.join(EXAMPLES_DIR, f"{request.param}.yaml")

    def test_yaml_urls_use_generated_path(self, yaml_path):
        """All URLs should use /stable/generated/ path (not bare /stable/)."""
        import yaml
        with open(yaml_path) as f:
            spec = yaml.safe_load(f)
        refs = spec.get("references", [])
        for url in refs:
            if "NetworkDynamics.jl" in url:
                assert "/generated/" in url, \
                    f"URL should use /generated/ path: {url}"
                # Check it doesn't use old format
                assert url.count("/stable/") == 1, \
                    f"URL has duplicate /stable/: {url}"
