"""
End-to-end tests: TVBO NetworkDynamics.jl backend vs original Julia reference.

These tests compare the numerical output of TVBO's NetworkDynamics.jl code generation + execution against pre-computed reference data from the original
NetworkDynamics.jl tutorials.

Reference data is stored in HDF5 files generated by:
    julia tests/reference_data/generate_nd_references.jl

The tests verify that TVBO-generated Julia code, when run with pyjulia, produces results numerically close to the original examples.

Requires: h5py, numpy, pytest
Optional: pyjulia (for live execution tests)
"""

import os
import numpy as np
import pytest

# Paths
HERE = os.path.dirname(os.path.abspath(__file__))
REF_DIR = os.path.join(HERE, "reference_data")
EXAMPLES_DIR = os.path.join(os.path.dirname(HERE), "docs", "Interoperability", "NetworkDynamics.jl", "yaml")

# Helpers


def _load_reference(name):
    """Load reference data from HDF5."""
    import h5py

    path = os.path.join(REF_DIR, f"{name}_reference.h5")
    if not os.path.exists(path):
        pytest.skip(f"Reference data not found: {path}")
    with h5py.File(path, "r") as f:
        data = {
            "t": f["t"][:],
            "u": f["u"][:],
            "x0": f["x0"][:],
        }
        if "adjacency" in f:
            data["adjacency"] = f["adjacency"][:]
        if "omega0" in f:
            data["omega0"] = f["omega0"][:]
        if "G" in f:
            data["G"] = f["G"][:]
        if "edge_weights" in f:
            data["edge_weights"] = f["edge_weights"][:]
        if "vertex_types" in f:
            data["vertex_types"] = [s.decode() if isinstance(s, bytes) else s for s in f["vertex_types"][:]]
        # Read attributes
        data["attrs"] = dict(f.attrs)
    return data


# Test 1: Code generation (no Julia needed)
class TestCodeGeneration:
    """Verify that TVBO generates valid Julia code from YAML specs."""

    @pytest.fixture(params=["diffusion", "kuramoto", "fitzhugh_nagumo"])
    def example(self, request):
        return request.param

    @pytest.fixture(
        params=[
            "diffusion",
            "kuramoto",
            "fitzhugh_nagumo",
            "diffusion_2d",
            "heterogeneous_kuramoto",
            "cascading_failure",
            "stress_on_truss",
        ]
    )
    def all_examples(self, request):
        return request.param

    def test_render_code_produces_julia(self, example):
        """render_code('networkdynamics') returns non-empty Julia code."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, f"{example}.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert isinstance(code, str)
        assert len(code) > 100
        assert "using NetworkDynamics" in code
        assert "using Graphs" in code

    def test_code_has_vertex_model(self, example):
        """Generated code defines a VertexModel."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, f"{example}.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "VertexModel" in code

    def test_code_has_edge_model(self, example):
        """Generated code defines an EdgeModel."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, f"{example}.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "EdgeModel" in code

    def test_code_has_ode_problem(self, example):
        """Generated code creates an ODEProblem."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, f"{example}.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "ODEProblem" in code

    def test_code_has_solve(self, example):
        """Generated code calls solve()."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, f"{example}.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "solve(" in code

    def test_diffusion_uses_barabasi_albert(self):
        """Diffusion example uses Barabasi-Albert graph generator."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "barabasi_albert" in code

    def test_kuramoto_uses_watts_strogatz(self):
        """Kuramoto example uses Watts-Strogatz graph generator."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "watts_strogatz" in code

    def test_fhn_uses_weighted_digraph(self):
        """FHN example uses SimpleWeightedDiGraph from connectivity file."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "fitzhugh_nagumo.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "SimpleWeightedDiGraph" in code or "readdlm" in code

    def test_fhn_uses_directed_coupling(self):
        """FHN example uses Directed edge coupling (not AntiSymmetric)."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "fitzhugh_nagumo.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "Directed(" in code

    def test_diffusion_uses_antisymmetric(self):
        """Diffusion example uses AntiSymmetric edge coupling."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "AntiSymmetric(" in code

    # -- 2D Diffusion specific tests --

    def test_diffusion_2d_multidim_coupling(self):
        """2D diffusion: vertex outputs 2 coupling variables via StateMask(1:2)."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion_2d.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "StateMask(1:2)" in code
        # State variable order follows LinkML normalized dict ordering
        assert "sym = [:phi, :x]" in code

    def test_diffusion_2d_broadcast_esum(self):
        """2D diffusion: vertex uses broadcasting (dx .= esum) for multi-dim coupling."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion_2d.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "dx .= esum" in code

    def test_diffusion_2d_broadcasting_edge(self):
        """2D diffusion: edge uses broadcasting (e_dst .= v_src .- v_dst)."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion_2d.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "e_dst .=" in code
        assert "outsym = [:flow_phi, :flow_x]" in code

    def test_diffusion_2d_no_variable_shadowing(self):
        """2D diffusion: function arg doesn't shadow state var 'x'."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion_2d.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "function Diffusion2D_f!(dx, _x, esum" in code
        assert "phi, x = _x" in code

    def test_diffusion_2d_uses_barabasi_albert_10(self):
        """2D diffusion: 10-node Barabási-Albert network."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion_2d.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 10
        code = exp.render_code("networkdynamics")
        assert "barabasi_albert(10, 4)" in code

    # -- Heterogeneous Kuramoto specific tests --

    def test_heterogeneous_kuramoto_vertex_types(self):
        """Heterogeneous Kuramoto: generates 3 vertex model types."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "vertex_Kuramoto" in code
        assert "vertex_StaticNode" in code
        assert "vertex_KuramotoInertia" in code

    def test_heterogeneous_kuramoto_vertex_array(self):
        """Heterogeneous Kuramoto: builds VertexModel[] array with per-node assignment."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "vertex_array = VertexModel[" in code
        assert "vertex_array[1] = vertex_StaticNode" in code
        assert "vertex_array[5] = vertex_KuramotoInertia" in code

    def test_heterogeneous_kuramoto_static_no_feedforward(self):
        """Static vertex uses NoFeedForward() and outputs :theta."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "ff = NoFeedForward()" in code
        assert "outsym = [:theta]" in code

    def test_heterogeneous_kuramoto_inertia_2d(self):
        """Inertia vertex has 2 state vars but only 1 coupling output."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        # KuramotoInertia has sym = [:omega, :theta] (alphabetical) but g = StateMask(2:2)
        assert "sym = [:omega, :theta]" in code
        # Should be in the KuramotoInertia section
        code.split("vertex_KuramotoInertia")[1]
        # g=2:2 means only theta (at index 2) is output
        assert "StateMask(2:2)" in code

    def test_heterogeneous_kuramoto_per_node_params(self):
        """Per-node omega0 parameters are set via NWState."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        # Check that per-node omega0 values are set
        assert "s.p.v[2, :omega0] = -0.3125" in code
        assert "s.p.v[8, :omega0] = 0.4375" in code
        # Static node gets theta_fix parameter
        assert "s.p.v[1, :theta_fix] = -0.4375" in code

    def test_heterogeneous_kuramoto_dealias(self):
        """Heterogeneous Network uses dealias=true."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "dealias=true" in code

    # -- Cascading Failure specific tests --

    def test_cascading_failure_find_fixpoint(self):
        """Cascading failure uses find_fixpoint for initial conditions."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "cascading_failure.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "find_fixpoint(nw)" in code
        assert "set_defaults!(nw, u0)" in code

    def test_cascading_failure_callbacks(self):
        """Cascading failure has component-based callbacks."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "cascading_failure.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "ComponentCondition" in code
        assert "ComponentAffect" in code
        assert "ContinuousComponentCallback" in code
        assert "set_callback!" in code

    def test_cascading_failure_preset_time_callback(self):
        """Cascading failure has a preset time callback on edge 5."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "cascading_failure.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "PresetTimeComponentCallback" in code
        assert "add_callback!" in code

    def test_cascading_failure_per_node_params(self):
        """Cascading failure sets per-node P_ref via set_default!."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "cascading_failure.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "set_default!(nw, VIndex(1, :P_ref), -1.0)" in code
        assert "set_default!(nw, VIndex(2, :P_ref), 1.5)" in code

    def test_cascading_failure_outsym(self):
        """Cascading failure edge outputs :P."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "cascading_failure.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "outsym = [:P]" in code

    def test_cascading_failure_dealias(self):
        """Cascading failure uses dealias=true for per-edge callbacks."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "cascading_failure.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "dealias=true" in code

    def test_cascading_failure_ode_problem_nwstate(self):
        """Cascading failure uses ODEProblem(nw, u0, tspan) with NWState."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "cascading_failure.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "ODEProblem(nw, u0, tspan)" in code

    # -- Stress on Truss specific tests --

    def test_stress_on_truss_heterogeneous_vertices(self):
        """Stress on truss uses FreeVertex and FixedVertex."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "stress_on_truss.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "vertex_FreeVertex" in code
        assert "vertex_FixedVertex" in code
        assert "vertex_array = VertexModel[" in code

    def test_stress_on_truss_fixed_vertex_no_feedforward(self):
        """FixedVertex uses NoFeedForward and outputs :x, :y."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "stress_on_truss.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "ff = NoFeedForward()" in code

    def test_stress_on_truss_2d_coupling(self):
        """Stress on truss has 2D coupling with outsym [:Fx, :Fy]."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "stress_on_truss.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "outsym = [:Fx, :Fy]" in code
        assert "insym = [:Fx, :Fy]" in code
        assert "StateMask(3:4)" in code

    def test_stress_on_truss_observed_function(self):
        """Stress on truss beam has an observed function for Fabs."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "stress_on_truss.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        assert "obsf" in code
        assert "obssym = [:Fabs]" in code

    def test_stress_on_truss_per_edge_L(self):
        """Stress on truss sets per-edge L (rest length) values."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "stress_on_truss.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        code = exp.render_code("networkdynamics")
        # Vertical beams have L=1.562050
        assert ":L] = 1.56205" in code
        # Cross braces have L=1.019804
        assert ":L] = 1.019804" in code


# Test 2: YAML specification correctness
class TestYAMLSpecs:
    """Verify YAML specifications match original tutorial parameters."""

    def test_diffusion_yaml(self):
        """Diffusion YAML matches original: 20 nodes, BA(k=4), Tsit5, t=[0,2]."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 20
        assert exp.integration.duration == 2.0

    def test_kuramoto_yaml(self):
        """Kuramoto YAML matches original: 8 nodes, WS(k=2,p=0), K=3, t=[0,10]."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 8
        assert exp.integration.duration == 10.0

    def test_fhn_yaml(self):
        """FHN YAML matches original: 90 nodes, a=0.5, eps=0.05, sigma=0.5, t=[0,200]."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "fitzhugh_nagumo.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 90
        assert exp.integration.duration == 200.0

    def test_fhn_equations_match_original(self):
        """FHN equations match original ND.jl code (not the description)."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "fitzhugh_nagumo.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        svs = exp.dynamics.state_variables
        # du/dt = u - u^3/3 - v + coupling  (NOT divided by epsilon)
        u_rhs = svs["u"].equation.rhs
        assert "/ epsilon" not in u_rhs, f"u equation should NOT divide by epsilon: {u_rhs}"
        # dv/dt = (u - a) * epsilon  (matches code, not math description)
        v_rhs = svs["v"].equation.rhs
        assert "a" in v_rhs and "epsilon" in v_rhs, f"v equation should contain a and epsilon: {v_rhs}"

    def test_diffusion_2d_yaml(self):
        """2D Diffusion YAML: 10 nodes, BA(k=4), t=[0,3], 2 SVs, both coupling vars."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion_2d.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 10
        assert exp.integration.duration == 3.0
        svs = exp.dynamics.state_variables
        assert len(svs) == 2
        assert "x" in svs and "phi" in svs
        for sv in svs.values():
            assert getattr(sv, "coupling_variable", False) is True

    def test_heterogeneous_kuramoto_yaml(self):
        """Heterogeneous Kuramoto YAML: 8 nodes, 3 vertex types, per-node assignment."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 8
        assert exp.integration.duration == 10.0
        # Default dynamics is Kuramoto
        assert exp.dynamics.name == "Kuramoto"
        # Additional dynamics in network library
        assert "StaticNode" in exp.network.dynamics
        assert "KuramotoInertia" in exp.network.dynamics
        # Nodes with per-node assignments
        nodes = exp.network.nodes
        assert len(nodes) == 8
        # Node 0 has StaticNode dynamics
        assert str(nodes[0].dynamics) == "StaticNode"
        # Node 4 has KuramotoInertia
        assert str(nodes[4].dynamics) == "KuramotoInertia"

    def test_cascading_failure_yaml(self):
        """Cascading failure YAML: 5 nodes, swing equation, events, find_fixpoint."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "cascading_failure.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 5
        assert exp.integration.duration == 6.0
        assert exp.dynamics.name == "SwingEquation"
        # Has events
        events = getattr(exp, "events", [])
        assert len(events) >= 2
        # Has find_fixpoint execution config
        exec_cfg = getattr(exp, "execution", None)
        assert exec_cfg is not None
        assert getattr(exec_cfg, "find_fixpoint", False) is True

    def test_stress_on_truss_yaml(self):
        """Stress on truss YAML: 11 nodes, 2 vertex types, per-edge L."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "stress_on_truss.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        assert exp.network.number_of_nodes == 11
        assert exp.integration.duration == 12.0
        assert exp.dynamics.name == "FreeVertex"
        # Has FixedVertex in network dynamics library
        assert "FixedVertex" in exp.network.dynamics
        # Edges
        edges = exp.network.edges
        assert len(edges) == 18
        # FreeVertex has coupling_variables x and y
        svs = exp.dynamics.state_variables
        assert svs["x"].coupling_variable is True
        assert svs["y"].coupling_variable is True
        assert getattr(svs["vx"], "coupling_variable", False) is not True
        assert getattr(svs["vy"], "coupling_variable", False) is not True


# Test 3: Live execution + numerical comparison (requires pyjulia + HDF5)
class TestNumericalComparison:
    """Run TVBO-generated code in Julia and compare with reference data."""

    @pytest.fixture(autouse=True)
    def _require_julia(self):
        """Skip entire class if juliacall is not available."""
        pytest.importorskip("juliacall", reason="juliacall not installed")
        from tvbo.run.julia import run_julia_code

        try:
            run_julia_code("1+1")
        except Exception:
            pytest.skip("Julia runtime not available")

    @pytest.fixture
    def julia_runner(self):
        """Provide Julia code execution capability."""
        from tvbo.run.julia import run_julia_code, extract_ode_solution

        return run_julia_code, extract_ode_solution

    def test_diffusion_numerical(self, julia_runner):
        """Diffusion: TVBO result matches original within tolerance."""
        _load_reference("diffusion")
        run_julia_code, extract_ode_solution = julia_runner

        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        ts = exp.run(format="networkdynamics")

        # Check shape: should have 20 nodes, 1 state variable
        assert ts.data.sizes["node"] == 20, f"Expected 20 nodes, got {ts.data.sizes['node']}"
        # Check convergence: all nodes should converge to same value
        final_states = ts.data.isel(time=-1).sel(variable="v")
        assert np.std(final_states) < 0.1, f"Diffusion should converge: std={np.std(final_states):.4f}"

    def test_kuramoto_numerical(self, julia_runner):
        """Kuramoto: TVBO result has correct shape and reasonable dynamics."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        ts = exp.run(format="networkdynamics")

        # Check shape: 8 nodes, 1 state variable (theta)
        assert ts.data.sizes["node"] == 8, f"Expected 8 nodes, got {ts.data.sizes['node']}"
        # Phases should grow over time (oscillators)
        node0_theta = ts.data.sel(variable="theta", node="0")
        assert node0_theta.isel(time=-1).item() != node0_theta.isel(time=0).item(), "Phase should change over time"

    def test_fhn_numerical(self, julia_runner):
        """FHN: TVBO result has correct shape and shows synchronization."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "fitzhugh_nagumo.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        ts = exp.run(format="networkdynamics")

        # Check shape: 90 nodes, 2 state variables (u, v)
        assert ts.data.sizes["node"] == 90, f"Expected 90 nodes, got {ts.data.sizes['node']}"
        assert ts.data.sizes["variable"] == 2, f"Expected 2 state vars, got {ts.data.sizes['variable']}"
        # u variables should be bounded (no numerical explosion)
        u_data = ts.data.sel(variable="u")
        assert np.all(np.abs(u_data) < 50), f"u should be bounded: max={np.max(np.abs(u_data)):.1f}"

    def test_diffusion_2d_numerical(self, julia_runner):
        """2D diffusion: TVBO result has correct shape and converges."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "diffusion_2d.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        ts = exp.run(format="networkdynamics")

        # Check shape: 10 nodes, 2 state variables (x, phi)
        assert ts.data.sizes["node"] == 10, f"Expected 10 nodes, got {ts.data.sizes['node']}"
        assert ts.data.sizes["variable"] == 2, f"Expected 2 state vars, got {ts.data.sizes['variable']}"
        # Both x and phi should converge (diffusion)
        for sv_name in ts.data.coords["variable"].values:
            final = ts.data.isel(time=-1).sel(variable=sv_name)
            assert np.std(final) < 0.15, f"SV {sv_name} should converge: std={np.std(final):.4f}"

    def test_heterogeneous_kuramoto_numerical(self, julia_runner):
        """Heterogeneous Kuramoto: correct shape with mixed vertex types."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "heterogeneous_kuramoto.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        ts = exp.run(format="networkdynamics")

        # Proper (time, variable, node) shape with named coordinates
        assert "variable" in ts.data.dims
        assert "node" in ts.data.dims
        # Non-NaN states should be finite (NaN expected for static nodes and variables not present on all node types)
        vals = ts.data.values
        assert np.all(np.isfinite(vals[~np.isnan(vals)])), "Non-NaN states should be finite"

    def test_cascading_failure_numerical(self, julia_runner):
        """Cascading failure: identical to reference Julia implementation."""
        ref = _load_reference("cascading_failure")
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "cascading_failure.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        ts = exp.run(format="networkdynamics")

        # 5 nodes, 2 state variables (delta, omega)
        assert ts.data.sizes["node"] == 5, f"Expected 5 nodes, got {ts.data.sizes['node']}"
        assert ts.data.sizes["variable"] == 2, f"Expected 2 state vars, got {ts.data.sizes['variable']}"
        # States should be bounded (no numerical explosion from cascade)
        assert np.all(np.isfinite(ts.data)), "All states should be finite"
        assert np.max(np.abs(ts.data)) < 100, f"States should be bounded: max={np.max(np.abs(ts.data)):.1f}"
        # Numerical identity with reference
        tvbo_flat = np.zeros((len(ts.time), 10))
        for node in range(5):
            tvbo_flat[:, node * 2] = ts.data.sel(variable="delta", node=str(node))
            tvbo_flat[:, node * 2 + 1] = ts.data.sel(variable="omega", node=str(node))
        assert np.allclose(ts.time, ref["t"]), "Time vectors must match"
        assert np.allclose(tvbo_flat, ref["u"], atol=1e-8), (
            f"States must match reference: max diff={np.max(np.abs(tvbo_flat - ref['u'])):.2e}"
        )

    def test_stress_on_truss_numerical(self, julia_runner):
        """Stress on truss: heterogeneous vertices, beams, states bounded."""
        from tvbo import SimulationExperiment

        yaml_path = os.path.join(EXAMPLES_DIR, "stress_on_truss.yaml")
        exp = SimulationExperiment.from_file(yaml_path)
        ts = exp.run(format="networkdynamics")

        # Heterogeneous: 11 nodes (9 free + 2 static), 4 unique SVs
        assert ts.data.sizes["variable"] == 4, f"Expected 4 unique state variables, got {ts.data.sizes['variable']}"
        assert ts.data.sizes["node"] == 11, f"Expected 11 nodes, got {ts.data.sizes['node']}"
        # Non-NaN states should be finite (no structural collapse)
        vals = ts.data.values
        assert np.all(np.isfinite(vals[~np.isnan(vals)])), "Non-NaN states should be finite"


# Test 4: Reference data validation (no Julia needed, only HDF5)
class TestReferenceData:
    """Validate the HDF5 reference data itself for consistency."""

    def test_diffusion_reference_shape(self):
        ref = _load_reference("diffusion")
        assert ref["t"].shape == (201,)
        assert ref["u"].shape[1] == 20  # 20 nodes
        assert ref["u"].shape[0] == 201  # 201 time points
        assert ref["x0"].shape == (20,)

    def test_diffusion_reference_convergence(self):
        """Diffusion should converge toward uniform state."""
        ref = _load_reference("diffusion")
        final = ref["u"][-1, :]  # last timestep, all nodes
        assert np.std(final) < 0.15, f"Diffusion should converge: std={np.std(final):.6f}"

    def test_kuramoto_reference_shape(self):
        ref = _load_reference("kuramoto")
        assert ref["t"].shape == (201,)
        assert ref["u"].shape[1] == 8
        assert ref["u"].shape[0] == 201
        assert ref["omega0"].shape == (8,)

    def test_kuramoto_reference_frequencies(self):
        """Omega0 should be centered and span [1/N, 1]."""
        ref = _load_reference("kuramoto")
        ω = ref["omega0"]
        assert abs(np.sum(ω)) < 1e-10, f"ω should be centered: sum={np.sum(ω)}"
        assert ω.shape == (8,)

    def test_fhn_reference_shape(self):
        ref = _load_reference("fitzhugh_nagumo")
        assert ref["t"].shape == (2001,)
        # 90 nodes × 2 state vars = 180 states
        assert ref["u"].shape[1] == 180
        assert ref["u"].shape[0] == 2001

    def test_fhn_reference_bounded(self):
        """FHN states should be bounded (no numerical explosion)."""
        ref = _load_reference("fitzhugh_nagumo")
        assert np.all(np.isfinite(ref["u"])), "All states should be finite"
        assert np.max(np.abs(ref["u"])) < 50, f"States should be bounded: max={np.max(np.abs(ref['u'])):.1f}"

    def test_fhn_connectivity_matrix(self):
        """FHN connectivity matrix should be 90×90 with correct sparsity."""
        ref = _load_reference("fitzhugh_nagumo")
        G = ref["G"]
        assert G.shape == (90, 90)
        # Not fully connected, not empty
        n_edges = np.count_nonzero(G)
        assert 1000 < n_edges < 8100, f"Expected ~7793 edges, got {n_edges}"

    # -- 2D Diffusion reference data --

    def test_diffusion_2d_reference_shape(self):
        """2D Diffusion reference: 301 timesteps, 20 states (10 nodes × 2 SVs)."""
        ref = _load_reference("diffusion_2d")
        assert ref["t"].shape == (301,)
        # 10 nodes × 2 state vars = 20 interleaved states
        assert ref["u"].shape[0] == 301
        assert ref["u"].shape[1] == 20

    def test_diffusion_2d_reference_convergence(self):
        """2D Diffusion: both state variables should converge."""
        ref = _load_reference("diffusion_2d")
        final = ref["u"][-1, :]  # last timestep, all states
        # x states (even indices), phi states (odd indices)
        x_final = final[0::2]
        phi_final = final[1::2]
        assert np.std(x_final) < 0.5, f"x should converge: std={np.std(x_final):.4f}"
        assert np.std(phi_final) < 0.5, f"phi should converge: std={np.std(phi_final):.4f}"

    # -- Heterogeneous Kuramoto reference data --

    def test_heterogeneous_kuramoto_reference_shape(self):
        """Heterogeneous Kuramoto reference: 201 timesteps, mixed state dim."""
        ref = _load_reference("heterogeneous_kuramoto")
        assert ref["t"].shape == (201,)
        # Node dimensions: 0(static)=0, 1-3(kuramoto)=1, 4(inertia)=2, 5-7(kuramoto)=1
        # Total: 0 + 1+1+1 + 2 + 1+1+1 = 8 states
        assert ref["u"].shape[0] == 201

    def test_heterogeneous_kuramoto_reference_bounded(self):
        """Heterogeneous Kuramoto: all states should be finite and bounded."""
        ref = _load_reference("heterogeneous_kuramoto")
        assert np.all(np.isfinite(ref["u"])), "All states should be finite"

    def test_heterogeneous_kuramoto_vertex_types_data(self):
        """Heterogeneous Kuramoto: vertex types are correctly stored."""
        ref = _load_reference("heterogeneous_kuramoto")
        if "vertex_types" in ref:
            vtypes = ref["vertex_types"]
            assert len(vtypes) == 8

    # -- Cascading Failure reference data --

    def test_cascading_failure_reference_shape(self):
        """Cascading failure: saveat=0.01 over 6s + callback interpolation."""
        ref = _load_reference("cascading_failure")
        # Callback events may add extra interpolated points
        assert ref["t"].shape[0] >= 601
        assert ref["u"].shape[0] == ref["t"].shape[0]
        assert ref["u"].shape[1] == 10  # 5 nodes × 2 SVs

    def test_cascading_failure_reference_bounded(self):
        """Cascading failure: states should be bounded (no numerical explosion)."""
        ref = _load_reference("cascading_failure")
        assert np.all(np.isfinite(ref["u"])), "All states should be finite"
        assert np.max(np.abs(ref["u"])) < 100, f"States should be bounded: max={np.max(np.abs(ref['u'])):.1f}"

    def test_cascading_failure_adjacency(self):
        """Cascading failure: 5×5 adjacency matrix with 7 edges."""
        ref = _load_reference("cascading_failure")
        adj = ref["adjacency"]
        assert adj.shape == (5, 5)
        n_edges = np.count_nonzero(adj)
        assert n_edges == 14  # 7 undirected edges × 2

    # -- Stress on Truss reference data --

    def test_stress_on_truss_reference_shape(self):
        """Stress on truss: 1201 timesteps, 36 states (9 free × 4 SVs)."""
        ref = _load_reference("stress_on_truss")
        assert ref["t"].shape == (1201,)
        assert ref["u"].shape[0] == 1201  # timesteps
        assert ref["u"].shape[1] == 36  # 9 free nodes × 4 SVs

    def test_stress_on_truss_reference_bounded(self):
        """Stress on truss: states should be bounded (no numerical explosion)."""
        ref = _load_reference("stress_on_truss")
        assert np.all(np.isfinite(ref["u"])), "All states should be finite"

    def test_stress_on_truss_adjacency(self):
        """Stress on truss: 11×11 adjacency matrix with 18 edges."""
        ref = _load_reference("stress_on_truss")
        adj = ref["adjacency"]
        assert adj.shape == (11, 11)
        n_edges = np.count_nonzero(adj)
        assert n_edges == 36  # 18 undirected edges × 2


# Test 5: URL validation (no Julia needed)
class TestDocURLs:
    """Verify that documentation URLs in YAML files are valid."""

    @pytest.fixture(
        params=[
            "diffusion",
            "kuramoto",
            "fitzhugh_nagumo",
            "diffusion_2d",
            "heterogeneous_kuramoto",
            "cascading_failure",
            "stress_on_truss",
        ]
    )
    def yaml_path(self, request):
        return os.path.join(EXAMPLES_DIR, f"{request.param}.yaml")

    def test_yaml_urls_use_generated_path(self, yaml_path):
        """All URLs should use /stable/generated/ path (not bare /stable/)."""
        import yaml

        with open(yaml_path) as f:
            spec = yaml.safe_load(f)
        refs = spec.get("references", [])
        for url in refs:
            if "NetworkDynamics.jl" in url:
                assert "/generated/" in url, f"URL should use /generated/ path: {url}"
                # Check it doesn't use old format
                assert url.count("/stable/") == 1, f"URL has duplicate /stable/: {url}"
