#!/usr/bin/env python3
"""${name} — generated by tvbo bsplot figure codegen.

Self-contained: opens the result containers, draws each panel, saves the figure.
Edit freely — it is a normal Python file.
"""
from __future__ import annotations

import functools

import numpy as np
import xarray as xr
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import bsplot
from bsplot import panels as _bpanels
from tvbo.adapters.bsplot import TRANSFORMS as _TF, CUSTOM_PANELS as _CP, registered as _registered
% for m in code_modules:
import ${m}  # noqa: F401 — registers this study's custom panels/transforms into _CP / _TF
% endfor


@functools.lru_cache(maxsize=None)
def _open(path):
    """Open a run's result container once per distinct path (xarray)."""
    return xr.open_dataset(path, engine="h5netcdf")


def _placeholder(ax, label):
    """Honest labelled placeholder when a panel's data is missing/degenerate."""
    ax.text(0.5, 0.5, label, ha="center", va="center", transform=ax.transAxes, wrap=True)
    ax.set_xticks([]); ax.set_yticks([])


def _coord(da, name, axis):
    """Coordinate values along a named dim, or an integer index if it has no coord."""
    if name and name in da.coords:
        return np.asarray(da.coords[name].values)
    return np.arange(da.shape[axis])


def _apply_axopts(ax, o):
    """Apply a grammar panel's resolved axis directives (labels, limits, ticks, legend)."""
    if o.get("axhline") is not None:
        ax.axhline(o["axhline"], color="0.6", lw=0.7, ls=":", zorder=0)
    if o.get("xlabel") is not None:
        ax.set_xlabel(o["xlabel"])
    if o.get("ylabel") is not None:
        ax.set_ylabel(o["ylabel"])
    if o.get("title"):
        ax.set_title(o["title"])
    if o.get("xlim"):
        ax.set_xlim(*o["xlim"])
    if o.get("ylim"):
        ax.set_ylim(*o["ylim"])
    if o.get("xticks") is not None:
        ax.set_xticks(o["xticks"])
    if o.get("yticks") is not None:
        ax.set_yticks(o["yticks"])
    if o.get("hide_xticklabels"):
        ax.set_xticklabels([])
    if o.get("hide_yticklabels"):
        ax.set_yticklabels([])
    if o.get("legend"):
        ax.legend(loc=o["legend"] if isinstance(o["legend"], str) else "best",
                  frameon=False)


% for p in panels:
def _panel_${p['key']}(fig, ax):
    """Panel ${p['key']} — ${p['kind']}."""
% if p['kind'] == 'image':
    ax.imshow(plt.imread(${repr(p['path'])}), origin="upper")
    ax.axis("off")
% elif p['kind'] == 'custom':
    _registered(_CP, ${repr(p['render'])}, "custom panel")(fig, ax, ${repr(p['ctx'])})
% else:
% for L in p['layers']:
    _ds = _open(${repr(L['container'])})
    _da = _ds[${repr(L['output'])}]
% if L['transform']:
    _da = _registered(_TF, ${repr(L['transform'])}, "transform")(_da)
% endif
% if L['sel'] is not None:
    _da = _da.sel(${repr(L['sel'])}, method=${repr(L['sel_method'])})
% endif
% if L['mark'] == 'heatmap':
    _C = np.asarray(_da.values)
    _x = _coord(_da, ${repr(L['x'])}, 0)
    _y = _coord(_da, ${repr(L['y'])}, 1)
    if _C.shape == (len(_x), len(_y)):
        _C = _C.T                                   # orient to (y, x) for pcolormesh
    _im = ax.pcolormesh(_x, _y, _C, shading="auto")
    fig.colorbar(_im, ax=ax)
% elif L['mark'] == 'scatter':
    _x = _coord(_da, ${repr(L['x'])}, 0)
    ax.scatter(_x, np.asarray(_da.values).squeeze(), **${repr(L['style'])})
% else:
    _x = _coord(_da, ${repr(L['x'])}, 0)
    ax.plot(_x, np.asarray(_da.values).squeeze(), **${repr(L['style'])})
% endif
% endfor
    _apply_axopts(ax, ${repr(p['axopts'])})
% endif
% if p['title']:
    ax.set_title(${repr(p['title'])})
% endif
% for a in p['annotations']:
    ax.text(${a['x']}, ${a['y']}, ${repr(a['text'])}, transform=ax.transAxes, ha="center", va="center")
% endfor


% endfor
def main():
% for s in style:
% if not s['path']:
    bsplot.style.use(${repr(s['value'])})
% endif
% endfor
% if font_size:
    plt.rcParams.update({_k: ${font_size} for _k in (          # metadata base: every element the same size by default
        "font.size", "axes.labelsize", "axes.titlesize",
        "xtick.labelsize", "ytick.labelsize", "legend.fontsize", "figure.titlesize")})
% endif
% for s in style:
% if s['path']:
    plt.style.use(${repr(s['value'])})              # study .mplstyle last: overrides individual sizes if it sets them
% endif
% endfor
% if spine_rcparams:
    plt.rcParams.update(${repr(spine_rcparams)})
% endif
    fig, axd = bsplot.figure.subplots(**${repr(subplots_kwargs)})
    try:                                            # tvbo prefers the "compressed" engine (packs
        fig.set_layout_engine("compressed")         # fixed-aspect axes tightly, less whitespace);
    except Exception:                               # fall back to "tight" where compressed can't apply.
        fig.set_layout_engine("tight")

% for p in panels:
% if p['placeholder']:
    try:
        _panel_${p['key']}(fig, axd[${repr(p['key'])}])
    except (FileNotFoundError, OSError, KeyError, ValueError, IndexError):
        _placeholder(axd[${repr(p['key'])}], ${repr(p['placeholder'])})
% else:
    _panel_${p['key']}(fig, axd[${repr(p['key'])}])
% endif
% endfor

% if auto_format:
    bsplot.style.format_fig(fig, add_panel_numbers=False)   # normalise ticks/labels; panel letters below
% endif
% for p in panels:
% if p['kind'] == 'image':
    _iax = axd[${repr(p['key'])}]            # keep image top-down (format_fig normalises the y-axis)
    if _iax.get_ylim()[0] < _iax.get_ylim()[1]:
        _iax.invert_yaxis()
% endif
% endfor
% if panel_numbers:
% for p in panels:
    _bpanels.add_panel_number(axd[${repr(p['key'])}], ${repr(p['letter'])}, **${repr(p['number_kwargs'])})
% endfor
% endif
    fig.savefig(${repr(outfile)}, **${repr(savefig_kwargs)})
    print("wrote", ${repr(outfile)})
    return fig


if __name__ == "__main__":
    main()
