#!/usr/bin/env python3
"""${name} — generated by tvbo bsplot figure codegen.

Self-contained: opens the result containers, draws each panel, saves the figure.
Edit freely — it is a normal Python file.
"""
from __future__ import annotations

import functools

import numpy as np
import xarray as xr
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import bsplot
from bsplot import panels as _bpanels
from tvbo.adapters.bsplot import (TRANSFORMS as _TF, CUSTOM_PANELS as _CP,
                                  load_layer as _load_layer, registered as _registered,
                                  scale_colormap as _scale_cmap)
from tvbo.data.dataref import match_output as _match_output
% for m in code_modules:
import ${m}  # noqa: F401 — registers this study's custom panels/transforms into _CP / _TF
% endfor


@functools.lru_cache(maxsize=None)
def _open(path):
    """Open a run's result container once per distinct path (xarray)."""
    return xr.open_dataset(path, engine="h5netcdf")


def _var(ds, output):
    """The data-variable a layer's ``output`` names, via the shared ``DataRef`` rule.

    A recorded state variable is stored under its own name, while an observation, an
    analysis result or an estimate carries an ``observation__``/``estimate__`` prefix. A
    figure names the quantity, not the storage convention, so both resolve — through the
    one matcher every other consumer uses, not a copy of it.
    """
    return ds[_match_output(ds.data_vars, output)]


def _mesh_style(style, values):
    """Mesh kwargs from a declared style, with the colormap resolved and any ``center`` folded in.

    Both go through :func:`tvbo.adapters.bsplot.scale_colormap`, the same call the standalone
    ``kind: colorbar`` panel makes, so a bar cannot key a mesh that was built from a different
    map. An undeclared colormap stays undeclared: the mesh then takes the stylesheet's own.
    """
    kw = dict(style)
    c = kw.pop("center", None)
    if c is None:
        if kw.get("cmap") is not None:
            kw["cmap"] = _scale_cmap(kw["cmap"])
        return kw
    finite = np.asarray(values)[np.isfinite(values)]
    lo = float(kw["vmin"]) if kw.get("vmin") is not None else float(finite.min())
    hi = float(kw["vmax"]) if kw.get("vmax") is not None else float(finite.max())
    kw["cmap"] = _scale_cmap(kw.get("cmap"), lo, hi, float(c))
    kw["vmin"], kw["vmax"] = lo, hi
    return kw


def _distinct_ticks(fig):
    """Widen the decimals of any linear axis whose ticks print the same number twice.

    A tick budget small enough for a dense cell can put two neighbouring values inside one
    rounding step, and the axis then reads "0.00113, 0.00113" — two marks, one number, no
    scale. The reader cannot recover the spacing from that, so the axis carries whatever
    precision it takes to tell its own ticks apart.

    It judges the DRAWN labels, which is why it is a pass over the finished figure rather than
    one more directive in ``_apply_axopts``: a tick formatter carries state a draw establishes,
    so asking one for a string before then answers for every axis alike and would re-round the
    axes that were already fine. A colourbar is left alone — panel-attached or standing in its
    own slot, its own pass has already written the precision the spec asked for — and so is any
    axis whose labels are not numbers, where a repeat is two entries with the same name rather
    than a rounding collision.
    """
    from matplotlib.ticker import FormatStrFormatter

    fig.canvas.draw()
    _bars = {id(_cb.ax) for _cb, _ in _COLORBAR_POST} | {id(_a) for _a in _SCALE_AXES.values()}
    pending, seen = list(fig.axes), []
    while pending:                          # a grid's cells are child_axes, not fig.axes
        ax = pending.pop()
        seen.append(ax)
        pending.extend(getattr(ax, "child_axes", []))
    for ax in seen:
        if id(ax) in _bars:
            continue
        for axis, scale in ((ax.xaxis, ax.get_xscale()), (ax.yaxis, ax.get_yscale())):
            if scale != "linear":
                continue
            lo, hi = sorted(axis.get_view_interval())
            locs, texts = list(axis.get_majorticklocs()), [t.get_text() for t in axis.get_ticklabels()]
            if len(locs) != len(texts):
                continue
            shown = [(v, s) for v, s in zip(locs, texts) if lo <= v <= hi and s]
            if len(shown) < 2 or len({s for _, s in shown}) == len(shown) or not all(_numeric_text(s) for _, s in shown):
                continue
            vals = [v for v, _ in shown]
            for d in range(1, 12):
                if len({f"%.{d}f" % v for v in vals}) == len(vals):
                    axis.set_major_formatter(FormatStrFormatter(f"%.{d}f"))
                    break


def _numeric_text(text):
    """True when a drawn tick label is the number it sits at, minus signs and all."""
    try:
        float(text.replace("\N{MINUS SIGN}", "-"))
    except ValueError:
        return False
    return True


def _format_colorbar(cb, decimals):
    """Colourbar ticks that carry their own magnitude, dropping one that collides with a neighbour.

    A slim bar has nowhere to put a shared exponent: factored out, a field spanning 3e4 reads
    "3, 1, 0" and one spanning 1e-4 reads "3, 0, -1". So each tick is written in full — to
    *decimals* where the spec declares them, and with `%g` otherwise. The tick rule places one
    at each end and one at the centre value; when the data barely crosses that centre, two land
    on the same pixel and print over each other, so the middle one goes.
    """
    bsplot.style.format_colorbar(cb, colorbar_decimals=decimals)
    ax = cb.ax
    _pos, (_fw, _fh) = ax.get_position(), ax.figure.get_size_inches()
    _thick = 72 * min(_pos.width * _fw, _pos.height * _fh)
    ax.tick_params(length=min(float(plt.rcParams["ytick.major.size"]), 0.5 * _thick))   # the bar is thinner than the figure's own tick is long
    vertical = str(getattr(cb, "orientation", "vertical")) != "horizontal"   # the bar's declared orientation, not its slot's shape
    axis, lim = (ax.yaxis, ax.get_ylim()) if vertical else (ax.xaxis, ax.get_xlim())
    ticks = list(axis.get_ticklocs())
    span = abs(lim[1] - lim[0]) or 1.0
    keep = [t for i, t in enumerate(ticks)
            if i in (0, len(ticks) - 1) or min(abs(t - ticks[0]), abs(t - ticks[-1])) / span > 0.12]
    if len(keep) != len(ticks):
        axis.set_ticks(keep)
    _fmt = axis.get_major_formatter() if decimals is not None else (lambda v, pos: _tick_text(v))
    axis.set_major_formatter(lambda v, pos: _zeroless(_fmt(v, pos)))


def _tick_text(v):
    """A colourbar tick written in full, at a precision that suits its own magnitude."""
    a = abs(v)
    if a == 0:
        return "0"
    if a >= 1e4:
        return f"{v:.0f}"
    return f"{v:.4g}" if a >= 1 else f"{v:g}"


def _zeroless(text):
    """A tick label stripped of a minus sign it only has because the value rounds to zero.

    At the printed precision the value IS zero, and "-0.00000" reads as a distinct negative
    quantity rather than the end of a scale that stops at nothing.
    """
    return text.lstrip("-") if text.lstrip("-").strip("0.") == "" else text


_PLACEHOLDER_AXES = []          # re-bared after the format pass, which re-derives ticks
_INSET_POST = []                # (inset axes, declared frame) — the tidy-up must not win over it
_COLORBAR_POST = []             # (colourbar, decimals) — same rule, for a bar whose scale is declared
_SCALE_AXES = {}                # panel key -> the bar inside a `kind: colorbar` slot, which is what a declared frame is about


def _bare(ax):
    """Strip a placeholder slot to a dashed grey outline: it holds the paper's layout
    position but must never read as a drawn-and-empty panel."""
    ax.set_xticks([]); ax.set_yticks([])
    for _s in ax.spines.values():
        _s.set_visible(True); _s.set_color("0.75"); _s.set_linestyle((0, (4, 4)))
        _s.set_linewidth(0.6)


def _wrap(ax, text, pad=0.88):
    """Wrap text to the AXES width — matplotlib's ``wrap=True`` wraps to the figure edge,
    so a long placeholder label would otherwise run across its neighbours."""
    import textwrap

    width_pt = ax.get_window_extent().width / ax.figure.dpi * 72.0 * pad
    n = max(14, int(width_pt / (0.5 * plt.rcParams.get("font.size", 10.0))))
    return "\n".join(textwrap.fill(line, n) for line in str(text).splitlines())


def _placeholder(ax, label):
    """Honest labelled placeholder when a panel's data is missing/degenerate."""
    ax.text(0.5, 0.5, _wrap(ax, label), ha="center", va="center", transform=ax.transAxes,
            color="0.35", style="italic")
    _bare(ax)
    _PLACEHOLDER_AXES.append(ax)


def _triangle(C, which, gap=0):
    """One triangle of a square matrix, the other half NaN, so two layers compose one image.

    The halves are named as drawn: with the matrix convention (row 0 at top, ``invert_y``)
    ``upper`` is the top-right triangle. ``gap`` widens the matrix by that many cells and
    slides the two halves apart along the diagonal, leaving a blank band between them —
    without it the two quantities touch and read as one field.
    """
    if C.ndim != 2 or C.shape[0] != C.shape[1]:
        raise ValueError(f"triangle needs a square matrix, got shape {C.shape}")
    n, g = C.shape[0], int(gap)
    out = np.full((n + g, n + g), np.nan)
    ones = np.ones(C.shape, dtype=bool)
    if which == "upper":
        keep = np.triu(ones, 1)
        out[:n, g:] = np.where(keep, C, np.nan)      # slid right, above the band
    else:
        keep = np.tril(ones, -1)
        out[g:, :n] = np.where(keep, C, np.nan)      # slid down, below the band
    return out


def _color_dim(da, name):
    """The dimension a colour encoding iterates, and the labels for its entries.

    ``color`` may name a dimension (labels are its coordinate values, or indices when it
    has none) or a NON-dimension coordinate defined along one — which is how a panel draws
    one line per region and still labels them by name rather than by atlas number.
    """
    if name in da.dims:
        vals = da.coords[name].values if name in da.coords else np.arange(da.sizes[name])
        return name, [str(v) for v in vals]
    if name not in da.coords:
        raise KeyError(f"colour encoding {name!r} is neither a dim nor a coord "
                       f"(dims {tuple(da.dims)}, coords {tuple(da.coords)}).")
    coord = da.coords[name]
    return str(coord.dims[0]), [str(v) for v in np.asarray(coord.values)]


def _coord(da, name, axis):
    """Coordinate values along a named dim, or an integer index if it has no coord."""
    if name and name in da.coords:
        return np.asarray(da.coords[name].values)
    return np.arange(da.shape[axis])


def _bounds(da, x, output):
    """The two edges of a ``band`` layer, as ``(lower, upper)`` over *x*.

    A band spans two series, so its output carries a length-2 axis beside the swept one —
    the analysis returns the pair in ONE labelled array rather than the figure binding two
    outputs and trusting them to stay in step.
    """
    v = np.asarray(da.values)
    if v.ndim != 2 or 2 not in v.shape:
        raise ValueError(
            f"band layer {output!r}: needs a (n, 2) output holding the two edges of the "
            f"band, got shape {v.shape}."
        )
    v = v if v.shape[0] == len(x) else v.T
    return v[:, 0], v[:, 1]


def _apply_tick_format(ax, o):
    """Tick notation: 'sci' factors a shared exponent out to the axis corner, 'plain' writes it in full.

    A row of small panels whose values span 1e-5 cannot print its ticks in full without the
    neighbours running together, which is why the published figure carries the magnitude once at
    the corner. The format pass installs a fixed-point formatter, so a declared notation has to be
    re-applied after it, like a declared rotation.
    """
    from matplotlib.ticker import ScalarFormatter
    for _axis, _key in ((ax.xaxis, "xtick_format"), (ax.yaxis, "ytick_format")):
        _mode = o.get(_key)
        if _mode is None:
            continue
        _fmt = ScalarFormatter(useMathText=True)
        _fmt.set_scientific(str(_mode) == "sci")
        if str(_mode) == "sci":
            _fmt.set_powerlimits((-2, 3))
        _axis.set_major_formatter(_fmt)


def _apply_tick_rotation(ax, o):
    """Slant a panel's tick labels, in degrees counter-clockwise.

    Separate from the rest of ``_apply_axopts`` because the format pass resets tick parameters,
    so a declared rotation has to be re-applied after it — the same rule that governs declared
    ticks and colourbar decimals. A rotated x label is anchored at its tick rather than centred
    under it, which is what stops a dense row of panels running its numbers together.
    """
    for _axis, _key in (("x", "xtick_rotation"), ("y", "ytick_rotation")):
        if o.get(_key) is None:
            continue
        _rot = float(o[_key])
        ax.tick_params(axis=_axis, labelrotation=_rot)
        if _axis == "x" and _rot % 180:
            for _lab in ax.get_xticklabels():
                _lab.set_rotation_mode("anchor")
                _lab.set_ha("right" if _rot > 0 else "left")


def _apply_axopts(ax, o):
    """Apply a grammar panel's resolved axis directives (labels, limits, ticks, legend)."""
    for _key, _draw in (("axhline", ax.axhline), ("axvline", ax.axvline)):
        _at = o.get(_key)
        if _at is None:
            continue
        _at = list(_at) if isinstance(_at, (list, tuple)) else [_at]
        _c = o.get(_key + "_color", "0.6")   # one colour, or one per rule where they name different things
        _c = list(_c) if isinstance(_c, (list, tuple)) else [_c]
        for _i, _v in enumerate(_at):
            _draw(_v, color=_c[min(_i, len(_c) - 1)], lw=0.7, ls=":", zorder=0)
    for _ax, _key, _far in ((ax.xaxis, "xtick_side", "top"), (ax.yaxis, "ytick_side", "right")):
        _side = o.get(_key)
        if _side:                       # ticks and label on the named side, as the paper prints them
            _ax.set_ticks_position(str(_side))
            _ax.set_label_position(str(_side))
            if str(_side) == _far:
                ax.spines[_far].set_visible(True)
    for _ax, _key in ((ax.xaxis, "xlabel_side"), (ax.yaxis, "ylabel_side")):
        if o.get(_key):                 # the label alone crosses the axis; the tick numbers stay put
            _ax.set_label_position(str(o[_key]))
    _reg = o.get("region")
    if _reg is not None:                            # a window RINGED on the field, not shaded over it
        from matplotlib.patches import Rectangle
        _x0, _x1, _y0, _y1 = [float(v) for v in _reg]
        ax.add_patch(Rectangle((_x0, _y0), _x1 - _x0, _y1 - _y0, fill=False, zorder=5,
                               edgecolor=o.get("region_color", "w"), linewidth=0.8,
                               linestyle=(0, (3, 2))))
    if o.get("xlabel") is not None:
        ax.set_xlabel(o["xlabel"], **({"labelpad": float(o["xlabel_pad"])} if o.get("xlabel_pad") is not None else {}))
    if o.get("ylabel") is not None:
        ax.set_ylabel(o["ylabel"], **({"labelpad": float(o["ylabel_pad"])} if o.get("ylabel_pad") is not None else {}))
    if o.get("title"):
        ax.set_title(o["title"])
    if o.get("xscale"):
        ax.set_xscale(o["xscale"])
    if o.get("yscale"):
        ax.set_yscale(o["yscale"])
    if o.get("xlim"):
        ax.set_xlim(*o["xlim"])
    if o.get("ylim"):
        ax.set_ylim(*o["ylim"])
    if o.get("frame") in ("off", False):
        ax.set_frame_on(False)                      # a matrix has no measurable axis
        ax.set_xticks([]); ax.set_yticks([])
    if o.get("aspect"):
        ax.set_aspect(o["aspect"])
    if o.get("box_aspect"):
        ax.set_box_aspect(o["box_aspect"])           # frame shape, independent of the data ranges
    if o.get("invert_x"):
        ax.invert_xaxis()
    if o.get("invert_y"):
        ax.invert_yaxis()
    if o.get("nbins") or o.get("tick_prune"):
        from matplotlib.ticker import MaxNLocator   # a declared tick budget; either directive stands on its own
        _loc = {"nbins": o.get("nbins") or "auto", "prune": o.get("tick_prune") or None}
        ax.xaxis.set_major_locator(MaxNLocator(**_loc))
        ax.yaxis.set_major_locator(MaxNLocator(**_loc))
    if o.get("xticks") is not None:
        ax.set_xticks(o["xticks"])
    if o.get("yticks") is not None:
        ax.set_yticks(o["yticks"])
    if o.get("hide_xticklabels"):
        ax.set_xticklabels([])
    if o.get("hide_yticklabels"):
        ax.set_yticklabels([])
    _ticks = {_k: float(o[_v]) for _k, _v in (("labelsize", "tick_size"), ("length", "tick_length")) if o.get(_v)}
    if _ticks:
        ax.tick_params(**_ticks)          # a dense grid's cells cannot carry the figure's own tick geometry
    _apply_tick_format(ax, o)
    _apply_tick_rotation(ax, o)
    if o.get("legend"):
        ax.legend(loc=o["legend"] if isinstance(o["legend"], str) else "best",
                  frameon=False)


def _channel(ds, da, name, axis=0):
    """One 1-D channel of a panel, by NAME: a data_var, a value along a component coord
    (e.g. select ``E`` along a ``var=[E,x,u]`` dim), or the index if the name is a plain dim.

    Serves the depth axis of a line3d panel and the colour of a shaded scatter — both ask the
    same question (give me this named quantity, one value per point) and must answer it the
    same way, so a panel's z and its c cannot resolve a name differently.

    A coord of the plotted array wins over a same-named sibling variable: it is aligned to the
    points by construction, where a sibling is only aligned if its shape happens to agree. Both
    the coord and the index fallback are read through :func:`_coord`, so a name resolves to a
    coordinate in exactly one place."""
    coords = getattr(da, "coords", {})
    if name and name not in coords:
        for c in coords:
            vals = np.asarray(da.coords[c].values)
            if vals.dtype.kind in "US" and name in set(vals.tolist()):
                dim = da.coords[c].dims[0] if da.coords[c].dims else c
                return np.asarray(da.sel({dim: name}).values).squeeze()
        try:                              # a sibling variable, under whatever prefix it is stored
            return np.asarray(_var(ds, name).values).squeeze()
        except KeyError:
            pass
    return _coord(da, name, axis)


def _apply_axopts3d(ax, o):
    """3-D axis directives for a line3d panel: labels, limits, camera, per-axis inversion,
    and an opaque white box (no default grey panes). Applied after the 2-D-shared labels."""
    if o.get("zlabel") is not None:
        ax.set_zlabel(o["zlabel"], labelpad=float(o.get("zlabel_pad", 4.0)))
    if o.get("zlim"):
        ax.set_zlim(*o["zlim"])
    if o.get("elev") is not None or o.get("azim") is not None:
        ax.view_init(elev=o.get("elev", ax.elev), azim=o.get("azim", ax.azim))
    if o.get("invert_z"):
        ax.invert_zaxis()
    if o.get("zoom"):                                 # fill the cell (3-D axes reserve big margins)
        try:
            ax.set_box_aspect(None, zoom=o["zoom"])
        except TypeError:
            pass                                      # older mpl without the zoom kwarg
    for _pa in (ax.xaxis, ax.yaxis, ax.zaxis):        # white box, faint edges
        _pa.pane.set_facecolor("white"); _pa.pane.set_alpha(1.0); _pa.pane.set_edgecolor("0.8")


def _panel_number(ax, label, kwargs):
    """Draw a panel's letter, including on a 3-D axes.

    ``Axes3D.text`` takes (x, y, z, s), so the shared 2-D placement call raises there and a
    line3d panel would silently lose its letter — or, as it did, take the whole figure down.
    ``text2D`` is the 3-D axes' own flat-overlay call, which is what a panel letter is."""
    if hasattr(ax, "get_zlim"):   # defaults mirror add_panel_number, so 3-D letters match their 2-D siblings
        ax.text2D(kwargs.get("x_shift", 0.0), 1.0 + kwargs.get("y_shift", 0.0), str(label),
                  transform=ax.transAxes, ha=kwargs.get("ha", "center"), va=kwargs.get("va", "bottom"),
                  fontsize=kwargs.get("fontsize", 16), fontweight="bold")
        return
    _bpanels.add_panel_number(ax, label, **kwargs)


def _cell_axes(ax):
    """A panel's own axes: the primary, any twin sharing its subplot cell, and every INSET
    a composite drawer opened inside it (recursively, twins of those included).

    A composite panel draws its cells as inset axes, which carry no subplotspec — so
    without walking `child_axes` a grid's deliberate per-cell ticks are invisible to the
    snapshot and the figure-wide format pass silently replaces them."""
    axes = [ax]
    sp = ax.get_subplotspec()
    if sp is not None:
        for a in ax.figure.axes:
            if a is not ax and a.get_subplotspec() is sp:
                axes.append(a)
    for a in list(axes):
        for child in getattr(a, "child_axes", ()) or ():
            if child not in axes:
                axes.extend(_cell_axes(child))
    return axes


def _share_scale(axd, keys, axis):
    """Put every panel in *keys* on the union of the group's limits along *axis*.

    A declared shared scale is what makes hidden tick labels honest: without it the
    panels are drawn at whatever range their own data implied, and the reader compares
    two pictures that are not on one scale.
    """
    axes = [axd[k] for k in keys if k in axd]
    if len(axes) < 2:
        return
    get, set_ = (("get_xlim", "set_xlim") if axis == "x" else ("get_ylim", "set_ylim"))
    limits = [getattr(a, get)() for a in axes]
    lo = min(min(l) for l in limits)
    hi = max(max(l) for l in limits)
    for a, (l0, l1) in zip(axes, limits):
        getattr(a, set_)((hi, lo) if l0 > l1 else (lo, hi))


def _snapshot_fixed_axes(ax):
    """Record the tick locator/formatter/limits of a custom panel's axes so the figure-wide
    format pass cannot overwrite ticks the drawer set on purpose.

    bsplot's format pass re-derives evenly spaced ticks for every numeric axis, keeping only
    axes whose labels are strings. A custom drawer, though, often sets meaningful *numeric*
    ticks — a raster's [0, n, 2n] cell axis, a 0-1 twin scale — or an intentionally bare axis
    (``set_yticks([])``). Both cases install a ``FixedLocator``; snapshot exactly those so
    ``_restore_fixed_axes`` can put them back verbatim after the format pass, while axes left
    on an automatic locator still get the tidy shared formatting."""
    from matplotlib.ticker import FixedLocator
    snap = []
    for a in _cell_axes(ax):
        xloc, yloc = a.xaxis.get_major_locator(), a.yaxis.get_major_locator()
        snap.append((a, isinstance(xloc, FixedLocator), isinstance(yloc, FixedLocator),
                     a.get_xlim(), a.get_ylim(), xloc, a.xaxis.get_major_formatter(),
                     yloc, a.yaxis.get_major_formatter()))
    return snap


def _restore_fixed_axes(snap):
    """Put back the drawer's own fixed ticks/limits captured by ``_snapshot_fixed_axes``."""
    for a, x_fixed, y_fixed, xlim, ylim, xloc, xfmt, yloc, yfmt in snap:
        if x_fixed:
            a.xaxis.set_major_locator(xloc); a.xaxis.set_major_formatter(xfmt); a.set_xlim(xlim)
        if y_fixed:
            a.yaxis.set_major_locator(yloc); a.yaxis.set_major_formatter(yfmt); a.set_ylim(ylim)


<%def name="colorbar(p)">\
% if p['colorbar']:
    _cb = fig.colorbar(_im, ax=ax, **${repr(p['colorbar_kwargs'])})   # one scale per panel, not per layer
% if p['colorbar_label']:
    _cb.set_label(${repr(p['colorbar_label'])})
% endif
    _cb.outline.set_linewidth(0.5)
    _COLORBAR_POST.append((_cb, ${repr(None if p['colorbar_decimals'] is None else int(p['colorbar_decimals']))}))   # re-applied after the format pass
% endif
</%def>\
<%def name="draw(p)">\
% if p['placeholder_only']:
    _placeholder(ax, ${repr(p['placeholder'])})
% elif p['kind'] == 'image':
    ax.imshow(plt.imread(${repr(p['path'])}), origin="upper")
    ax.axis("off")
% elif p['kind'] == 'grid':
    ax.axis("off")          # the cells below carry the drawing; this axes is only their frame
% elif p['kind'] in ('colorbar', 'legend'):
    _drawn = _registered(_CP, ${repr(p['render'])}, "custom panel")(fig, ax, ${repr(p['ctx'])})
    if hasattr(_drawn, "xaxis"):
        _SCALE_AXES[${repr(p['key'])}] = _drawn   # the bar, not the slot: a declared frame belongs on it, the panel letter on the slot behind it
% elif p['kind'] in ('custom', 'surface'):
    _registered(_CP, ${repr(p['render'])}, "custom panel")(fig, ax, ${repr(p['ctx'])})
% elif p['kind'] == 'line3d':
    _spec = ax.get_subplotspec(); ax.remove()           # swap the 2-D cell for a 3-D axis
    ax = fig.add_subplot(_spec, projection="3d")
% for L in p['layers']:
    _ds = _open(${repr(L['container'])})
    _da = _var(_ds, ${repr(L['output'])})
% if L['transform']:
    _da = _registered(_TF, ${repr(L['transform'])}, "transform")(_da)
% endif
% if L['sel'] is not None:
    _da = _da.sel(${repr(L['sel'])}, method=${repr(L['sel_method'])})
% endif
    _x = _channel(_ds, _da, ${repr(L['x'])}, 0)
    _y = _channel(_ds, _da, ${repr(L['y'])}, 1)
    _z = _channel(_ds, _da, ${repr(L['z'])}, 2)
% if L['mark'] == 'scatter' and L['color']:
    _im = ax.scatter(_x, _y, _z, c=_channel(_ds, _da, ${repr(L['color'])}),
                     cmap=${repr(L['cmap'] or 'viridis')}, **${repr(L['style'])})
% elif L['mark'] == 'scatter':
    ax.scatter(_x, _y, _z, **${repr(L['style'])})
% else:
    ax.plot(_x, _y, _z, **${repr(L['style'])})
% endif
% endfor
${colorbar(p)}\
    _apply_axopts(ax, ${repr(p['axopts'])})
    _apply_axopts3d(ax, ${repr(p['axopts'])})
% else:
% for L in p['layers']:
    _ds = _open(${repr(L['container'])})
    _da = _var(_ds, ${repr(L['output'])})
% if L['transform']:
    _da = _registered(_TF, ${repr(L['transform'])}, "transform")(_da)
% endif
% if L['sel'] is not None:
    _da = _da.sel(${repr(L['sel'])}, method=${repr(L['sel_method'])})
% endif
% if L['mark'] == 'heatmap':
    _C = np.asarray(_da.values)
    _x = _coord(_da, ${repr(L['x'])}, 0)
    _y = _coord(_da, ${repr(L['y'])}, 1)
    if _C.shape == (len(_x), len(_y)):
        _C = _C.T                                   # orient to (y, x) for pcolormesh
% if L['triangle']:
    _C = _triangle(_C, ${repr(L['triangle'])}, ${p['triangle_gap']})
    _x = _y = np.arange(_C.shape[0])                # the gap widens the frame
% endif
    _im = ax.pcolormesh(_x, _y, _C, shading="auto", **_mesh_style(${repr(L['style'])}, _C))
% elif L['mark'] == 'scatter':
    _x = _coord(_da, ${repr(L['x'])}, 0)
% if L['color']:
    # Colour is a THIRD QUANTITY per point, not a fan of artists: one cloud shaded by the variable it is not plotted against.
    _im = ax.scatter(_x, np.asarray(_da.values).squeeze(),
                     c=_channel(_ds, _da, ${repr(L['color'])}),
                     cmap=${repr(L['cmap'] or 'viridis')}, **${repr(L['style'])})
% else:
    ax.scatter(_x, np.asarray(_da.values).squeeze(), **${repr(L['style'])})
% endif
% elif L['mark'] == 'bar':
    _x = _coord(_da, ${repr(L['x'])}, 0)
    ax.bar(_x, np.asarray(_da.values).squeeze(), **${repr(L['style'])})
% elif L['mark'] == 'area':
    _x = _coord(_da, ${repr(L['x'])}, 0)
    ax.fill_between(_x, np.asarray(_da.values).squeeze(), **${repr(L['style'])})
% elif L['mark'] == 'band':
    _x = _coord(_da, ${repr(L['x'])}, 0 if _da.shape[0] != 2 else 1)  # swept axis is the non-pair one
    _b = _bounds(_da, _x, ${repr(L['output'])})
    ax.fill_between(_x, _b[0], _b[1], **${repr(L['style'])})
% elif L['mark'] == 'rule':
    # The channel the value is ON decides the orientation: an `x:` rule is vertical.
    _line = ax.axvline if ${repr(bool(L['x']))} else ax.axhline
    _rule_style = dict(${repr(L['style'])})
    _rule_label = _rule_style.pop("label", None)   # label once, else N duplicate legend entries
    for _i, _v in enumerate(np.atleast_1d(np.asarray(_da.values, dtype=float)).ravel()):
        _line(_v, label=(_rule_label if _i == 0 else None), **_rule_style)
% elif L['color']:
    _dim, _labels = _color_dim(_da, ${repr(L['color'])})   # one line per entry, coloured along the map
    _cmap = plt.get_cmap(${repr(L['cmap'] or 'viridis')})
    for _i, _lab in enumerate(_labels):
        _line = _da.isel({_dim: _i})
        ax.plot(_coord(_line, ${repr(L['x'])}, 0), np.asarray(_line.values).squeeze(),
                color=_cmap(_i / max(len(_labels) - 1, 1)), label=_lab, **${repr(L['style'])})
% else:
    _x = _coord(_da, ${repr(L['x'])}, 0)
    ax.plot(_x, np.asarray(_da.values).squeeze(), **${repr(L['style'])})
% endif
% endfor
${colorbar(p)}\
    _apply_axopts(ax, ${repr(p['axopts'])})
% endif
% if p['title']:
    ax.set_title(${repr(p['title'])})
% endif
% for g in p['groups']:
% for _r in g['rules']:
    ax.ax${'h' if g['axis'] == 'y' else 'v'}line(${_r}, **${repr(g['rule_kwargs'])})
% endfor
% for _l in g['labels']:
% if g['axis'] == 'y':
    ax.text(${-g['pad']}, ${_l['at']}, ${repr(_l['text'])},   # x in axes fraction, y in data
            transform=ax.get_yaxis_transform(), **${repr(g['kwargs'])})
% else:
    ax.text(${_l['at']}, ${-g['pad']}, ${repr(_l['text'])},   # x in data, y in axes fraction
            transform=ax.get_xaxis_transform(), **${repr(g['kwargs'])})
% endif
% endfor
% endfor
% for a in p['annotations']:
% if a['layer']:
    _txt = ${repr(a['text'])}.format(       # the number is READ from the run, not typed
        float(np.asarray(_load_layer(${repr(a['layer'])}).values).ravel()[0]))
% else:
    _txt = ${repr(a['text'])}
% endif
% if a['tail']:
    _ty = float(np.asarray(_load_layer(${repr(a['tail']['layer'])}).values).ravel()[0])
    ax.annotate(_txt, xy=(${a['x']}, ${a['y']}), xycoords="axes fraction",
                xytext=(${a['tail']['x']}, _ty), textcoords="data",   # tail ON the computed point
                zorder=10, **${repr(a['kwargs'])},
                arrowprops={"arrowstyle": "-|>", "color": "k", "lw": 0.8,
                            "shrinkA": 2, "shrinkB": 2})
% elif a['arrow']:
    ax.annotate(_txt, xy=(${a['x']}, ${a['y']}), xycoords="axes fraction",
                xytext=(${a['x'] - a['arrow'][0]}, ${a['y'] - a['arrow'][1]}),
                textcoords="axes fraction", zorder=10, **${repr(a['kwargs'])},
                arrowprops={"arrowstyle": "-|>", "color": "k", "lw": 0.8,
                            "shrinkA": 0, "shrinkB": 0})   # above a composite panel's sub-axes
% elif a['layer']:
    ax.text(${a['x']}, ${a['y']}, _txt, transform=ax.transAxes, zorder=10,
            bbox={"facecolor": fig.get_facecolor(), "edgecolor": "none", "pad": 1.0,
                  "alpha": 0.75},   # a statistic printed over its own scatter stays readable
            **${repr(a['kwargs'])})
% else:
    ax.text(${a['x']}, ${a['y']}, _txt, transform=ax.transAxes, zorder=10, **${repr(a['kwargs'])})
% endif
% endfor
</%def>\
<%def name="emit(d, name, what)">\
% for ins in d['insets']:
${emit(ins, '_' + str(ins['key']), 'Sub-axes')}\
% endfor
def ${name}(fig, ax):
    """${what} ${d['key']} — ${d['kind']}."""
${draw(d)}\
% for ins in d['insets']:
    _iax = ax.inset_axes(${repr(ins['bounds'])})   # drawn after the body, over it
    _${ins['key']}(fig, _iax)
% if ins['post_axopts']:
    _INSET_POST.append((_SCALE_AXES.get(${repr(ins['key'])}, _iax), ${repr(ins['post_axopts'])}))   # re-applied after the format pass
% endif
% endfor
    return ax


</%def>\
% for p in panels:
${emit(p, '_panel_' + str(p['key']), 'Panel')}\
% endfor
def main():
% for s in style:
% if not s['path']:
    bsplot.style.use(${repr(s['value'])})
% endif
% endfor
% for s in style:
% if s['path']:
    plt.style.use(${repr(s['value'])})              # study .mplstyle supplies the defaults
% endif
% endfor
% if font_size:
    plt.rcParams.update({_k: ${font_size} for _k in (          # declared font_size WINS over the
        "font.size", "axes.labelsize", "axes.titlesize",       # .mplstyle: it is the per-figure
        "xtick.labelsize", "ytick.labelsize", "legend.fontsize", "figure.titlesize")})
% endif
% if spine_rcparams:
    plt.rcParams.update(${repr(spine_rcparams)})
% endif
    fig, axd = bsplot.figure.subplots(**${repr(subplots_kwargs)})
    try:                                            # tvbo prefers the "compressed" engine (packs
        fig.set_layout_engine("compressed")         # fixed-aspect axes tightly, less whitespace);
    except Exception:                               # fall back to "tight" where compressed can't apply.
        fig.set_layout_engine("tight")

% for p in panels:
% if p['placeholder'] and not p['placeholder_only']:
    try:                                            # data declared but may be absent: fall back to the label
        axd[${repr(p['key'])}] = _panel_${p['key']}(fig, axd[${repr(p['key'])}])
    except Exception as _e:
        print("panel ${p['key']}: placeholder ({}: {})".format(type(_e).__name__, _e))
        _placeholder(axd[${repr(p['key'])}], ${repr(p['placeholder'])})
% else:
    axd[${repr(p['key'])}] = _panel_${p['key']}(fig, axd[${repr(p['key'])}])
% endif
% endfor

% if auto_format:
<% custom_keys = [p['key'] for p in panels if p['drawer']] %>\
% if custom_keys:
    _fixed = [_snapshot_fixed_axes(axd[_k]) for _k in ${repr(custom_keys)}]   # drawer's own fixed ticks
% endif
    _blank = [_ax for _ax in fig.axes if not _ax.axison and not hasattr(_ax, "zaxis")]   # a 2-D slot the panel blanked stays blank
    bsplot.style.format_fig(fig, add_panel_numbers=False, **${repr(format_kwargs)})   # normalise ticks/labels; panel letters below
    for _ax in _blank:
        _ax.set_axis_off()
% if custom_keys:
    for _s in _fixed:                                       # ...restored so the format pass can't overwrite them
        _restore_fixed_axes(_s)
% endif
    for _pax in _PLACEHOLDER_AXES:                          # a placeholder slot has no ticks to normalise
        _bare(_pax)
    for _iax, _iopts in _INSET_POST:                        # an inset's declared frame, same rule as a panel's
        _apply_axopts(_iax, _iopts)
    for _cbar, _dec in _COLORBAR_POST:                      # declared decimals beat the tidy-up's multiplier
        _format_colorbar(_cbar, _dec)
% for p in panels:
% if p['post_axopts']:
    if axd[${repr(p['key'])}] not in _PLACEHOLDER_AXES:   # a slot that fell back to a placeholder stays bare
        _apply_axopts(_SCALE_AXES.get(${repr(p['key'])}, axd[${repr(p['key'])}]), ${repr(p['post_axopts'])})   # declared frame wins over the tidy-up
% endif
% endfor
% endif
% for p in panels:
% if p['kind'] == 'image' or p['axopts'].get('invert_y'):
    _iax = axd[${repr(p['key'])}]            # keep image/matrix top-down (format_fig normalises the y-axis)
    if _iax.get_ylim()[0] < _iax.get_ylim()[1]:
        _iax.invert_yaxis()
% endif
% if p['axopts'].get('invert_x'):
    _iax = axd[${repr(p['key'])}]            # restore declared x-inversion (format_fig normalises the x-axis)
    if _iax.get_xlim()[0] < _iax.get_xlim()[1]:
        _iax.invert_xaxis()
% endif
% endfor
% for _axis, _groups in shared_scales.items():
% for _group in _groups:
    _share_scale(axd, ${repr(_group)}, ${repr(_axis)})
% endfor
% endfor
% if panel_numbers:
% for p in panels:
% if p['letter'] is not None:
    _panel_number(axd[${repr(p['key'])}], ${repr(p['letter'])}, ${repr(p['number_kwargs'])})
% endif
% endfor
% endif
    _distinct_ticks(fig)                                    # an axis whose ticks repeat one number carries no scale
    fig.savefig(${repr(outfile)}, **${repr(savefig_kwargs)})
    print("wrote", ${repr(outfile)})
    return fig


if __name__ == "__main__":
    main()
