#!/usr/bin/env python3
"""${name} — generated by tvbo bsplot figure codegen.

Self-contained: opens the result containers, draws each panel, saves the figure.
Edit freely — it is a normal Python file.
"""
from __future__ import annotations

import functools

import numpy as np
import xarray as xr
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import bsplot
from bsplot import panels as _bpanels
from tvbo.adapters.bsplot import (TRANSFORMS as _TF, CUSTOM_PANELS as _CP,
                                  load_layer as _load_layer, registered as _registered)
from tvbo.data.dataref import match_output as _match_output
% for m in code_modules:
import ${m}  # noqa: F401 — registers this study's custom panels/transforms into _CP / _TF
% endfor


@functools.lru_cache(maxsize=None)
def _open(path):
    """Open a run's result container once per distinct path (xarray)."""
    return xr.open_dataset(path, engine="h5netcdf")


def _var(ds, output):
    """The data-variable a layer's ``output`` names, via the shared ``DataRef`` rule.

    A recorded state variable is stored under its own name, while an observation, an
    analysis result or an estimate carries an ``observation__``/``estimate__`` prefix. A
    figure names the quantity, not the storage convention, so both resolve — through the
    one matcher every other consumer uses, not a copy of it.
    """
    return ds[_match_output(ds.data_vars, output)]


_PLACEHOLDER_AXES = []          # re-bared after the format pass, which re-derives ticks


def _bare(ax):
    """Strip a placeholder slot to a dashed grey outline: it holds the paper's layout
    position but must never read as a drawn-and-empty panel."""
    ax.set_xticks([]); ax.set_yticks([])
    for _s in ax.spines.values():
        _s.set_visible(True); _s.set_color("0.75"); _s.set_linestyle((0, (4, 4)))
        _s.set_linewidth(0.6)


def _wrap(ax, text, pad=0.88):
    """Wrap text to the AXES width — matplotlib's ``wrap=True`` wraps to the figure edge,
    so a long placeholder label would otherwise run across its neighbours."""
    import textwrap

    width_pt = ax.get_window_extent().width / ax.figure.dpi * 72.0 * pad
    n = max(14, int(width_pt / (0.5 * plt.rcParams.get("font.size", 10.0))))
    return "\n".join(textwrap.fill(line, n) for line in str(text).splitlines())


def _placeholder(ax, label):
    """Honest labelled placeholder when a panel's data is missing/degenerate."""
    ax.text(0.5, 0.5, _wrap(ax, label), ha="center", va="center", transform=ax.transAxes,
            color="0.35", style="italic")
    _bare(ax)
    _PLACEHOLDER_AXES.append(ax)


def _triangle(C, which, gap=0):
    """One triangle of a square matrix, the other half NaN, so two layers compose one image.

    The halves are named as drawn: with the matrix convention (row 0 at top, ``invert_y``)
    ``upper`` is the top-right triangle. ``gap`` widens the matrix by that many cells and
    slides the two halves apart along the diagonal, leaving a blank band between them —
    without it the two quantities touch and read as one field.
    """
    if C.ndim != 2 or C.shape[0] != C.shape[1]:
        raise ValueError(f"triangle needs a square matrix, got shape {C.shape}")
    n, g = C.shape[0], int(gap)
    out = np.full((n + g, n + g), np.nan)
    ones = np.ones(C.shape, dtype=bool)
    if which == "upper":
        keep = np.triu(ones, 1)
        out[:n, g:] = np.where(keep, C, np.nan)      # slid right, above the band
    else:
        keep = np.tril(ones, -1)
        out[g:, :n] = np.where(keep, C, np.nan)      # slid down, below the band
    return out


def _color_dim(da, name):
    """The dimension a colour encoding iterates, and the labels for its entries.

    ``color`` may name a dimension (labels are its coordinate values, or indices when it
    has none) or a NON-dimension coordinate defined along one — which is how a panel draws
    one line per region and still labels them by name rather than by atlas number.
    """
    if name in da.dims:
        vals = da.coords[name].values if name in da.coords else np.arange(da.sizes[name])
        return name, [str(v) for v in vals]
    if name not in da.coords:
        raise KeyError(f"colour encoding {name!r} is neither a dim nor a coord "
                       f"(dims {tuple(da.dims)}, coords {tuple(da.coords)}).")
    coord = da.coords[name]
    return str(coord.dims[0]), [str(v) for v in np.asarray(coord.values)]


def _coord(da, name, axis):
    """Coordinate values along a named dim, or an integer index if it has no coord."""
    if name and name in da.coords:
        return np.asarray(da.coords[name].values)
    return np.arange(da.shape[axis])


def _apply_axopts(ax, o):
    """Apply a grammar panel's resolved axis directives (labels, limits, ticks, legend)."""
    for _key, _draw in (("axhline", ax.axhline), ("axvline", ax.axvline)):
        _at = o.get(_key)
        if _at is not None:
            for _v in (_at if isinstance(_at, (list, tuple)) else [_at]):
                _draw(_v, color="0.6", lw=0.7, ls=":", zorder=0)
    if o.get("xlabel") is not None:
        ax.set_xlabel(o["xlabel"])
    if o.get("ylabel") is not None:
        ax.set_ylabel(o["ylabel"])
    if o.get("title"):
        ax.set_title(o["title"])
    if o.get("xscale"):
        ax.set_xscale(o["xscale"])
    if o.get("yscale"):
        ax.set_yscale(o["yscale"])
    if o.get("xlim"):
        ax.set_xlim(*o["xlim"])
    if o.get("ylim"):
        ax.set_ylim(*o["ylim"])
    if o.get("frame") in ("off", False):
        ax.set_frame_on(False)                      # a matrix has no measurable axis
        ax.set_xticks([]); ax.set_yticks([])
    if o.get("aspect"):
        ax.set_aspect(o["aspect"])
    if o.get("box_aspect"):
        ax.set_box_aspect(o["box_aspect"])           # frame shape, independent of the data ranges
    if o.get("invert_x"):
        ax.invert_xaxis()
    if o.get("invert_y"):
        ax.invert_yaxis()
    if o.get("nbins"):
        from matplotlib.ticker import MaxNLocator   # a declared tick budget, not a tidy-up
        ax.xaxis.set_major_locator(MaxNLocator(nbins=o["nbins"], prune=None))
        ax.yaxis.set_major_locator(MaxNLocator(nbins=o["nbins"], prune=None))
    if o.get("xticks") is not None:
        ax.set_xticks(o["xticks"])
    if o.get("yticks") is not None:
        ax.set_yticks(o["yticks"])
    if o.get("hide_xticklabels"):
        ax.set_xticklabels([])
    if o.get("hide_yticklabels"):
        ax.set_yticklabels([])
    if o.get("legend"):
        ax.legend(loc=o["legend"] if isinstance(o["legend"], str) else "best",
                  frameon=False)


def _series3d(ds, da, name, axis):
    """One 1-D channel of a line3d panel: a data_var, a value along a component coord
    (e.g. select ``E`` along a ``var=[E,x,u]`` dim), or the index if the name is a plain dim."""
    if name and name in ds.data_vars:
        return np.asarray(ds[name].values).squeeze()
    for c in getattr(da, "coords", {}):
        vals = np.asarray(da.coords[c].values)
        if vals.dtype.kind in "US" and name in set(vals.tolist()):
            dim = da.coords[c].dims[0] if da.coords[c].dims else c
            return np.asarray(da.sel({dim: name}).values).squeeze()
    return _coord(da, name, axis)


def _apply_axopts3d(ax, o):
    """3-D axis directives for a line3d panel: labels, limits, camera, per-axis inversion,
    and an opaque white box (no default grey panes). Applied after the 2-D-shared labels."""
    if o.get("zlabel") is not None:
        ax.set_zlabel(o["zlabel"])
    if o.get("zlim"):
        ax.set_zlim(*o["zlim"])
    if o.get("elev") is not None or o.get("azim") is not None:
        ax.view_init(elev=o.get("elev", ax.elev), azim=o.get("azim", ax.azim))
    if o.get("invert_z"):
        ax.invert_zaxis()
    if o.get("zoom"):                                 # fill the cell (3-D axes reserve big margins)
        try:
            ax.set_box_aspect(None, zoom=o["zoom"])
        except TypeError:
            pass                                      # older mpl without the zoom kwarg
    for _pa in (ax.xaxis, ax.yaxis, ax.zaxis):        # white box, faint edges
        _pa.pane.set_facecolor("white"); _pa.pane.set_alpha(1.0); _pa.pane.set_edgecolor("0.8")


def _cell_axes(ax):
    """A panel's own axes: the primary, any twin sharing its subplot cell, and every INSET
    a composite drawer opened inside it (recursively, twins of those included).

    A composite panel draws its cells as inset axes, which carry no subplotspec — so
    without walking `child_axes` a grid's deliberate per-cell ticks are invisible to the
    snapshot and the figure-wide format pass silently replaces them."""
    axes = [ax]
    sp = ax.get_subplotspec()
    if sp is not None:
        for a in ax.figure.axes:
            if a is not ax and a.get_subplotspec() is sp:
                axes.append(a)
    for a in list(axes):
        for child in getattr(a, "child_axes", ()) or ():
            if child not in axes:
                axes.extend(_cell_axes(child))
    return axes


def _snapshot_fixed_axes(ax):
    """Record the tick locator/formatter/limits of a custom panel's axes so the figure-wide
    format pass cannot overwrite ticks the drawer set on purpose.

    bsplot's format pass re-derives evenly spaced ticks for every numeric axis, keeping only
    axes whose labels are strings. A custom drawer, though, often sets meaningful *numeric*
    ticks — a raster's [0, n, 2n] cell axis, a 0-1 twin scale — or an intentionally bare axis
    (``set_yticks([])``). Both cases install a ``FixedLocator``; snapshot exactly those so
    ``_restore_fixed_axes`` can put them back verbatim after the format pass, while axes left
    on an automatic locator still get the tidy shared formatting."""
    from matplotlib.ticker import FixedLocator
    snap = []
    for a in _cell_axes(ax):
        xloc, yloc = a.xaxis.get_major_locator(), a.yaxis.get_major_locator()
        snap.append((a, isinstance(xloc, FixedLocator), isinstance(yloc, FixedLocator),
                     a.get_xlim(), a.get_ylim(), xloc, a.xaxis.get_major_formatter(),
                     yloc, a.yaxis.get_major_formatter()))
    return snap


def _restore_fixed_axes(snap):
    """Put back the drawer's own fixed ticks/limits captured by ``_snapshot_fixed_axes``."""
    for a, x_fixed, y_fixed, xlim, ylim, xloc, xfmt, yloc, yfmt in snap:
        if x_fixed:
            a.xaxis.set_major_locator(xloc); a.xaxis.set_major_formatter(xfmt); a.set_xlim(xlim)
        if y_fixed:
            a.yaxis.set_major_locator(yloc); a.yaxis.set_major_formatter(yfmt); a.set_ylim(ylim)


<%def name="draw(p)">\
% if p['placeholder_only']:
    _placeholder(ax, ${repr(p['placeholder'])})
% elif p['kind'] == 'image':
    ax.imshow(plt.imread(${repr(p['path'])}), origin="upper")
    ax.axis("off")
% elif p['kind'] == 'grid':
    ax.axis("off")          # the cells below carry the drawing; this axes is only their frame
% elif p['kind'] in ('custom', 'surface', 'colorbar', 'legend'):
    _registered(_CP, ${repr(p['render'])}, "custom panel")(fig, ax, ${repr(p['ctx'])})
% elif p['kind'] == 'line3d':
    _spec = ax.get_subplotspec(); ax.remove()           # swap the 2-D cell for a 3-D axis
    ax = fig.add_subplot(_spec, projection="3d")
% for L in p['layers']:
    _ds = _open(${repr(L['container'])})
    _da = _var(_ds, ${repr(L['output'])})
% if L['transform']:
    _da = _registered(_TF, ${repr(L['transform'])}, "transform")(_da)
% endif
% if L['sel'] is not None:
    _da = _da.sel(${repr(L['sel'])}, method=${repr(L['sel_method'])})
% endif
    _x = _series3d(_ds, _da, ${repr(L['x'])}, 0)
    _y = _series3d(_ds, _da, ${repr(L['y'])}, 1)
    _z = _series3d(_ds, _da, ${repr(L['z'])}, 2)
% if L['mark'] == 'scatter':
    ax.scatter(_x, _y, _z, **${repr(L['style'])})
% else:
    ax.plot(_x, _y, _z, **${repr(L['style'])})
% endif
% endfor
    _apply_axopts(ax, ${repr(p['axopts'])})
    _apply_axopts3d(ax, ${repr(p['axopts'])})
% else:
% for L in p['layers']:
    _ds = _open(${repr(L['container'])})
    _da = _var(_ds, ${repr(L['output'])})
% if L['transform']:
    _da = _registered(_TF, ${repr(L['transform'])}, "transform")(_da)
% endif
% if L['sel'] is not None:
    _da = _da.sel(${repr(L['sel'])}, method=${repr(L['sel_method'])})
% endif
% if L['mark'] == 'heatmap':
    _C = np.asarray(_da.values)
    _x = _coord(_da, ${repr(L['x'])}, 0)
    _y = _coord(_da, ${repr(L['y'])}, 1)
    if _C.shape == (len(_x), len(_y)):
        _C = _C.T                                   # orient to (y, x) for pcolormesh
% if L['triangle']:
    _C = _triangle(_C, ${repr(L['triangle'])}, ${p['triangle_gap']})
    _x = _y = np.arange(_C.shape[0])                # the gap widens the frame
% endif
    _im = ax.pcolormesh(_x, _y, _C, shading="auto", **${repr(L['style'])})
% elif L['mark'] == 'scatter':
    _x = _coord(_da, ${repr(L['x'])}, 0)
    ax.scatter(_x, np.asarray(_da.values).squeeze(), **${repr(L['style'])})
% elif L['mark'] == 'bar':
    _x = _coord(_da, ${repr(L['x'])}, 0)
    ax.bar(_x, np.asarray(_da.values).squeeze(), **${repr(L['style'])})
% elif L['mark'] == 'area':
    _x = _coord(_da, ${repr(L['x'])}, 0)
    ax.fill_between(_x, np.asarray(_da.values).squeeze(), **${repr(L['style'])})
% elif L['color']:
    _dim, _labels = _color_dim(_da, ${repr(L['color'])})   # one line per entry, coloured along the map
    _cmap = plt.get_cmap(${repr(L['cmap'] or 'viridis')})
    for _i, _lab in enumerate(_labels):
        _line = _da.isel({_dim: _i})
        ax.plot(_coord(_line, ${repr(L['x'])}, 0), np.asarray(_line.values).squeeze(),
                color=_cmap(_i / max(len(_labels) - 1, 1)), label=_lab, **${repr(L['style'])})
% else:
    _x = _coord(_da, ${repr(L['x'])}, 0)
    ax.plot(_x, np.asarray(_da.values).squeeze(), **${repr(L['style'])})
% endif
% endfor
% if p['colorbar']:
    _cb = fig.colorbar(_im, ax=ax, **${repr(p['colorbar_kwargs'])})   # one scale per panel, not per layer
% if p['colorbar_label']:
    _cb.set_label(${repr(p['colorbar_label'])})
% endif
    _cb.outline.set_linewidth(0.5)
% endif
    _apply_axopts(ax, ${repr(p['axopts'])})
% endif
% if p['title']:
    ax.set_title(${repr(p['title'])})
% endif
% for g in p['groups']:
% for _r in g['rules']:
    ax.ax${'h' if g['axis'] == 'y' else 'v'}line(${_r}, **${repr(g['rule_kwargs'])})
% endfor
% for _l in g['labels']:
% if g['axis'] == 'y':
    ax.text(${-g['pad']}, ${_l['at']}, ${repr(_l['text'])},   # x in axes fraction, y in data
            transform=ax.get_yaxis_transform(), **${repr(g['kwargs'])})
% else:
    ax.text(${_l['at']}, ${-g['pad']}, ${repr(_l['text'])},   # x in data, y in axes fraction
            transform=ax.get_xaxis_transform(), **${repr(g['kwargs'])})
% endif
% endfor
% endfor
% for a in p['annotations']:
% if a['layer']:
    _txt = ${repr(a['text'])}.format(       # the number is READ from the run, not typed
        float(np.asarray(_load_layer(${repr(a['layer'])}).values).ravel()[0]))
% else:
    _txt = ${repr(a['text'])}
% endif
% if a['tail']:
    _ty = float(np.asarray(_load_layer(${repr(a['tail']['layer'])}).values).ravel()[0])
    ax.annotate(_txt, xy=(${a['x']}, ${a['y']}), xycoords="axes fraction",
                xytext=(${a['tail']['x']}, _ty), textcoords="data",   # tail ON the computed point
                zorder=10, **${repr(a['kwargs'])},
                arrowprops={"arrowstyle": "-|>", "color": "k", "lw": 0.8,
                            "shrinkA": 2, "shrinkB": 2})
% elif a['arrow']:
    ax.annotate(_txt, xy=(${a['x']}, ${a['y']}), xycoords="axes fraction",
                xytext=(${a['x'] - a['arrow'][0]}, ${a['y'] - a['arrow'][1]}),
                textcoords="axes fraction", zorder=10, **${repr(a['kwargs'])},
                arrowprops={"arrowstyle": "-|>", "color": "k", "lw": 0.8,
                            "shrinkA": 0, "shrinkB": 0})   # above a composite panel's sub-axes
% else:
    ax.text(${a['x']}, ${a['y']}, _txt, transform=ax.transAxes, zorder=10,
            **${repr(a['kwargs'])})
% endif
% endfor
</%def>\
<%def name="emit(d, name, what)">\
% for ins in d['insets']:
${emit(ins, '_' + str(ins['key']), 'Sub-axes')}\
% endfor
def ${name}(fig, ax):
    """${what} ${d['key']} — ${d['kind']}."""
${draw(d)}\
% for ins in d['insets']:
    _${ins['key']}(fig, ax.inset_axes(${repr(ins['bounds'])}))   # drawn after the body, over it
% endfor
    return ax


</%def>\
% for p in panels:
${emit(p, '_panel_' + str(p['key']), 'Panel')}\
% endfor
def main():
% for s in style:
% if not s['path']:
    bsplot.style.use(${repr(s['value'])})
% endif
% endfor
% for s in style:
% if s['path']:
    plt.style.use(${repr(s['value'])})              # study .mplstyle supplies the defaults
% endif
% endfor
% if font_size:
    plt.rcParams.update({_k: ${font_size} for _k in (          # declared font_size WINS over the
        "font.size", "axes.labelsize", "axes.titlesize",       # .mplstyle: it is the per-figure
        "xtick.labelsize", "ytick.labelsize", "legend.fontsize", "figure.titlesize")})
% endif
% if spine_rcparams:
    plt.rcParams.update(${repr(spine_rcparams)})
% endif
    fig, axd = bsplot.figure.subplots(**${repr(subplots_kwargs)})
    try:                                            # tvbo prefers the "compressed" engine (packs
        fig.set_layout_engine("compressed")         # fixed-aspect axes tightly, less whitespace);
    except Exception:                               # fall back to "tight" where compressed can't apply.
        fig.set_layout_engine("tight")

% for p in panels:
% if p['placeholder'] and not p['placeholder_only']:
    try:                                            # data declared but may be absent: fall back to the label
        axd[${repr(p['key'])}] = _panel_${p['key']}(fig, axd[${repr(p['key'])}])
    except Exception as _e:
        print("panel ${p['key']}: placeholder ({}: {})".format(type(_e).__name__, _e))
        _placeholder(axd[${repr(p['key'])}], ${repr(p['placeholder'])})
% else:
    axd[${repr(p['key'])}] = _panel_${p['key']}(fig, axd[${repr(p['key'])}])
% endif
% endfor

% if auto_format:
<% custom_keys = [p['key'] for p in panels if p['drawer']] %>\
% if custom_keys:
    _fixed = [_snapshot_fixed_axes(axd[_k]) for _k in ${repr(custom_keys)}]   # drawer's own fixed ticks
% endif
    bsplot.style.format_fig(fig, add_panel_numbers=False, **${repr(format_kwargs)})   # normalise ticks/labels; panel letters below
% if custom_keys:
    for _s in _fixed:                                       # ...restored so the format pass can't overwrite them
        _restore_fixed_axes(_s)
% endif
    for _pax in _PLACEHOLDER_AXES:                          # a placeholder slot has no ticks to normalise
        _bare(_pax)
% for p in panels:
% if p['post_axopts']:
    if axd[${repr(p['key'])}] not in _PLACEHOLDER_AXES:   # a slot that fell back to a placeholder stays bare
        _apply_axopts(axd[${repr(p['key'])}], ${repr(p['post_axopts'])})   # declared frame wins over the tidy-up
% endif
% endfor
% endif
% for p in panels:
% if p['kind'] == 'image' or p['axopts'].get('invert_y'):
    _iax = axd[${repr(p['key'])}]            # keep image/matrix top-down (format_fig normalises the y-axis)
    if _iax.get_ylim()[0] < _iax.get_ylim()[1]:
        _iax.invert_yaxis()
% endif
% if p['axopts'].get('invert_x'):
    _iax = axd[${repr(p['key'])}]            # restore declared x-inversion (format_fig normalises the x-axis)
    if _iax.get_xlim()[0] < _iax.get_xlim()[1]:
        _iax.invert_xaxis()
% endif
% endfor
% if panel_numbers:
% for p in panels:
% if p['letter'] is not None:
    _bpanels.add_panel_number(axd[${repr(p['key'])}], ${repr(p['letter'])}, **${repr(p['number_kwargs'])})
% endif
% endfor
% endif
    fig.savefig(${repr(outfile)}, **${repr(savefig_kwargs)})
    print("wrote", ${repr(outfile)})
    return fig


if __name__ == "__main__":
    main()
