

# Slot: equation 



URI: [tvbo:Equation](http://www.thevirtualbrain.org/tvb-o/Equation)
Alias: equation

<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [Function](Function.qmd) |  |  no  |
| [DifferentialOperator](DifferentialOperator.qmd) |  |  no  |
| [Monitor](Monitor.qmd) | Observation model for monitoring simulation output with optional processing p... |  no  |
| [DerivedVariable](DerivedVariable.qmd) |  |  no  |
| [StateVariable](StateVariable.qmd) |  |  no  |
| [Stimulus](Stimulus.qmd) |  |  no  |
| [Distribution](Distribution.qmd) |  |  no  |
| [Noise](Noise.qmd) |  |  no  |
| [FittingTarget](FittingTarget.qmd) |  |  no  |
| [Case](Case.qmd) |  |  no  |
| [DownsamplingModel](DownsamplingModel.qmd) |  |  no  |
| [FieldStateVariable](FieldStateVariable.qmd) |  |  no  |
| [DerivedParameter](DerivedParameter.qmd) |  |  no  |
| [Parameter](Parameter.qmd) |  |  no  |
| [ObservationModel](ObservationModel.qmd) |  |  no  |
| [CostFunction](CostFunction.qmd) |  |  no  |






## Properties

* Range: [Equation](Equation.qmd)




## Identifier and Mapping Information






### Schema Source


* from schema: https://w3id.org/tvbo




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:Equation |
| native | tvbo:equation |




## LinkML Source

<details>
```yaml
name: equation
from_schema: https://w3id.org/tvbo
rank: 1000
slot_uri: tvbo:Equation
alias: equation
domain_of:
- Stimulus
- ObservationModel
- StateVariable
- Distribution
- Parameter
- Function
- Case
- DerivedParameter
- DerivedVariable
- Noise
- CostFunction
- FittingTarget
- Monitor
- DifferentialOperator
range: Equation

```
</details>