--- Stamp each page with the phase of the spine it belongs to.
---
--- The phase comes from `_static/phase_map.lua`, generated from the sidebar by `scripts/build_phase_map.py`. A page may override it with `phase:` in its own frontmatter, naming either the number or the key declared in `_static/phases.yml`; `phase: false` suppresses the badge. Icons, colours and names all come from that one rule file, so this filter never decides what a phase looks like.

local map, spine = nil, nil

local function project_root()
  return (quarto and quarto.project and quarto.project.directory) or "."
end

--- The map is generated by scripts/build_phase_map.py during the pre-render and is not committed, so a render that skipped the pre-render has no file to load. That is a missing badge, never a failed build, so the load is guarded and says which step did not run.
local function load_tables()
  if map then return end
  local ok, loaded = pcall(dofile, project_root() .. "/_static/phase_map.lua")
  if not ok then
    quarto.log.warning("phase-badge: no _static/phase_map.lua; run scripts/build_phase_map.py (the pre-render does) to stamp phases")
  end
  map = (ok and loaded) or {}
  spine = {}
  for _, entry in pairs(map) do
    spine[entry.key] = entry
    if entry.number then spine[tostring(entry.number)] = entry end
  end
end

local function page_key()
  local root, file = project_root(), quarto and quarto.doc and quarto.doc.input_file
  if not file then return nil end
  if file:sub(1, #root + 1) == root .. "/" then return file:sub(#root + 2) end
  return file
end

local function escape(text)
  return (text:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"))
end

local function badge(entry, section)
  local numeral = ""
  if entry.number then
    numeral = string.format('<span class="tvbo-phase__n">%d</span>', entry.number)
  end
  local tail = ""
  if section and section ~= entry.name then
    tail = string.format('<span class="tvbo-phase__sep">·</span><span class="tvbo-phase__section">%s</span>',
      escape(section))
  end
  return string.format(
    '<nav class="tvbo-phase tvbo-phase--%s" style="--phase-color:%s" aria-label="Documentation phase">%s' ..
    '<i class="%s" aria-hidden="true"></i><span class="tvbo-phase__name">%s</span>%s</nav>',
    entry.key, entry.color, numeral, entry.icon, escape(entry.name), tail)
end

function Pandoc(doc)
  load_tables()

  local declared = doc.meta.phase
  if declared == false then return doc end

  local key = page_key()
  local entry = key and map[key] or nil
  local section = entry and entry.section or nil

  if declared ~= nil and declared ~= true then
    local wanted = pandoc.utils.stringify(declared)
    local override = spine[wanted]
    if override then
      entry = override
      section = doc.meta["phase-section"] and pandoc.utils.stringify(doc.meta["phase-section"]) or nil
    else
      quarto.log.warning("phase-badge: unknown `phase: " .. wanted .. "` in " .. tostring(key))
    end
  end

  if not entry then
    quarto.log.warning("phase-badge: " .. tostring(key) .. " is in no sidebar PART and declares no `phase:`")
    return doc
  end

  table.insert(doc.blocks, 1, pandoc.RawBlock("html", badge(entry, section)))
  return doc
end
