FROM odoo:19

USER root
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y python3-pip libcairo2-dev libpango1.0-dev poppler-utils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install tvbo and dependencies (ignore system packages to avoid conflicts)
COPY --chown=odoo:odoo . /tmp/tvbo-install
RUN python3 -m pip install --break-system-packages --ignore-installed /tmp/tvbo-install && \
    rm -rf /tmp/tvbo-install

USER odoo
CMD ["odoo"]
