# BOLD (Double Exponential) - hemodynamic forward model

name: BOLD_DoubleExponential
label: BOLD (Double Exponential HRF)
description: >-
    BOLD fMRI observation model using a Double Exponential hemodynamic
    response function.

imaging_modality: BOLD

class_reference:
    name: Bold
    module: tvb.simulator.monitors
    constructor_args:
        - name: hrf_kernel
          value: DoubleExponential
        - name: hrf_length
          value: 20000.0

parameters:
    TR:
        value: 2000.0
        unit: ms

pipeline:
    - name: temporal_average_interim
      output: interim_averaged
      equation:
          rhs: "window_mean(X, stepsize)"
      arguments:
          stepsize:
              value: 1
      apply_on_dimension: time

    - name: hemodynamic_response
      acronym: HRF
      output: hrf_kernel
      time_range:
          lo: 0
          hi: duration
          step: stock_dt
      equation:
          rhs: "A1 * exp(-t / tau_1) + A2 * exp(-t / tau_2)"
          parameters:
              A1:
                  value: 3.87
              tau_1:
                  value: 0.9
                  unit: s
              A2:
                  value: 0.18
              tau_2:
                  value: 9.5
                  unit: s
      arguments:
          duration:
              value: 20
              unit: s
          stock_dt:
              value: 0.004
              unit: s

    - name: convolve
      input: temporal_average_interim
      output: convolved
      callable:
          module: scipy.signal
          name: fftconvolve
      arguments:
          in2:
              value: hrf_kernel
          mode:
              value: same

    - name: subsample_to_period
      input: convolve
      output: Bold
      equation:
          rhs: "subsample(X, stepsize)"
      arguments:
          stepsize:
              description: "TR / dt"
      apply_on_dimension: time
