# -*- coding: utf-8 -*-
"""Low-level Julia execution utilities for running generated Julia code.

This module provides functions for executing Julia code generated by TVBO
templates (DifferentialEquations.jl, BifurcationKit.jl, NetworkDynamics.jl)
and extracting results back into Python/NumPy.

Uses pyjulia (``tvbo.adapters.julia``) for the Python↔Julia bridge,
keeping full Julia objects available for interactive inspection.
"""

from __future__ import annotations

import numpy as np

from tvbo.adapters.julia import eval_with_auto_install, get_julia


def ensure_packages(*packages: str) -> None:
    """Ensure Julia packages are installed, installing if missing.

    Parameters
    ----------
    packages : str
        Package names to ensure are available.
    """
    for pkg in packages:
        eval_with_auto_install(
            f'try using {pkg} catch; import Pkg; Pkg.add("{pkg}"); using {pkg} end'
        )


def run_julia_code(code: str, compiled_modules: bool = True):
    """Execute a block of Julia code in the Main module.

    Parameters
    ----------
    code : str
        Julia source code to evaluate.
    compiled_modules : bool
        Passed to ``get_julia()``. Default True to use precompiled packages.

    Returns
    -------
    object
        The return value of the last Julia expression.
    """
    _jl, _Main = get_julia(compiled_modules=compiled_modules)
    return eval_with_auto_install(code)


def extract_ode_solution() -> tuple[np.ndarray, np.ndarray, object]:
    """Extract time and state arrays from a Julia ODE/SDE solution.

    Assumes a variable ``sol`` exists in Julia Main after running
    a DifferentialEquations.jl / NetworkDynamics.jl solve.

    Returns
    -------
    t : np.ndarray
        Time points, shape ``(n_t,)``.
    u : np.ndarray
        State array, shape ``(n_states, n_t)``.
    sol : object
        The raw Julia solution proxy for interactive use.
    """
    sol = eval_with_auto_install("sol")
    t = np.array(eval_with_auto_install("Array(sol.t)"), dtype=float)
    u = np.array(eval_with_auto_install("Array(sol)"), dtype=float)
    return t, u, sol


def extract_bifurcation_result():
    """Extract a bifurcation result from Julia Main.

    Assumes ``bifurcation_result`` exists after running a
    BifurcationKit.jl script.

    Returns
    -------
    object
        The Julia BifurcationResult proxy.
    """
    return eval_with_auto_install("bifurcation_result")


def solution_to_array(
    t: np.ndarray,
    u: np.ndarray,
    n_sv: int,
    n_nodes: int,
) -> np.ndarray:
    """Reshape a flat DiffEq solution into TVBO 4-D convention.

    Parameters
    ----------
    t : np.ndarray
        Time array, shape ``(n_t,)``.
    u : np.ndarray
        Raw solution, shape ``(n_nodes * n_sv, n_t)``.
    n_sv : int
        Number of state variables per node.
    n_nodes : int
        Number of nodes.

    Returns
    -------
    np.ndarray
        Shape ``(n_t, n_sv, n_nodes, 1)``.
    """
    n_t = len(t)
    data = u.T                                   # (time, n_nodes*n_sv)
    data = data.reshape(n_t, n_nodes, n_sv)      # (time, nodes, sv)
    data = data.transpose(0, 2, 1)               # (time, sv, nodes)
    data = data[:, :, :, np.newaxis]              # (time, sv, nodes, 1)
    return data
