#!/usr/bin/env python
"""Turn the palette TVB-O ships into the custom properties the docs are styled from.

The colours live in `tvbo/plot/palette.yaml` inside the package, where the figures a study renders and the manuscript's own figures already read them from, and where they validate as a `Palette` in the figure spec. The docs read that same file rather than keeping a copy, so a page and a figure beside it cannot disagree about a colour.

The emitted `_static/palette.css` carries the five named roles and the categorical hues as `--palette-*`. `styles.css` maps the docs' own semantic names onto those in one block, and mixes the surface tints and hover states it needs from them, so no page introduces a colour the palette has not approved.
"""

from __future__ import annotations

import argparse
import pathlib

import yaml

from tvbo.plot.palette import PATH as SOURCE

DOCS = pathlib.Path(__file__).parent.parent
OUT = DOCS / "_static" / "palette.css"
UPSTREAM = pathlib.Path("figures/style/palette.yaml")
ROLES = ("ink", "base", "muted", "highlight", "background")


def load(path: pathlib.Path) -> dict:
    spec = yaml.safe_load(path.read_text()) or {}
    missing = [r for r in ROLES if r not in spec] + ([] if spec.get("palette") else ["palette"])
    if missing:
        raise SystemExit(f"{path}: palette is missing {', '.join(missing)}")
    return spec


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manuscript", default=str(pathlib.Path.home() / "projects/TVB-O/tvbo-manuscript"), help="a checkout whose own copy of the palette is reported when it has drifted from the packaged one")
    args = parser.parse_args()

    spec = load(SOURCE)
    lines = ["/* Generated by scripts/build_palette.py from tvbo/plot/palette.yaml. Do not edit. */", ":root {"]
    lines += [f"    --palette-{role}: {spec[role]};" for role in ROLES]
    lines += [f"    --palette-hue-{i}: {hue};" for i, hue in enumerate(spec["palette"], start=1)]
    lines += ["}", ""]
    OUT.write_text("\n".join(lines))
    print(f"[palette] {len(ROLES)} role(s) and {len(spec['palette'])} hue(s) -> {OUT.relative_to(DOCS)}")

    copy = pathlib.Path(args.manuscript).expanduser() / UPSTREAM
    if copy.exists():
        theirs = load(copy)
        drift = [r for r in (*ROLES, "palette") if theirs.get(r) != spec.get(r)]
        if drift:
            print(f"[palette] {copy} has drifted from the packaged palette in: {', '.join(drift)}")
            print(f"[palette] {SOURCE} is the authority; copy it over theirs to bring the manuscript's figures back in line")


if __name__ == "__main__":
    main()
