#!/usr/bin/env python
"""Map every sidebar page to the phase or chapter it sits under.

Reads the spine declared in ``_static/phases.yml`` and the sidebar in ``_toc.yml``, and writes ``_static/phase_map.lua`` — a Lua table the phase-badge filter loads directly, so the filter needs no JSON decoder and no Python at render time.

A page's phase comes from the PART header it sits beneath. The generated ``api/`` and ``datamodel/`` trees live in their own sidebars rather than in ``_toc.yml``, so they are mapped to the REFERENCE chapter by directory instead; every other page outside the curated sidebar carries a ``phase:`` key in its own frontmatter, which the filter prefers over anything written here.

Run as a Quarto pre-render step, after the ``update_toc_*`` generators have spliced their blocks in.
"""

from __future__ import annotations

import pathlib

import yaml

DOCS = pathlib.Path(__file__).parent.parent
OUT = DOCS / "_static" / "phase_map.lua"

# Generated trees carry their own sidebars, so the PART walk never reaches them.
GENERATED = {"api": "API reference", "datamodel": "Data model"}


def spine() -> dict[str, dict]:
    """Every phase and chapter, keyed by the PART header text that introduces it."""
    decl = yaml.safe_load((DOCS / "_static" / "phases.yml").read_text())
    by_part: dict[str, dict] = {}
    for entry in decl["phases"]:
        by_part[entry["part"]] = {**entry, "kind": "phase"}
    for entry in decl["chapters"]:
        by_part[entry["part"]] = {**entry, "number": None, "kind": "chapter"}
    return by_part


def walk(items: list, part: str | None, section: str | None, out: dict) -> str | None:
    """Descend the sidebar, remembering the PART header and the nearest enclosing section."""
    for item in items:
        if not isinstance(item, dict):
            continue
        text, href, kids = item.get("text"), item.get("href"), item.get("contents")
        if text and not href and not kids:
            part = text
            continue
        if href and href.endswith((".qmd", ".md")):
            out.setdefault(href, {"part": part, "section": section})
        if kids:
            walk(kids, part, item.get("section") or text or section, out)
    return part


def main() -> None:
    toc = yaml.safe_load((DOCS / "_toc.yml").read_text())
    pages: dict[str, dict] = {}
    walk(toc["website"]["sidebar"][0]["contents"], None, None, pages)

    by_part = spine()
    reference = next((e for e in by_part.values() if e["key"] == "reference"), None)
    if reference is None:
        raise SystemExit(
            "_static/phases.yml declares no chapter with key `reference`, which is where the generated api/ and datamodel/ trees are mapped."
        )
    for directory, section in GENERATED.items():
        for page in sorted((DOCS / directory).rglob("*.qmd")):
            pages.setdefault(str(page.relative_to(DOCS)), {"part": reference["part"], "section": section})

    rows, unmapped = [], []
    for href, where in sorted(pages.items()):
        entry = by_part.get(where["part"] or "")
        if entry is None:
            unmapped.append(href)
            continue
        section = where["section"] or entry["name"]
        rows.append(
            "  [{h}] = {{number={n}, name={nm}, key={k}, icon={i}, color={c}, section={s}, kind={kd}}},".format(
                h=lua_str(href),
                n=entry["number"] if entry["number"] is not None else "nil",
                nm=lua_str(entry["name"]),
                k=lua_str(entry["key"]),
                i=lua_str(entry["icon"]),
                c=lua_str(entry["color"]),
                s=lua_str(section),
                kd=lua_str(entry["kind"]),
            )
        )

    OUT.write_text("-- Generated by scripts/build_phase_map.py. Do not edit.\nreturn {\n" + "\n".join(rows) + "\n}\n")
    write_css(by_part)
    print(f"[phase-map] {len(rows)} pages mapped -> {OUT.relative_to(DOCS)}")
    if unmapped:
        print(f"[phase-map] {len(unmapped)} sidebar page(s) sit under no PART header:")
        for href in unmapped:
            print(f"    {href}")


def write_css(by_part: dict[str, dict]) -> None:
    """Emit the phase palette as custom properties, so the stylesheet and the landing page read the same colours the badge does."""
    lines = ["/* Generated by scripts/build_phase_map.py from _static/phases.yml. Do not edit. */", ":root {"]
    for entry in by_part.values():
        if entry["kind"] == "phase":
            lines.append(f"    --phase-{entry['number']}: {entry['color']};")
    lines += ["}", ""]
    (DOCS / "_static" / "phases.css").write_text("\n".join(lines))


def lua_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


if __name__ == "__main__":
    main()
