"""Tag documentation pages with the published studies that exercise them.

Walks the hand-authored recipes of a use-case corpus, records which specification slots each study actually writes, and maps those slots onto the page that documents them via `_static/usecase_slots.yml`. Two artifacts come out: `_static/usecase_tags.lua`, which `filters/usecase-tags.lua` reads to append a "Used in" block to the owning page, and `_static/usecase_studies.yml`, the catalogue `Replication/index.qmd` renders.

Nothing here counts a study's experiments or figures. The recipes reach those through `!include`, YAML anchors and nested blocks, so a text scan gets it wrong in both directions, and a wrong number in a catalogue is worse than no number.

The corpus is a separate, currently private repository, so this is a maintainer step and the generated artifact is committed. Run it whenever the corpus gains a study:

    python scripts/build_usecase_tags.py --corpus ~/projects/TVB-O/tvbo-manuscript/use-cases

Slots are detected in the raw text rather than through a YAML parse, because the recipes use `!include` and merge keys that a plain loader rejects, and because a slot that appears only inside an included fragment still counts as used.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

DOCS = Path(__file__).resolve().parent.parent
SKIP_DIRS = {"prov", "derivatives", "sourcedata", "logs", ".tvbo", "__pycache__", "report", "docs"}


def study_recipes(corpus: Path) -> dict[str, list[Path]]:
    """Group hand-authored recipe files by the study directory that owns them."""
    studies: dict[str, list[Path]] = {}
    for path in sorted(corpus.rglob("*.yaml")):
        rel = path.relative_to(corpus)
        if SKIP_DIRS & set(rel.parts):
            continue
        key = rel.parts[-2] if len(rel.parts) > 1 else rel.stem
        studies.setdefault(key, []).append(path)
    return studies


def study_metadata(paths: list[Path]) -> dict[str, str]:
    """Read title, year and DOI off whichever recipe carries them."""
    meta: dict[str, str] = {}
    for path in paths:
        text = path.read_text(encoding="utf-8", errors="replace")
        for field in ("title", "year", "doi"):
            if field in meta:
                continue
            m = re.search(rf'^{field}:\s*"?([^"\n]+?)"?\s*$', text, re.M)
            if m:
                meta[field] = m.group(1).strip()
    return meta


def slots_used(paths: list[Path], slots: dict[str, str], idioms: dict[str, str]) -> set[str]:
    """Every slot key written anywhere in the study, plus every idiom it matches."""
    found: set[str] = set()
    for path in paths:
        text = path.read_text(encoding="utf-8", errors="replace")
        for slot in slots:
            if re.search(rf"^\s*-?\s*{re.escape(slot)}:", text, re.M):
                found.add(slot)
        for pattern in idioms:
            if re.search(pattern, text, re.M):
                found.add(pattern)
    return found


def lua_literal(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--corpus", type=Path, required=True, help="root of the use-case corpus")
    ap.add_argument("--out", type=Path, default=DOCS / "_static" / "usecase_tags.lua")
    ap.add_argument("--catalogue", type=Path, default=DOCS / "_static" / "usecase_studies.yml")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if not args.corpus.is_dir():
        print(f"corpus not found: {args.corpus}", file=sys.stderr)
        return 1

    rules = yaml.safe_load((DOCS / "_static" / "usecase_slots.yml").read_text())
    slots, idioms = rules["slots"], rules["idioms"]
    owner = {**slots, **idioms}

    pages: dict[str, list[dict[str, str]]] = {}
    catalogue: list[dict] = []
    for key, paths in sorted(study_recipes(args.corpus).items()):
        meta = study_metadata(paths)
        if "title" not in meta:
            continue
        entry = {"key": key, "title": meta["title"], "doi": meta.get("doi", ""), "year": meta.get("year", "")}
        touched = sorted({owner[slot] for slot in slots_used(paths, slots, idioms)})
        for page in touched:
            bucket = pages.setdefault(page, [])
            if not any(e["key"] == key for e in bucket):
                bucket.append(entry)
        if meta.get("doi"):
            catalogue.append({**entry, "documents": touched})

    lines = [
        "-- Generated by scripts/build_usecase_tags.py from the use-case corpus. Do not edit.",
        "return {",
    ]
    for page in sorted(pages):
        lines.append(f"  [{lua_literal(page)}] = {{")
        for e in sorted(pages[page], key=lambda x: x["key"]):
            fields = ", ".join(f"{k} = {lua_literal(v)}" for k, v in e.items())
            lines.append(f"    {{{fields}}},")
        lines.append("  },")
    lines.append("}")
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    header = "# Generated by scripts/build_usecase_tags.py from the use-case corpus. Do not edit.\n"
    args.catalogue.write_text(header + yaml.safe_dump({"studies": catalogue}, sort_keys=False), encoding="utf-8")

    if not args.quiet:
        studies = {e["key"] for v in pages.values() for e in v}
        print(f"{len(studies)} studies tagged across {len(pages)} pages -> {args.out.relative_to(DOCS)}")
        print(f"{len(catalogue)} studies catalogued -> {args.catalogue.relative_to(DOCS)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
