# Class: CachedArray 


_One numeric array inside a cached-result ``.h5`` companion, described by name, shape and dtype so a reader can check the layout it expects without opening the file._



<div data-search-exclude markdown="1">



URI: [tvbo:CachedArray](https://w3id.org/tvbo/CachedArray)





```{mermaid}
 classDiagram
    class CachedArray
    click CachedArray href "./CachedArray.html"
      CachedArray : dtype
        
          
    
        
        
        CachedArray --> "0..1" String : dtype
        click String href "../http://www.w3.org/2001/XMLSchema#string.html"
    

        
      CachedArray : name
        
          
    
        
        
        CachedArray --> "1" String : name
        click String href "../http://www.w3.org/2001/XMLSchema#string.html"
    

        
      CachedArray : shape
        
          
    
        
        
        CachedArray --> "*" Integer : shape
        click Integer href "../http://www.w3.org/2001/XMLSchema#integer.html"
    

        
      
```




<!-- no inheritance hierarchy -->

## Class Properties

| Property | Value |
| --- | --- |
| Class URI | [tvbo:CachedArray](https://w3id.org/tvbo/CachedArray) |


## Slots

| Name | Cardinality and Range | Description | Inheritance |
| ---  | --- | --- | --- |
| [name](../slots/name.qmd) | 1 <br/> [xsd:string](http://www.w3.org/2001/XMLSchema#string) | Globally unique identifier for the entity | direct |
| [shape](../slots/shape.qmd) | * <br/> [xsd:integer](http://www.w3.org/2001/XMLSchema#integer) | Array shape, outermost axis first | direct |
| [dtype](../slots/dtype.qmd) | 0..1 <br/> [xsd:string](http://www.w3.org/2001/XMLSchema#string) | NumPy dtype name of the stored array (e | direct |





## Usages

| used by | used in | type | used |
| ---  | --- | --- | --- |
| [ExperimentResultSidecar](../classes/ExperimentResultSidecar.qmd) | [parameters](../slots/parameters.qmd) | range | [CachedArray](../classes/CachedArray.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:CachedArray |
| native | tvbo:CachedArray |






## LinkML Source

<!-- TODO: investigate https://stackoverflow.com/questions/37606292/how-to-create-tabbed-code-blocks-in-mkdocs-or-sphinx -->

### Direct

<details>
```yaml
name: CachedArray
description: One numeric array inside a cached-result ``.h5`` companion, described
  by name, shape and dtype so a reader can check the layout it expects without opening
  the file.
from_schema: https://w3id.org/tvbo
slots:
- name
attributes:
  shape:
    name: shape
    description: Array shape, outermost axis first.
    from_schema: https://w3id.org/tvbo
    domain_of:
    - Matrix
    - CachedArray
    - NamedArray
    - Parameter
    - FreeParameter
    - NDArray
    range: integer
    multivalued: true
  dtype:
    name: dtype
    description: NumPy dtype name of the stored array (e.g. ``float64``).
    from_schema: https://w3id.org/tvbo
    domain_of:
    - Matrix
    - CachedArray
    - NamedArray
    - Edge
    - NDArray
    range: string
class_uri: tvbo:CachedArray

```
</details>

### Induced

<details>
```yaml
name: CachedArray
description: One numeric array inside a cached-result ``.h5`` companion, described
  by name, shape and dtype so a reader can check the layout it expects without opening
  the file.
from_schema: https://w3id.org/tvbo
attributes:
  shape:
    name: shape
    description: Array shape, outermost axis first.
    from_schema: https://w3id.org/tvbo
    owner: CachedArray
    domain_of:
    - Matrix
    - CachedArray
    - NamedArray
    - Parameter
    - FreeParameter
    - NDArray
    range: integer
    multivalued: true
  dtype:
    name: dtype
    description: NumPy dtype name of the stored array (e.g. ``float64``).
    from_schema: https://w3id.org/tvbo
    owner: CachedArray
    domain_of:
    - Matrix
    - CachedArray
    - NamedArray
    - Edge
    - NDArray
    range: string
  name:
    name: name
    description: Globally unique identifier for the entity.
    from_schema: https://w3id.org/tvbo/common
    slot_uri: schema:name
    identifier: true
    owner: CachedArray
    domain_of:
    - BrainAtlas
    - CommonCoordinateSpace
    - ParcellationEntity
    - StudyLayout
    - StudyTemplate
    - StudyDirectory
    - StudyFile
    - DBSProtocol
    - ClinicalScale
    - ClinicalScore
    - SoftwarePackage
    - SoftwareRequirement
    - SoftwareEnvironment
    - Figure
    - Event
    - Tractogram
    - ResultEntity
    - Activity
    - CachedArray
    - MeasureSpec
    - NamedArray
    - GraphGenerator
    - Binding
    - ProcedureStep
    - File
    - StateValue
    - Observation
    - Dynamics
    - StateVariable
    - Distribution
    - Parameter
    - CouplingInput
    - Argument
    - Function
    - FunctionCall
    - Callable
    - DerivedParameter
    - DerivedVariable
    - DataSource
    - OptimizationStage
    - Exploration
    - Inference
    - Prior
    - Likelihood
    - UpdateRule
    - Algorithm
    - Option
    - BranchSwitch
    - Continuation
    - Coupling
    - EnvironmentVariable
    - SchedulerDirective
    - Reducer
    range: string
    required: true
class_uri: tvbo:CachedArray

```
</details></div>