# Class: SpatialField 

<div data-search-exclude markdown="1">



URI: [tvbo:SpatialField](https://w3id.org/tvbo/SpatialField)





```{mermaid}
 classDiagram
    class SpatialField
    click SpatialField href "./SpatialField.html"
      SpatialField : description
        
          
    
        
        
        SpatialField --> "0..1" String : description
        click String href "../http://www.w3.org/2001/XMLSchema#string.html"
    

        
      SpatialField : initial_expression
        
          
    
        
        
        SpatialField --> "0..1" Equation : initial_expression
        click Equation href "./Equation.html"
    

        
      SpatialField : initial_value
        
          
    
        
        
        SpatialField --> "0..1" Float : initial_value
        click Float href "../http://www.w3.org/2001/XMLSchema#float.html"
    

        
      SpatialField : label
        
          
    
        
        
        SpatialField --> "0..1" String : label
        click String href "../http://www.w3.org/2001/XMLSchema#string.html"
    

        
      SpatialField : mesh
        
          
    
        
        
        SpatialField --> "0..1" Mesh : mesh
        click Mesh href "./Mesh.html"
    

        
      SpatialField : quantity_kind
        
          
    
        
        
        SpatialField --> "0..1" String : quantity_kind
        click String href "../http://www.w3.org/2001/XMLSchema#string.html"
    

        
      SpatialField : time_dependent
        
          
    
        
        
        SpatialField --> "0..1" Boolean : time_dependent
        click Boolean href "../http://www.w3.org/2001/XMLSchema#boolean.html"
    

        
      SpatialField : unit
        
          
    
        
        
        SpatialField --> "0..1" String : unit
        click String href "../http://www.w3.org/2001/XMLSchema#string.html"
    

        
      SpatialField : values
        
          
    
        
        
        SpatialField --> "0..1" NDArray : values
        click NDArray href "./NDArray.html"
    

        
      
```




<!-- no inheritance hierarchy -->

## Class Properties

| Property | Value |
| --- | --- |
| Class URI | [tvbo:SpatialField](https://w3id.org/tvbo/SpatialField) |


## Slots

| Name | Cardinality and Range | Description | Inheritance |
| ---  | --- | --- | --- |
| [label](../slots/label.qmd) | 0..1 <br/> [xsd:string](http://www.w3.org/2001/XMLSchema#string) |  | direct |
| [description](../slots/description.qmd) | 0..1 <br/> [xsd:string](http://www.w3.org/2001/XMLSchema#string) |  | direct |
| [quantity_kind](../slots/quantity_kind.qmd) | 0..1 <br/> [xsd:string](http://www.w3.org/2001/XMLSchema#string) | Scalar, vector, or tensor | direct |
| [unit](../slots/unit.qmd) | 0..1 <br/> [xsd:string](http://www.w3.org/2001/XMLSchema#string) |  | direct |
| [mesh](../slots/mesh.qmd) | 0..1 <br/> [Mesh](../classes/Mesh.qmd) |  | direct |
| [values](../slots/values.qmd) | 0..1 <br/> [NDArray](../classes/NDArray.qmd) |  | direct |
| [time_dependent](../slots/time_dependent.qmd) | 0..1 <br/> [xsd:boolean](http://www.w3.org/2001/XMLSchema#boolean) |  | direct |
| [initial_value](../slots/initial_value.qmd) | 0..1 <br/> [xsd:float](http://www.w3.org/2001/XMLSchema#float) | Constant initial value for the field | direct |
| [initial_expression](../slots/initial_expression.qmd) | 0..1 <br/> [Equation](../classes/Equation.qmd) | Analytic initial condition for the field | direct |















## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:SpatialField |
| native | tvbo:SpatialField |






## LinkML Source

<!-- TODO: investigate https://stackoverflow.com/questions/37606292/how-to-create-tabbed-code-blocks-in-mkdocs-or-sphinx -->

### Direct

<details>
```yaml
name: SpatialField
from_schema: https://w3id.org/tvbo
slots:
- label
- description
attributes:
  quantity_kind:
    name: quantity_kind
    description: Scalar, vector, or tensor.
    from_schema: https://w3id.org/tvbo
    rank: 1000
    domain_of:
    - SpatialField
    range: string
  unit:
    name: unit
    from_schema: https://w3id.org/tvbo
    domain_of:
    - CommonCoordinateSpace
    - ToolUnit
    - MeasureSpec
    - NamedArray
    - Edge
    - Observation
    - StateVariable
    - Parameter
    - Argument
    - DerivedParameter
    - DerivedVariable
    - ExplorationAxis
    - Integrator
    - TimeSeries
    - NDArray
    - SpatialField
    range: string
  mesh:
    name: mesh
    from_schema: https://w3id.org/tvbo
    domain_of:
    - Surface
    - Network
    - SpatialField
    - FieldStateVariable
    - PDE
    range: Mesh
  values:
    name: values
    from_schema: https://w3id.org/tvbo
    domain_of:
    - Matrix
    - BrainRegionSeries
    - SpatialField
    range: NDArray
  time_dependent:
    name: time_dependent
    from_schema: https://w3id.org/tvbo
    rank: 1000
    ifabsent: 'False'
    domain_of:
    - SpatialField
    - BoundaryCondition
    range: boolean
  initial_value:
    name: initial_value
    description: Constant initial value for the field. Absent means undeclared; see
      ``StateVariable.initial_value``.
    from_schema: https://w3id.org/tvbo
    domain_of:
    - StateVariable
    - FreeParameter
    - SpatialField
    range: float
  initial_expression:
    name: initial_expression
    description: Analytic initial condition for the field.
    from_schema: https://w3id.org/tvbo
    rank: 1000
    domain_of:
    - SpatialField
    range: Equation
class_uri: tvbo:SpatialField

```
</details>

### Induced

<details>
```yaml
name: SpatialField
from_schema: https://w3id.org/tvbo
attributes:
  quantity_kind:
    name: quantity_kind
    description: Scalar, vector, or tensor.
    from_schema: https://w3id.org/tvbo
    rank: 1000
    owner: SpatialField
    domain_of:
    - SpatialField
    range: string
  unit:
    name: unit
    from_schema: https://w3id.org/tvbo
    owner: SpatialField
    domain_of:
    - CommonCoordinateSpace
    - ToolUnit
    - MeasureSpec
    - NamedArray
    - Edge
    - Observation
    - StateVariable
    - Parameter
    - Argument
    - DerivedParameter
    - DerivedVariable
    - ExplorationAxis
    - Integrator
    - TimeSeries
    - NDArray
    - SpatialField
    range: string
  mesh:
    name: mesh
    from_schema: https://w3id.org/tvbo
    owner: SpatialField
    domain_of:
    - Surface
    - Network
    - SpatialField
    - FieldStateVariable
    - PDE
    range: Mesh
  values:
    name: values
    from_schema: https://w3id.org/tvbo
    owner: SpatialField
    domain_of:
    - Matrix
    - BrainRegionSeries
    - SpatialField
    range: NDArray
  time_dependent:
    name: time_dependent
    from_schema: https://w3id.org/tvbo
    rank: 1000
    ifabsent: 'False'
    owner: SpatialField
    domain_of:
    - SpatialField
    - BoundaryCondition
    range: boolean
  initial_value:
    name: initial_value
    description: Constant initial value for the field. Absent means undeclared; see
      ``StateVariable.initial_value``.
    from_schema: https://w3id.org/tvbo
    owner: SpatialField
    domain_of:
    - StateVariable
    - FreeParameter
    - SpatialField
    range: float
  initial_expression:
    name: initial_expression
    description: Analytic initial condition for the field.
    from_schema: https://w3id.org/tvbo
    rank: 1000
    owner: SpatialField
    domain_of:
    - SpatialField
    range: Equation
  label:
    name: label
    from_schema: https://w3id.org/tvbo
    rank: 1000
    slot_uri: rdfs:label
    owner: SpatialField
    domain_of:
    - ParcellationTerminology
    - Subject
    - Session
    - Dataset
    - Contact
    - SoftwareEnvironment
    - Figure
    - Panel
    - Inset
    - Layer
    - Colorbar
    - Rule
    - Equation
    - Stimulus
    - Event
    - Parcellation
    - Tractogram
    - Matrix
    - Phenotype
    - Network
    - Node
    - Edge
    - Observation
    - Dynamics
    - StateVariable
    - Parameter
    - Function
    - FunctionCall
    - DerivedVariable
    - RandomStream
    - DataSource
    - OptimizationStage
    - Exploration
    - ExplorationAxis
    - FreeParameter
    - Inference
    - AlgorithmStage
    - TuningObjective
    - Continuation
    - Coupling
    - RegionMapping
    - SimulationExperiment
    - SimulationStudy
    - TimeSeries
    - NDArray
    - SpatialDomain
    - Mesh
    - SpatialField
    - FieldStateVariable
    - DifferentialOperator
    - BoundaryCondition
    - PDESolver
    - PDE
    range: string
  description:
    name: description
    from_schema: https://w3id.org/tvbo
    rank: 1000
    slot_uri: dcterms:description
    owner: SpatialField
    domain_of:
    - CommonCoordinateSpace
    - Dataset
    - StudyLayout
    - StudyTemplate
    - StudyDirectory
    - StudyFile
    - ClinicalScore
    - SoftwarePackage
    - SoftwareRequirement
    - SoftwareEnvironment
    - Figure
    - Panel
    - Equation
    - Stimulus
    - Event
    - Tractogram
    - Matrix
    - ResultEntity
    - Activity
    - Phenotype
    - MeasureSpec
    - NamedArray
    - Network
    - GraphGenerator
    - ProcedureStep
    - File
    - Node
    - Edge
    - Observation
    - Dynamics
    - StateVariable
    - Parameter
    - CouplingInput
    - Argument
    - Function
    - FunctionCall
    - Callable
    - DerivedParameter
    - DerivedVariable
    - RandomStream
    - DataSource
    - OptimizationStage
    - Exploration
    - ExplorationAxis
    - FreeParameter
    - Inference
    - Prior
    - Likelihood
    - UpdateRule
    - AlgorithmStage
    - TuningObjective
    - Algorithm
    - BranchSwitch
    - Continuation
    - Integrator
    - Coupling
    - RegionMapping
    - SimulationExperiment
    - Study
    - ResultBinding
    - TimeSeries
    - NDArray
    - SpatialDomain
    - Mesh
    - SpatialField
    - FieldStateVariable
    - BoundaryCondition
    - PDESolver
    - PDE
    - Reducer
    range: string
class_uri: tvbo:SpatialField

```
</details></div>