## Nextflow DSL2 pipeline generated by `tvbo workflow nextflow`.
## Inputs: plan (tvbo.cli._workflow.WorkflowPlan), block (dict), now (str).
<%
axes = plan.workflow_axes
%>\
// ------------------------------------------------------------------
// Generated by tvbo workflow nextflow — ${now}
//   study      : ${plan.study_key}
//   experiment : ${plan.experiment_key}
//   backend    : ${plan.backend.name}
//   workflow wildcards : ${plan.wildcards}
//   vectorized inside backend: ${[ax.name for ax in plan.vectorize_axes]}
// ------------------------------------------------------------------

nextflow.enable.dsl = 2

% if plan.container:
process.container = '${plan.container}'
% endif
% if block.get("executor"):
process.executor  = '${block["executor"]}'
% endif
% if block.get("queue"):
process.queue     = '${block["queue"]}'
% endif

process tvbo_run {
    tag "${plan.experiment_key}"
% for ax in axes:
    publishDir "${plan.out_dir}/${ax.name}=${'${'+ax.name+'}'}", mode: 'copy'
% endfor
    input:
% for ax in axes:
        val ${ax.name}
% endfor
    output:
        path 'result.h5'

    script:
    """
% if script_relpath:
    python ${'${baseDir}/'}${script_relpath} \\
% for ax in axes:
        --override=${ax.parameter}=${'$'+ax.name} \\
% endfor
% for ax in plan.vectorize_axes:
        --sweep=${ax.parameter}=${','.join(repr(v) for v in ax.values)} \\
% endfor
        -o .
% else:
    tvbo run experiment:${plan.experiment_key} \\
        --backend=${plan.backend.name} \\
% for ax in axes:
        --override=${ax.parameter}=${'$'+ax.name} \\
% endfor
% for ax in plan.vectorize_axes:
        --sweep=${ax.parameter}=${','.join(repr(v) for v in ax.values)} \\
% endfor
        -o .
% endif
    """
}

workflow {
% if axes:
%   for ax in axes:
    ${ax.name}_ch = Channel.from(${list(ax.values)})
%   endfor
    tvbo_run(${', '.join(ax.name + '_ch' for ax in axes)})
% else:
    tvbo_run()
% endif
}
