## Snakefile generated by `tvbo workflow snakemake`.
## Inputs: exp_plans (list of dicts, one per experiment), block (dict), now (str).
##   Each exp_plan: {key, rule_name, spec_relpath, backend, out_dir, result_stem,
##                   axes (list of {name, parameter, values}), container}.
<%
def _values(vals):
    return ", ".join(repr(v) for v in vals)

def _run_flags(ep):
    """Per-cell `tvbo run` flags: --subject for the dataset fan-out, --pin for a fanned
    exploration axis. --pin sets the axis's parameter AND drops it from the sweep, so the
    cell is a single point (its base run — and every declared observation — computed there);
    a plain --set of a swept model parameter would neither resolve nor collapse the sweep.
    Shell directives reference wildcards as ``{wildcards.<name>}``."""
    out = []
    for a in ep["axes"]:
        wc = "{wildcards.%s}" % a["name"]
        if a["parameter"] == "dataset.active_subject":
            out.append("--subject=" + wc)
        else:
            out.append("--pin=%s=%s" % (a["parameter"], wc))
    return out

# key -> plan, so a from_experiment dependency can reference the source's output.
_ep_by_key = {ep["key"]: ep for ep in exp_plans}
# Figures render as their own rules (in the included figures.smk) but must be built by
# the default target too, so `tvbo workflow submit` renders them right after the grid.
_figure_outputs = context.get('figure_outputs') or []

import shlex

from tvbo.cli._workflow import (mem_mb as _mem_mb, runtime_minutes as _runtime_min,
                                cell_out_relpath as _cell_out, fan_expand_kwargs as _expand_kwargs,
                                cohort_out_relpaths as _cohort_out)

def _activation(block):
    """Shell lines that put the declared environment in place, in activation order.

    A rule's shell is a fresh non-login shell on the compute node and inherits
    nothing from the environment that emitted the kit, so ``modules``/``venv`` are
    activated per rule ahead of the verbatim ``setup`` lines. The venv path is
    shell-quoted; ``setup`` is passed through as authored.
    """
    lines = ["module load %s" % m for m in (block.get("modules") or [])]
    if block.get("venv"):
        lines.append("source %s/bin/activate" % shlex.quote(str(block["venv"])))
    return lines + list(block.get("setup") or [])

def _rule_resources(block):
    """Intrinsic per-rule resources for the Snakemake job → dict of {key: python-literal}.

    The SLURM executor reads cpus_per_task/mem_mb/runtime plus slurm_partition and
    slurm_account. Partition and account are per-rule because they are declarable per
    experiment (``workflow_overrides.slurm.partition``); the profile carries the
    study-wide default for rules that declare none. options[] passes through verbatim.
    """
    r = {}
    if block.get("cpus_per_task"):
        r["cpus_per_task"] = int(block["cpus_per_task"])
    # `is not None`, not truthiness: a declared 0 is a value the recipe chose, and
    # dropping it silently hands the job the partition default instead.
    mb = _mem_mb(block.get("mem"))
    if mb is not None:
        r["mem_mb"] = mb
    rt = _runtime_min(block.get("time"))
    if rt is not None:
        r["runtime"] = rt
    for _key, _slot in (("partition", "slurm_partition"), ("account", "slurm_account")):
        if block.get(_key):
            r[_slot] = '"%s"' % block[_key]
    if block.get("gres"):
        # A GPU (or any generic) resource goes through the SLURM executor's first-class
        # ``gres`` resource — it builds the ``--gres`` flag itself and rejects the flag if
        # it appears in slurm_extra, so this must not be a passthrough.
        r["gres"] = '"%s"' % block["gres"]
    for opt in (block.get("options") or []):
        v = str(opt["value"])
        # numeric -> bare int; plain string -> "quoted"; anything with a quote -> repr (safely escaped)
        r[opt["name"]] = int(v) if v.lstrip("-").isdigit() else ('"%s"' % v if '"' not in v else repr(v))
    return r
%>\
# ------------------------------------------------------------------
# Snakefile generated by tvbo workflow snakemake — ${now}
#   experiments : ${", ".join(ep["key"] for ep in exp_plans)}
# Each experiment is one rule; experiments with a dataset fan out per subject,
# explorations fan/vectorize per sweep cell, group runs are a single job.
# ------------------------------------------------------------------

% if exp_plans and exp_plans[0].get("container"):
container: "${exp_plans[0]['container']}"
% endif

# Per-experiment fan-out value lists ---------------------------------------
% for ep in exp_plans:
% for ax in ep["axes"]:
${ep["rule_name"].upper()}_${ax["name"].upper()} = [${_values(ax["values"])}]
% endfor
% endfor

OUT_DIR = "${exp_plans[0]['out_dir'] if exp_plans else 'results'}"

rule all:
    input:
% for ep in exp_plans:
<% axes = ep["axes"]; cohort = _cohort_out(ep) %>\
% if cohort:
% for _r in cohort:
        f"{OUT_DIR}/${ep['key']}/${_r}",
% endfor
% elif axes:
        expand(
            f"{OUT_DIR}/${ep['key']}/${_cell_out(ep)}",
% for ax in axes:
            ${ax["name"]}=${ep["rule_name"].upper()}_${ax["name"].upper()}${"," if not loop.last else ""}
% endfor
        ),
% else:
        f"{OUT_DIR}/${ep['key']}/${_cell_out(ep)}",
% endif
% endfor
% for _fig_out in _figure_outputs:
        ${repr(_fig_out)},
% endfor

% for ep in exp_plans:
rule ${ep["rule_name"]}:
% if ep.get("depends_on"):
    # initial_state.from_experiment: the source experiment's result must exist first,
    # so Snakemake orders it before this rule (its operating point seeds this run).
    input:
% for _dep in ep["depends_on"]:
<% _dep_ep = _ep_by_key.get(_dep); _dep_cohort = _cohort_out(_dep_ep) if _dep_ep else [] %>\
% if _dep_cohort:
% for _r in _dep_cohort:
        f"{OUT_DIR}/${_dep}/${_r}",
% endfor
% elif _dep_ep and _dep_ep["axes"]:
        expand(f"{OUT_DIR}/${_dep}/${_cell_out(_dep_ep)}", ${_expand_kwargs(_dep_ep)}),
% elif _dep_ep:
        f"{OUT_DIR}/${_dep}/${_cell_out(_dep_ep)}",
% endif
% endfor
% endif
    output:
<% _cohort = _cohort_out(ep) %>\
% if _cohort:
% for _r in _cohort:
        f"{OUT_DIR}/${ep['key']}/${_r}"${"," if not loop.last else ""}
% endfor
% else:
        f"{OUT_DIR}/${ep['key']}/${_cell_out(ep)}"
% endif
% if ep.get("benchmark"):
    ## Engine-native benchmarking (`--benchmark` / `--set benchmark=true`): Snakemake times
    ## the rule and writes a TSV — wall time (s and h:m:s), max_rss / max_vms / max_uss /
    ## max_pss (MB), io_in/io_out, mean_load, cpu_time — next to the cell's output. One row
    ## per run; a fanned sweep benchmarks every cell (wildcards match the output). The SLURM
    ## executor still wraps the rule's shell, so this measures the job the same way locally.
    benchmark:
        f"{OUT_DIR}/${ep['key']}/${_cell_out(ep)[:-3]}.benchmark.tsv"
% endif
<% _global_container = exp_plans[0].get("container") if exp_plans else None %>\
% if _global_container and not ep.get("container"):
    # This run declares a venv, so it opts out of the study's global container; the image would otherwise shadow the venv under apptainer deployment.
    container:
        None
% elif ep.get("container") and ep["container"] != _global_container:
    # This experiment declares its own image; a rule-level `container:` overrides the global one above (keyed on the first experiment).
    container:
        "${ep['container']}"
% endif
## Each experiment's block already has the study defaults merged into it, so an empty
## one means "this experiment declares no resources" — not "inherit a sibling's". Only
## fall back when the caller supplied no block at all, never when it resolved to {}.
<% _b = ep.get("block", block) %>\
    threads: ${_b.get("cpus_per_task") or _b.get("cores") or 1}
<%
    _res = _rule_resources(_b)
    _escalate = int(ep.get('retries') or 0) > 0
    _is_gpu = bool(_b.get('gres'))
    if _escalate:
        for _k in list(_res):
            if _k == 'runtime' or (_k == 'mem_mb' and not _is_gpu):   # GPU rules shrink the on-device batch instead of raising host mem
                _res[_k] = "lambda wildcards, attempt: %s * attempt" % _res[_k]
        if _is_gpu:   # a RESOURCE, not params: Snakemake injects `attempt` only into resources callables (rules.py expand_resources)
            _res['nvmap_max'] = "lambda wildcards, attempt: 0 if attempt <= 1 else max(1, 8 // (attempt - 1))"
%>\
% if _res:
    # Intrinsic resources; the SLURM executor (via the shipped profile) turns these
    # into --cpus-per-task / --mem / --time on each submitted job.
    resources:
% for _k, _v in _res.items():
        ${_k}=${_v}${"" if loop.last else ","}
% endfor
% endif
% if _escalate:
    retries: ${int(ep['retries'])}
% endif
    shell:
% for _line in _activation(_b):
        ${repr(_line + " && ")}
% endfor
% if ep.get("needs_env_layer"):
        ## Declared requirements were provisioned by setup.sh (run it once first) into a
        ## --system-site-packages venv — native, or on the image when a container is
        ## declared; either way expose it to this rule's `tvbo run` via PYTHONPATH (a plain
        ## shell prepend, substrate-agnostic). The `python*` glob picks the venv's
        ## interpreter version; the `${...}` braces are doubled so Snakemake's `.format()`
        ## leaves them for the shell (single braces are wildcards).
        "export PYTHONPATH=$(echo ${ep['extras_venv']}/lib/python*/site-packages):${'$'}{{PYTHONPATH:-}} && "
% endif
% if context.get("bundled_code"):
        ## Snakemake .format()s the shell string, so the ${PYTHONPATH:-} braces must be
        ## doubled to survive as a literal (single braces are wildcard fields, e.g. {output}).
        "export PYTHONPATH=code:${'$'}{{PYTHONPATH:-}} && "
% endif
% for _e in (_b.get("env") or []):
        "export ${_e['name']}=${_e['value']} && "
% endfor
% if _escalate and _is_gpu:
        ## Retry escalation: cap this attempt's on-device vmap batch (0 = uncapped, attempt 1). {resources.nvmap_max} is a Snakemake field, substituted before the shell runs.
        "if [ {resources.nvmap_max} -gt 0 ]; then export TVBO_NVMAP_MAX={resources.nvmap_max}; fi && "
% endif
% if ep.get("scripts_relpath"):
        ## Pick the code source at run time. TVBO_CODE_SOURCE (or the emit-time default
        ## below) selects `frozen` -> run the pre-rendered `scripts/<key>` as-is with no
        ## codegen; anything else, or a missing script, falls back to re-rendering from
        ## the frozen spec. The `${...}` braces are doubled so Snakemake's `.format()`
        ## leaves the shell parameter expansion intact.
        "CODE_SOURCE=\"${'$'}{{TVBO_CODE_SOURCE:-${ep['code_source']}}}\" && "
        "if [ \"$CODE_SOURCE\" = frozen ] && [ -f ${ep['scripts_relpath']} ]; then RENDERED=\"--rendered ${ep['scripts_relpath']}\"; else RENDERED=\"\"; fi && "
% endif
        "tvbo run ${ep['spec_relpath']} "
% if ep.get("scripts_relpath"):
        "$RENDERED "
% endif
        "--backend=${ep['backend']} "
% if ep.get("select"):
        "--experiment=${ep['select']} "
% endif
% if ep.get("max_iterations") is not None:
        ## Smoke cap (`--set max_iterations=N` / `--set smoke=true` at emit): reach the
        ## post-tuning evaluation quickly to verify a fit runs/streams within memory.
        "--max-iterations ${ep['max_iterations']} "
% endif
% for _flag in _run_flags(ep):
        "${_flag} "
% endfor
% if _cohort_out(ep):
        "-o $(dirname {output[0]})"
% else:
        "-o $(dirname {output})"
% endif

% endfor
