## Snakefile generated by `tvbo workflow snakemake`.
## Inputs: exp_plans (list of dicts, one per experiment), block (dict), now (str).
##   Each exp_plan: {key, rule_name, spec_relpath, backend, out_dir, result_stem,
##                   axes (list of {name, parameter, values}), container}.
<%
def _wildcard(name):
    return "{" + name + "}"

def _values(vals):
    return ", ".join(repr(v) for v in vals)

def _cell_out(ep):
    """Per-cell output basename = exactly the file `tvbo run` writes for this cell."""
    axes = ep["axes"]
    is_subject_only = len(axes) == 1 and axes[0]["parameter"] == "dataset.active_subject"
    if is_subject_only:
        return "sub-" + _wildcard("subject") + "_" + ep["result_stem"] + ".h5"
    if axes:
        return "/".join("%s=%s" % (a["name"], _wildcard(a["name"])) for a in axes) + "/" + ep["result_stem"] + ".h5"
    return ep["result_stem"] + ".h5"

def _run_flags(ep):
    """Per-cell `tvbo run` flags: --subject for the dataset fan-out, --set for others.
    Shell directives reference wildcards as ``{wildcards.<name>}``."""
    out = []
    for a in ep["axes"]:
        wc = "{wildcards.%s}" % a["name"]
        if a["parameter"] == "dataset.active_subject":
            out.append("--subject=" + wc)
        else:
            out.append("--set=%s=%s" % (a["parameter"], wc))
    return out
%>\
# ------------------------------------------------------------------
# Snakefile generated by tvbo workflow snakemake — ${now}
#   experiments : ${", ".join(ep["key"] for ep in exp_plans)}
# Each experiment is one rule; experiments with a dataset fan out per subject,
# explorations fan/vectorize per sweep cell, group runs are a single job.
# ------------------------------------------------------------------

% if exp_plans and exp_plans[0].get("container"):
container: "${exp_plans[0]['container']}"
% endif

# Per-experiment fan-out value lists ---------------------------------------
% for ep in exp_plans:
% for ax in ep["axes"]:
${ep["rule_name"].upper()}_${ax["name"].upper()} = [${_values(ax["values"])}]
% endfor
% endfor

OUT_DIR = "${exp_plans[0]['out_dir'] if exp_plans else 'results'}"

rule all:
    input:
% for ep in exp_plans:
<% axes = ep["axes"] %>\
% if axes:
        expand(
            f"{OUT_DIR}/${ep['key']}/${_cell_out(ep)}",
% for ax in axes:
            ${ax["name"]}=${ep["rule_name"].upper()}_${ax["name"].upper()}${"," if not loop.last else ""}
% endfor
        ),
% else:
        f"{OUT_DIR}/${ep['key']}/${_cell_out(ep)}",
% endif
% endfor

% for ep in exp_plans:
rule ${ep["rule_name"]}:
    output:
        f"{OUT_DIR}/${ep['key']}/${_cell_out(ep)}"
    threads: ${block.get("cores") or 1}
% if block.get("options"):
    resources:
% for _opt in block["options"]:
        ${_opt["name"]}="${_opt["value"]}"${"" if loop.last else ","}
% endfor
% endif
    shell:
% for _line in (block.get("setup") or []):
        ${repr(_line + " && ")}
% endfor
% if context.get("bundled_code"):
        "export PYTHONPATH=code:${'$'}{PYTHONPATH:-} && "
% endif
% for _e in (block.get("env") or []):
        "export ${_e['name']}=${_e['value']} && "
% endfor
        "tvbo run ${ep['spec_relpath']} "
        "--backend=${ep['backend']} "
% if ep.get("select"):
        "--experiment=${ep['select']} "
% endif
% for _flag in _run_flags(ep):
        "${_flag} "
% endfor
        "-o $(dirname {output})"

% endfor
