## Figure render rules generated by tvbo.adapters.figure_workflow.emit_figure_rules.
##
## Structure only — all resolution (used->inputs, workflow_overrides->resources,
## mem/time unit conversion) happens in figure_workflow.py; this template just
## emits the rule skeleton from a clean context (the house codegen rule).
##
## Context:
##   figures      list[dict] — one per Figure, see keys below.
##   now          str        — emit timestamp.
##   include_all  bool       — prepend an aggregate `all_figures` target rule.
##
## Each figure dict: {name, rule_name, inputs (list[str], absolute container paths),
##   output (str), figures_dir (str), script (str), threads (int),
##   resources (dict[str, python-literal-str]), container (str|None),
##   setup (list[str]), env (list[{name, value}])}.
<%
def _q(p):
    """A path/string emitted as a Snakemake (python) string literal."""
    return repr(str(p))
%>\
# Figure render rules for ${", ".join(f["name"] for f in figures)} — generated by tvbo workflow (figures) ${now}
% if include_all:
<%
    in_kit = [f for f in figures if f.get("kit_satisfiable", True)]
    stranded = [f for f in figures if not f.get("kit_satisfiable", True)]
%>\

# Only figures whose every input this kit produces; one reading the author's own tree keeps its rule but leaves this target (see the note below).
rule all_figures:
    input:
% for f in in_kit:
        ${_q(f["output"])}${"," if not loop.last else ""}
% endfor
% if stranded:

# Not in `all_figures` — each of these reads a container this kit does not produce:
% for f in stranded:
#   ${f["rule_name"]}: ${", ".join(str(i["value"]) for i in f["inputs"] if not i["raw"])}
% endfor
# Stage those files at the paths above and run the rule by name.
% endif
% endif

% for f in figures:
rule ${f["rule_name"]}:
% if f["inputs"]:
    # A figure's PROV used-edge is its dep-edge, so the render waits for the results its layers read.
    input:
% for _in in f["inputs"]:
        ${_in["value"] if _in["raw"] else _q(_in["value"])}${"," if not loop.last else ""}
% endfor
% endif
    output:
        ${_q(f["output"])}
% if f.get("container"):
    container:
        ${_q(f["container"])}
% endif
    threads: ${f["threads"]}
% if f.get("resources"):
    # Merged from figure.workflow_overrides over the study-level workflow.
    resources:
% for _k, _v in f["resources"].items():
        ${_k}=${_v}${"" if loop.last else ","}
% endfor
% endif
    shell:
% for _line in (f.get("activation") or []):
        ## Put the declared environment in place first, so plot.py runs in the interpreter its data came from.
        ${repr(_line + " && ")}
% endfor
% if f.get("pythonpath_code"):
        ## Doubled braces survive Snakemake's own wildcard expansion into a literal ${PYTHONPATH:-}.
        "export PYTHONPATH=code:${'$'}{{PYTHONPATH:-}} && "
% endif
% for _e in (f.get("env") or []):
        "export ${_e['name']}=${_e['value']} && "
% endfor
        "mkdir -p ${f['figures_dir']} && "
        "python ${f['script']}"

% endfor
