## Figure render rules generated by tvbo.adapters.figure_workflow.emit_figure_rules.
##
## Structure only — all resolution (used->inputs, workflow_overrides->resources,
## mem/time unit conversion) happens in figure_workflow.py; this template just
## emits the rule skeleton from a clean context (the house codegen rule).
##
## Context:
##   figures      list[dict] — one per Figure, see keys below.
##   now          str        — emit timestamp.
##   include_all  bool       — prepend an aggregate `all_figures` target rule.
##
## Each figure dict: {name, rule_name, inputs (list[str], absolute container paths),
##   output (str), figures_dir (str), script (str), threads (int),
##   resources (dict[str, python-literal-str]), container (str|None),
##   setup (list[str]), env (list[{name, value}])}.
<%
def _q(p):
    """A path/string emitted as a Snakemake (python) string literal."""
    return repr(str(p))
%>\
# ------------------------------------------------------------------
# Figure render rules — generated by tvbo workflow (figures) ${now}
#   figures : ${", ".join(f["name"] for f in figures)}
# A figure's PROV `used` containers ARE its workflow inputs: each render
# rule declares the experiment result containers its layers bind to, so the
# engine schedules it after those experiments' rules (used-edge == dep-edge).
# ------------------------------------------------------------------
% if include_all:

rule all_figures:
    input:
% for f in figures:
        ${_q(f["output"])}${"," if not loop.last else ""}
% endfor
% endif

% for f in figures:
rule ${f["rule_name"]}:
% if f["inputs"]:
    # PROV used -> workflow input: the results this figure's layers read — an expand()
    # over a fanned experiment's whole grid (raw, so Snakemake evaluates it) or a single
    # container path. The used-edge IS the dep-edge, so the render waits for its data.
    input:
% for _in in f["inputs"]:
        ${_in["value"] if _in["raw"] else _q(_in["value"])}${"," if not loop.last else ""}
% endfor
% endif
    output:
        ${_q(f["output"])}
% if f.get("container"):
    container:
        ${_q(f["container"])}
% endif
    threads: ${f["threads"]}
% if f.get("resources"):
    # Merged from figure.workflow_overrides over the study-level workflow; the
    # SLURM executor turns these into --cpus-per-task / --mem / --time / etc.
    resources:
% for _k, _v in f["resources"].items():
        ${_k}=${_v}${"" if loop.last else ","}
% endfor
% endif
    shell:
% for _line in (f.get("activation") or []):
        ## modules / venv / setup — put the declared environment in place first, so plot.py
        ## runs in the same interpreter (bsplot, the study's code_modules) its data came from.
        ${repr(_line + " && ")}
% endfor
% if f.get("pythonpath_code"):
        ## The figure's custom-panel code_modules are bundled into code/; put it on
        ## PYTHONPATH so `import <code_module>` resolves when plot.py runs. Doubled braces
        ## survive Snakemake's own {…} wildcard expansion into a literal ${PYTHONPATH:-}.
        "export PYTHONPATH=code:${'$'}{{PYTHONPATH:-}} && "
% endif
% for _e in (f.get("env") or []):
        "export ${_e['name']}=${_e['value']} && "
% endfor
        "mkdir -p ${f['figures_dir']} && "
        "python ${f['script']}"

% endfor
