## -*- coding: utf-8 -*-
<%doc>
TVBO → NeuroML v2 Document Template
=====================================
Generates a valid NeuroML v2 document (<neuroml> root) with custom
ComponentType definitions for any TVBO Dynamics model.

Unlike the LEMS template (tvbo-neuroml-lems.xml.mako), this template:
  - Uses <neuroml> root with XML namespace declarations
  - Does NOT include inline Dimension/Unit definitions
  - Does NOT include Simulation infrastructure types
  - Does NOT include a <Simulation> block
  - IS suitable for sharing and import by NeuroML ecosystem tools

All dynamics models are exported as custom LEMS ComponentTypes —
no mapping to native NeuroML cell types (iafCell, fitzHughNagumoCell,
etc.) is attempted.  This keeps the output generic and independent.

To run this file, pair it with a LEMS simulation wrapper:
  <Lems>
    <Include file="Cells.xml"/>
    <Include file="Networks.xml"/>
    <Include file="Simulation.xml"/>
    <Include file="this_file.nml"/>
    <Simulation ... target="net"/>
  </Lems>

Generate the wrapper via NeuroMLAdapter.render_lems_wrapper().

All template variables are pre-computed by NeuroMLAdapter._ctx()
via tvbo.adapters.neuroml.build_lems_context().
</%doc>
<?xml version="1.0" encoding="UTF-8"?>

<neuroml xmlns="http://www.neuroml.org/schema/neuroml2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.neuroml.org/schema/neuroml2 https://raw.githubusercontent.com/NeuroML/NeuroML2/master/Schemas/NeuroML2/NeuroML_v2.3.1.xsd"
    id="${dyn_id}">

  <!-- Generated by TVBO (The Virtual Brain Ontology)
       Dynamics model: ${dyn.name or '(unnamed)'} -->

  <!-- ════════════════════════════════════════════════════════════════
       Dynamics ComponentType & Component instances
       ════════════════════════════════════════════════════════════════ -->
<%include file="_lems_componenttype.xml.mako"/>

  <!-- ════════════════════════════════════════════════════════════════
       Network: ${n_nodes} node(s), population of ${dyn_id}
       ════════════════════════════════════════════════════════════════ -->
  <network id="net">
    <population id="pop0" component="${dyn_id}_inst" size="${n_nodes}"/>
  </network>

</neuroml>
