# Slot: alternative_identifier 


_Further identifiers for the same package, an RRID among them (BEP028 ``AlternativeIdentifier``)._



<div data-search-exclude markdown="1">



URI: [tvbo_sw:slot/alternative_identifier](https://w3id.org/tvbo/software/slot/alternative_identifier)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [SoftwarePackage](../classes/SoftwarePackage.qmd) | Identity and metadata for a software package, aligned with schema |  no  |
| [SimulationTool](../classes/SimulationTool.qmd) | A software tool for computational neuroscience simulation, analysis, or model... |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:anyURI](http://www.w3.org/2001/XMLSchema#anyURI) |
| Domain Of | [SoftwarePackage](../classes/SoftwarePackage.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
| Multivalued | Yes |
### Slot Characteristics

| Property | Value |
| --- | --- |
| Owner | [SoftwarePackage](../classes/SoftwarePackage.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo/software




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo_sw:alternative_identifier |
| native | tvbo_sw:alternative_identifier |




## LinkML Source

<details>
```yaml
name: alternative_identifier
description: Further identifiers for the same package, an RRID among them (BEP028
  ``AlternativeIdentifier``).
from_schema: https://w3id.org/tvbo/software
rank: 1000
owner: SoftwarePackage
domain_of:
- SoftwarePackage
range: uriorcurie
multivalued: true

```
</details></div>