# Slot: call_args 


_Arguments passed when calling the instance (__call__). Usually the input data from simulation result. Example: result (simulation output array)._



<div data-search-exclude markdown="1">



URI: [tvbo:slot/call_args](https://w3id.org/tvbo/slot/call_args)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [ClassReference](../classes/ClassReference.qmd) | Reference to a class that can be instantiated and called |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [Argument](../classes/Argument.qmd) |
| Domain Of | [ClassReference](../classes/ClassReference.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
| Multivalued | Yes |
### Slot Characteristics

| Property | Value |
| --- | --- |
| Owner | [ClassReference](../classes/ClassReference.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:call_args |
| native | tvbo:call_args |




## LinkML Source

<details>
```yaml
name: call_args
description: 'Arguments passed when calling the instance (__call__). Usually the input
  data from simulation result. Example: result (simulation output array).'
from_schema: https://w3id.org/tvbo
rank: 1000
owner: ClassReference
domain_of:
- ClassReference
range: Argument
multivalued: true
inlined: true
inlined_as_list: true

```
</details></div>