# Slot: clinical_improvement 


_Observed improvement relative to baseline based on a defined score._



<div data-search-exclude markdown="1">



URI: [tvbo_dbs:slot/clinical_improvement](https://w3id.org/tvbo/dbs/slot/clinical_improvement)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [DBSProtocol](../classes/DBSProtocol.qmd) | A protocol describing DBS therapy, potentially bilateral or multi-lead |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [ClinicalImprovement](../classes/ClinicalImprovement.qmd) |
| Domain Of | [DBSProtocol](../classes/DBSProtocol.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
| Multivalued | Yes |
### Slot Characteristics

| Property | Value |
| --- | --- |
| Owner | [DBSProtocol](../classes/DBSProtocol.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo/dbs




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo_dbs:clinical_improvement |
| native | tvbo_dbs:clinical_improvement |




## LinkML Source

<details>
```yaml
name: clinical_improvement
description: Observed improvement relative to baseline based on a defined score.
from_schema: https://w3id.org/tvbo/dbs
rank: 1000
owner: DBSProtocol
domain_of:
- DBSProtocol
range: ClinicalImprovement
multivalued: true

```
</details></div>