# Slot: condition_states 


_State variable symbols accessible in the condition function. For edges, can include source/destination vertex outputs._



<div data-search-exclude markdown="1">



URI: [tvbo:slot/condition_states](https://w3id.org/tvbo/slot/condition_states)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [Event](../classes/Event.qmd) | A discrete or continuous event that modifies the system during simulation |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:string](http://www.w3.org/2001/XMLSchema#string) |
| Domain Of | [Event](../classes/Event.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
| Multivalued | Yes |
### Slot Characteristics

| Property | Value |
| --- | --- |
| Owner | [Event](../classes/Event.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:condition_states |
| native | tvbo:condition_states |




## LinkML Source

<details>
```yaml
name: condition_states
description: State variable symbols accessible in the condition function. For edges,
  can include source/destination vertex outputs.
from_schema: https://w3id.org/tvbo
rank: 1000
owner: Event
domain_of:
- Event
range: string
multivalued: true

```
</details></div>