# Slot: coupling_variable 


_Whether this state variable is transmitted to connected nodes through the coupling function. In TVB terms, this determines the cvar indices (state variables extracted from history and fed into the coupling function). The coupling function may override this via its incoming_states attribute._



<div data-search-exclude markdown="1">



URI: [tvbo:slot/coupling_variable](https://w3id.org/tvbo/slot/coupling_variable)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [StateVariable](../classes/StateVariable.qmd) |  |  no  |
| [FieldStateVariable](../classes/FieldStateVariable.qmd) |  |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:boolean](http://www.w3.org/2001/XMLSchema#boolean) |
| Domain Of | [StateVariable](../classes/StateVariable.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
### Slot Characteristics

| Property | Value |
| --- | --- |
| If Absent | `False` |
| Owner | [StateVariable](../classes/StateVariable.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:coupling_variable |
| native | tvbo:coupling_variable |




## LinkML Source

<details>
```yaml
name: coupling_variable
description: Whether this state variable is transmitted to connected nodes through
  the coupling function. In TVB terms, this determines the cvar indices (state variables
  extracted from history and fed into the coupling function). The coupling function
  may override this via its incoming_states attribute.
from_schema: https://w3id.org/tvbo
rank: 1000
ifabsent: 'False'
owner: StateVariable
domain_of:
- StateVariable
range: boolean

```
</details></div>