# Slot: derived_observations 


_Observations derived from combining other observations. Computed after all regular observations are available. Examples: fc_corr (from fc, fc_target), rmse, etc._



<div data-search-exclude markdown="1">



URI: [tvbo:slot/derived_observations](https://w3id.org/tvbo/slot/derived_observations)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [SimulationExperiment](../classes/SimulationExperiment.qmd) |  |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [DerivedObservation](../classes/DerivedObservation.qmd) |
| Domain Of | [SimulationExperiment](../classes/SimulationExperiment.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
| Multivalued | Yes |
### Slot Characteristics

| Property | Value |
| --- | --- |
| Owner | [SimulationExperiment](../classes/SimulationExperiment.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:derived_observations |
| native | tvbo:derived_observations |




## LinkML Source

<details>
```yaml
name: derived_observations
description: 'Observations derived from combining other observations. Computed after
  all regular observations are available. Examples: fc_corr (from fc, fc_target),
  rmse, etc.'
from_schema: https://w3id.org/tvbo
rank: 1000
owner: SimulationExperiment
domain_of:
- SimulationExperiment
range: DerivedObservation
multivalued: true
inlined: true

```
</details></div>