# Slot: derivative_initial_value 


_Initial value for the first time derivative, used when equation_order > 1. For a second-order ODE d²x/dt² = f, this sets dx/dt(0). Required by ModelingToolkit.jl to fully specify higher-order initial value problems._



<div data-search-exclude markdown="1">



URI: [tvbo:slot/derivative_initial_value](https://w3id.org/tvbo/slot/derivative_initial_value)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [StateVariable](../classes/StateVariable.qmd) |  |  no  |
| [FieldStateVariable](../classes/FieldStateVariable.qmd) |  |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:float](http://www.w3.org/2001/XMLSchema#float) |
| Domain Of | [StateVariable](../classes/StateVariable.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
### Slot Characteristics

| Property | Value |
| --- | --- |
| Owner | [StateVariable](../classes/StateVariable.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:derivative_initial_value |
| native | tvbo:derivative_initial_value |




## LinkML Source

<details>
```yaml
name: derivative_initial_value
description: Initial value for the first time derivative, used when equation_order
  > 1. For a second-order ODE d²x/dt² = f, this sets dx/dt(0). Required by ModelingToolkit.jl
  to fully specify higher-order initial value problems.
from_schema: https://w3id.org/tvbo
rank: 1000
owner: StateVariable
domain_of:
- StateVariable
range: float

```
</details></div>