# Slot: detect_bifurcation 


_Bifurcation detection level. 0 = off, 1 = eigenvalues only, 2 = detect, 3 = locate precisely._



<div data-search-exclude markdown="1">



URI: [tvbo:slot/detect_bifurcation](https://w3id.org/tvbo/slot/detect_bifurcation)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [Continuation](../classes/Continuation.qmd) | Complete specification of a numerical continuation / bifurcation analysis |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:integer](http://www.w3.org/2001/XMLSchema#integer) |
| Domain Of | [Continuation](../classes/Continuation.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
### Slot Characteristics

| Property | Value |
| --- | --- |
| Owner | [Continuation](../classes/Continuation.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:detect_bifurcation |
| native | tvbo:detect_bifurcation |




## LinkML Source

<details>
```yaml
name: detect_bifurcation
description: Bifurcation detection level. 0 = off, 1 = eigenvalues only, 2 = detect,
  3 = locate precisely.
from_schema: https://w3id.org/tvbo
rank: 1000
owner: Continuation
domain_of:
- Continuation
range: integer

```
</details></div>