# Slot: device_scale_factor 


_Device pixel ratio; 2-3 renders a crisp raster at print resolution (the browser analogue of dpi)._



<div data-search-exclude markdown="1">



URI: [tvbo:slot/device_scale_factor](https://w3id.org/tvbo/slot/device_scale_factor)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [RenderSpec](../classes/RenderSpec.qmd) | A headless-browser capture recipe turning an `image` panel's HTML/URL `source... |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:float](http://www.w3.org/2001/XMLSchema#float) |
| Domain Of | [RenderSpec](../classes/RenderSpec.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
### Slot Characteristics

| Property | Value |
| --- | --- |
| Owner | [RenderSpec](../classes/RenderSpec.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo/figure




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:device_scale_factor |
| native | tvbo:device_scale_factor |




## LinkML Source

<details>
```yaml
name: device_scale_factor
description: Device pixel ratio; 2-3 renders a crisp raster at print resolution (the
  browser analogue of dpi).
from_schema: https://w3id.org/tvbo/figure
rank: 1000
owner: RenderSpec
domain_of:
- RenderSpec
range: float

```
</details></div>