# Slot: doi 

<div data-search-exclude markdown="1">



URI: [tvbo:slot/doi](https://w3id.org/tvbo/slot/doi)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [SoftwarePackage](../classes/SoftwarePackage.qmd) | Identity and metadata for a software package, aligned with schema |  no  |
| [SimulationTool](../classes/SimulationTool.qmd) | A software tool for computational neuroscience simulation, analysis, or model... |  no  |
| [Study](../classes/Study.qmd) | Bibliographic anchor for a source publication, identified by its citation key... |  no  |
| [SimulationStudy](../classes/SimulationStudy.qmd) |  |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:string](http://www.w3.org/2001/XMLSchema#string) |
| Domain Of | [SoftwarePackage](../classes/SoftwarePackage.qmd), [Study](../classes/Study.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |










## Identifier and Mapping Information






## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:doi |
| native | tvbo:doi |




## LinkML Source

<details>
```yaml
name: doi
domain_of:
- SoftwarePackage
- Study
range: string

```
</details></div>