# Slot: dynamics 

<div data-search-exclude markdown="1">



URI: [tvbo:slot/dynamics](https://w3id.org/tvbo/slot/dynamics)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [Network](../classes/Network.qmd) | Network specification with nodes, edges, and reusable coupling configurations |  no  |
| [Node](../classes/Node.qmd) | A node in a network with its own dynamics and properties |  no  |
| [Edge](../classes/Edge.qmd) | An edge in a network |  no  |
| [Observation](../classes/Observation.qmd) | Unified class for all observation/measurement specifications |  no  |
| [Continuation](../classes/Continuation.qmd) | Complete specification of a numerical continuation / bifurcation analysis |  no  |
| [SimulationExperiment](../classes/SimulationExperiment.qmd) |  |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:string](http://www.w3.org/2001/XMLSchema#string) |
| Domain Of | [Network](../classes/Network.qmd), [Node](../classes/Node.qmd), [Edge](../classes/Edge.qmd), [Observation](../classes/Observation.qmd), [Continuation](../classes/Continuation.qmd), [SimulationExperiment](../classes/SimulationExperiment.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |










## Identifier and Mapping Information






## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:dynamics |
| native | tvbo:dynamics |




## LinkML Source

<details>
```yaml
name: dynamics
domain_of:
- Network
- Node
- Edge
- Observation
- Continuation
- SimulationExperiment
range: string

```
</details></div>