# Slot: freeze_parameters 


_Parameters from previous stages to freeze (keep at optimized value but not update)_



<div data-search-exclude markdown="1">



URI: [tvbo:slot/freeze_parameters](https://w3id.org/tvbo/slot/freeze_parameters)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [OptimizationStage](../classes/OptimizationStage.qmd) | A single stage in a multi-stage optimization workflow |  no  |
| [Optimization](../classes/Optimization.qmd) | Configuration for parameter optimization |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [Parameter](../classes/Parameter.qmd) |
| Domain Of | [OptimizationStage](../classes/OptimizationStage.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
| Multivalued | Yes |
### Slot Characteristics

| Property | Value |
| --- | --- |
| Owner | [OptimizationStage](../classes/OptimizationStage.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:freeze_parameters |
| native | tvbo:freeze_parameters |




## LinkML Source

<details>
```yaml
name: freeze_parameters
description: Parameters from previous stages to freeze (keep at optimized value but
  not update)
from_schema: https://w3id.org/tvbo
rank: 1000
owner: OptimizationStage
domain_of:
- OptimizationStage
range: Parameter
multivalued: true
inlined: false

```
</details></div>