# Slot: method 

<div data-search-exclude markdown="1">



URI: [tvbo:slot/method](https://w3id.org/tvbo/slot/method)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [Discretization](../classes/Discretization.qmd) | Discretization method for boundary value problems in continuation (periodic o... |  no  |
| [InitialState](../classes/InitialState.qmd) | How to obtain the starting equilibrium or periodic orbit for continuation |  no  |
| [Solver](../classes/Solver.qmd) | Lightweight specification of a numerical ODE solver / integrator |  no  |
| [Integrator](../classes/Integrator.qmd) | Fixed-step or adaptive ODE integrator with TVB-specific extensions (noise, tr... |  no  |
| [PDESolver](../classes/PDESolver.qmd) | Numerical solver for a PDE: the time-integration algorithm, tolerances and st... |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:string](http://www.w3.org/2001/XMLSchema#string) |
| Domain Of | [Discretization](../classes/Discretization.qmd), [InitialState](../classes/InitialState.qmd), [Solver](../classes/Solver.qmd), [Integrator](../classes/Integrator.qmd), [PDESolver](../classes/PDESolver.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |










## Identifier and Mapping Information






## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:method |
| native | tvbo:method |




## LinkML Source

<details>
```yaml
name: method
domain_of:
- Discretization
- InitialState
- Solver
- Integrator
- PDESolver
range: string

```
</details></div>