# Slot: package 


_Reference to the software package identity._



<div data-search-exclude markdown="1">



URI: [tvbo_sw:slot/package](https://w3id.org/tvbo/software/slot/package)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [SoftwareRequirement](../classes/SoftwareRequirement.qmd) | An individual software requirement binding a package to a version constraint ... |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [SoftwarePackage](../classes/SoftwarePackage.qmd) |
| Domain Of | [SoftwareRequirement](../classes/SoftwareRequirement.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
### Slot Characteristics

| Property | Value |
| --- | --- |
| Owner | [SoftwareRequirement](../classes/SoftwareRequirement.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo/software




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo_sw:package |
| native | tvbo_sw:package |




## LinkML Source

<details>
```yaml
name: package
description: Reference to the software package identity.
from_schema: https://w3id.org/tvbo/software
rank: 1000
owner: SoftwareRequirement
domain_of:
- SoftwareRequirement
range: SoftwarePackage

```
</details></div>