# Slot: percent_change 


_Percent change compared to preoperative baseline (positive = improvement)_



<div data-search-exclude markdown="1">



URI: [tvbo_dbs:slot/percent_change](https://w3id.org/tvbo/dbs/slot/percent_change)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [ClinicalImprovement](../classes/ClinicalImprovement.qmd) | Relative improvement on a defined clinical score |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:float](http://www.w3.org/2001/XMLSchema#float) |
| Domain Of | [ClinicalImprovement](../classes/ClinicalImprovement.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
### Slot Characteristics

| Property | Value |
| --- | --- |
| Owner | [ClinicalImprovement](../classes/ClinicalImprovement.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo/dbs




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo_dbs:percent_change |
| native | tvbo_dbs:percent_change |




## LinkML Source

<details>
```yaml
name: percent_change
description: Percent change compared to preoperative baseline (positive = improvement)
from_schema: https://w3id.org/tvbo/dbs
rank: 1000
owner: ClinicalImprovement
domain_of:
- ClinicalImprovement
range: float

```
</details></div>