# Slot: references 

<div data-search-exclude markdown="1">



URI: [dcterms:references](http://purl.org/dc/terms/references)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [Provenance](../classes/Provenance.qmd) | W3C PROV-O aligned provenance ABOUT the artifact that carries it — reusable o... |  no  |
| [Observation](../classes/Observation.qmd) | Unified class for all observation/measurement specifications |  no  |
| [Dynamics](../classes/Dynamics.qmd) |  |  no  |
| [SimulationExperiment](../classes/SimulationExperiment.qmd) |  |  no  |
| [SimulationStudy](../classes/SimulationStudy.qmd) |  |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:string](http://www.w3.org/2001/XMLSchema#string) |
| Domain Of | [Provenance](../classes/Provenance.qmd), [Observation](../classes/Observation.qmd), [Dynamics](../classes/Dynamics.qmd), [SimulationExperiment](../classes/SimulationExperiment.qmd), [SimulationStudy](../classes/SimulationStudy.qmd) |
| Slot URI | [dcterms:references](http://purl.org/dc/terms/references) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
| Multivalued | Yes |










## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | dcterms:references |
| native | tvbo:references |




## LinkML Source

<details>
```yaml
name: references
from_schema: https://w3id.org/tvbo
rank: 1000
slot_uri: dcterms:references
domain_of:
- Provenance
- Observation
- Dynamics
- SimulationExperiment
- SimulationStudy
range: string
multivalued: true

```
</details></div>