# Slot: runtime_platform 


_Execution backends or platforms (e.g., MPI, OpenMP, CUDA, JAX)._



<div data-search-exclude markdown="1">



URI: [schema:runtimePlatform](http://schema.org/runtimePlatform)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [SimulationTool](../classes/SimulationTool.qmd) | A software tool for computational neuroscience simulation, analysis, or model... |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:string](http://www.w3.org/2001/XMLSchema#string) |
| Domain Of | [SimulationTool](../classes/SimulationTool.qmd) |
| Slot URI | [schema:runtimePlatform](http://schema.org/runtimePlatform) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |
| Multivalued | Yes |
### Slot Characteristics

| Property | Value |
| --- | --- |
| Owner | [SimulationTool](../classes/SimulationTool.qmd) |












## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo/software




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | schema:runtimePlatform |
| native | tvbo_sw:runtime_platform |




## LinkML Source

<details>
```yaml
name: runtime_platform
description: Execution backends or platforms (e.g., MPI, OpenMP, CUDA, JAX).
from_schema: https://w3id.org/tvbo/software
rank: 1000
slot_uri: schema:runtimePlatform
owner: SimulationTool
domain_of:
- SimulationTool
range: string
multivalued: true

```
</details></div>