# Slot: symbol 

<div data-search-exclude markdown="1">



URI: [tvbo:slot/symbol](https://w3id.org/tvbo/slot/symbol)
<!-- no inheritance hierarchy -->





## Applicable Classes

| Name | Description | Modifies Slot |
| --- | --- | --- |
| [StateVariable](../classes/StateVariable.qmd) |  |  no  |
| [Parameter](../classes/Parameter.qmd) |  |  no  |
| [CouplingInput](../classes/CouplingInput.qmd) | Specification of a coupling input channel for multi-coupling dynamics |  no  |
| [DerivedParameter](../classes/DerivedParameter.qmd) |  |  no  |
| [DerivedVariable](../classes/DerivedVariable.qmd) |  |  no  |
| [ToolUnit](../classes/ToolUnit.qmd) | One TVBO unit as a single tool writes it |  no  |
| [FieldStateVariable](../classes/FieldStateVariable.qmd) |  |  no  |






## Properties

### Type and Range

| Property | Value |
| --- | --- |
| Range | [xsd:string](http://www.w3.org/2001/XMLSchema#string) |
| Domain Of | [ToolUnit](../classes/ToolUnit.qmd), [StateVariable](../classes/StateVariable.qmd), [Parameter](../classes/Parameter.qmd), [CouplingInput](../classes/CouplingInput.qmd), [DerivedParameter](../classes/DerivedParameter.qmd), [DerivedVariable](../classes/DerivedVariable.qmd) |

### Cardinality and Requirements

| Property | Value |
| --- | --- |










## Identifier and Mapping Information





### Schema Source


* from schema: https://w3id.org/tvbo




## Mappings

| Mapping Type | Mapped Value |
| ---  | ---  |
| self | tvbo:symbol |
| native | tvbo:symbol |




## LinkML Source

<details>
```yaml
name: symbol
from_schema: https://w3id.org/tvbo
rank: 1000
domain_of:
- ToolUnit
- StateVariable
- Parameter
- CouplingInput
- DerivedParameter
- DerivedVariable
range: string

```
</details></div>