"""Canonical-skill parser + adapter renderers.

A canonical skill is a single ``SKILL.md`` file with YAML frontmatter:

```yaml
---
name: linkml-schema
description: How to edit the LinkML schema and why the generated dir is off-limits.
audience: maintainer        # maintainer | user | both
applies_to:                 # globs — used by Copilot/Cursor
  - "schema/**/*.yaml"
  - "tvbo/datamodel/**"
tags: [schema, codegen]
requires_extras: []         # e.g. ["jax"] — surfaced in user-target docs
---

# body in plain markdown
```

Renderers translate the canonical form into the format each tool consumes:

| Target | Output |
|---|---|
| ``claude-code`` | ``<dest>/<name>/SKILL.md`` (Claude frontmatter) |
| ``copilot`` | ``<dest>/<name>.instructions.md`` (``applyTo`` frontmatter) |
| ``cursor`` | ``<dest>/<name>.mdc`` (``globs`` + ``description``) |
| ``agents-md`` | marker region in ``AGENTS.md`` |
| ``prompt`` | concatenated markdown, returned as str |

User-target installs (``claude-code`` / ``cursor`` invoked by ``tvbo skills install``) add a ``tvbo-`` prefix to the on-disk name and stamp ``managed-by: tvbo`` + ``tvbo-version: …`` into the frontmatter so we can safely overwrite our own files on upgrade without clobbering user edits.

A skill directory may carry an ``assets/`` sibling of its ``SKILL.md`` (helper scripts, templates, a skeleton, reference chapters the body defers detail to).
Only the directory-shaped ``claude-code`` target can hold it: the renderer mirrors ``assets/`` next to the rendered ``SKILL.md`` and prunes it on uninstall. The flat targets (``cursor``, ``copilot``, ``prompt``, ``agents-md``) have nowhere to put a mirror, so they inline every referenced ``assets/*.md`` into the body instead — a deferred chapter must not become an unreachable pointer just because the target is a single file.
"""

from __future__ import annotations

import fnmatch
import re
import shutil
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

import yaml

ASSET_IGNORE = ("__pycache__", "*.py[cod]", ".DS_Store")
"""Byte-compiled / OS-noise names never carried into a rendered ``assets/`` mirror."""


def is_asset_noise(rel: Path) -> bool:
    """True if any component of a mirrored-asset relative path is :data:`ASSET_IGNORE`."""
    return any(fnmatch.fnmatch(part, pat) for part in rel.parts for pat in ASSET_IGNORE)


CANONICAL_PACKAGE_DIR = Path(__file__).parent / "canonical"
"""User-skill canonical root (ships in the wheel as package data)."""

CANONICAL_REPO_DIR = Path("skills")
"""Maintainer-skill canonical root (resolved relative to the repo root)."""

AGENTS_MD_BEGIN = "<!-- BEGIN SKILLS INDEX (generated by `tvbo skills sync`; do not edit) -->"
AGENTS_MD_END = "<!-- END SKILLS INDEX -->"


@dataclass
class Skill:
    """A parsed canonical skill."""

    name: str
    description: str
    audience: str  # "maintainer" | "user" | "both"
    applies_to: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    requires_extras: list[str] = field(default_factory=list)
    body: str = ""
    source: Path | None = None
    assets_dir: Path | None = None
    """Sibling ``assets/`` directory of ``SKILL.md``, if present."""

    @property
    def install_name(self) -> str:
        """Name used when installing to a user-global skill directory.

        User skills get a ``tvbo-`` prefix to avoid clashing with skills from other packages. Maintainer skills are rendered into the repo and need no prefix (the repo is already scoped).
        """
        if self.audience == "maintainer":
            return self.name
        return self.name if self.name.startswith("tvbo-") else f"tvbo-{self.name}"


def split_frontmatter(text: str) -> tuple[dict, str]:
    """Split a markdown document with leading YAML frontmatter.

    Returns ``({}, text)`` if no frontmatter is found.
    """
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end == -1:
        end = text.find("\n---", 4)
        if end == -1:
            return {}, text
    fm_text = text[4:end]
    body = text[end:].split("\n", 2)
    rest = body[2] if len(body) > 2 else ""
    return (yaml.safe_load(fm_text) or {}), rest.lstrip("\n")


def parse_skill(path: Path) -> Skill:
    """Parse a ``SKILL.md`` file into a :class:`Skill`.

    Custom fields (``audience``, ``applies_to``, ``tags``, ``requires_extras``) may live either at the top level or under a ``metadata:`` key — the latter satisfies VS Code's SKILL.md schema, which only allows a known set of top-level attributes plus a free-form ``metadata`` block.
    """
    text = path.read_text(encoding="utf-8")
    fm, body = split_frontmatter(text)
    meta = fm.get("metadata") or {}

    def _field(key: str, default=None):
        if key in meta:
            return meta[key]
        return fm.get(key, default)

    name = fm.get("name") or path.parent.name
    description = (fm.get("description") or "").strip()
    audience = _field("audience", "both")
    if audience not in {"maintainer", "user", "both"}:
        raise ValueError(f"{path}: audience must be maintainer|user|both, got {audience!r}")
    assets = path.parent / "assets"
    return Skill(
        name=name,
        description=description,
        audience=audience,
        applies_to=list(_field("applies_to") or []),
        tags=list(_field("tags") or []),
        requires_extras=list(_field("requires_extras") or []),
        body=body.rstrip() + "\n",
        source=path,
        assets_dir=assets if assets.is_dir() else None,
    )


def load_canonical(roots: Iterable[Path]) -> list[Skill]:
    """Walk one or more canonical roots and return all parsed skills, sorted by name."""
    skills: dict[str, Skill] = {}
    for root in roots:
        if not root.exists():
            continue
        for skill_md in sorted(root.glob("*/SKILL.md")):
            skill = parse_skill(skill_md)
            if skill.name in skills:
                raise ValueError(f"duplicate skill name {skill.name!r}: {skills[skill.name].source} vs {skill.source}")
            skills[skill.name] = skill
    return sorted(skills.values(), key=lambda s: s.name)


ASSET_REF = re.compile(r"`assets/([^`\s]+)`")
"""Every ``assets/…`` path a skill body points at, backtick-quoted."""


def asset_refs(body: str) -> list[str]:
    """Distinct ``assets/`` paths referenced by *body*, in first-mention order."""
    return list(dict.fromkeys(ref.rstrip("/") for ref in ASSET_REF.findall(body)))


def flat_body(skill: Skill) -> str:
    """Body with every referenced ``assets/*.md`` chapter appended.

    The flat targets carry no ``assets/`` mirror, so a body that defers detail to a reference file would *lose* that detail rather than defer it. Inlining keeps those consumers whole; the directory-shaped target leaves the pointer alone so the agent reads the chapter only when it reaches that phase.
    """
    if skill.assets_dir is None:
        return skill.body
    chapters = [(ref, skill.assets_dir / ref) for ref in asset_refs(skill.body) if ref.endswith(".md")]
    parts = [skill.body.rstrip()]
    parts += [
        f"<!-- inlined from assets/{ref} -->\n\n{path.read_text(encoding='utf-8').strip()}"
        for ref, path in chapters
        if path.is_file()
    ]
    return skill.body if len(parts) == 1 else "\n\n---\n\n".join(parts) + "\n"


def _dump_frontmatter(data: dict) -> str:
    return yaml.safe_dump(data, sort_keys=False, default_flow_style=False).strip()


def _wrap(fm: dict, body: str) -> str:
    return f"---\n{_dump_frontmatter(fm)}\n---\n\n{body.lstrip()}"


def _sync_assets(assets_dir: Path | None, dest_skill_dir: Path) -> None:
    """Mirror a skill's ``assets/`` dir next to its rendered ``SKILL.md``.

    Idempotent: the destination ``assets/`` is rebuilt from source on every render, so files removed upstream do not linger. A skill with no ``assets/`` leaves the destination without one (and prunes a stale copy if present).
    """
    dest_assets = dest_skill_dir / "assets"
    if dest_assets.exists():
        shutil.rmtree(dest_assets)
    if assets_dir is not None and assets_dir.is_dir():
        # Skip byte-compiled / OS noise so the mirror (and wheel) stay deterministic.
        shutil.copytree(assets_dir, dest_assets, ignore=shutil.ignore_patterns(*ASSET_IGNORE))


def render_claude_code(
    skill: Skill,
    dest_dir: Path,
    *,
    managed: bool = False,
    tvbo_version: str | None = None,
    use_install_name: bool = False,
) -> Path:
    """Render a skill in Claude Code's ``<dest>/<name>/SKILL.md`` format.

    Parameters
    ----------
    managed
        If True, stamp ``managed-by: tvbo`` and ``tvbo-version`` into the
        frontmatter so :func:`uninstall_managed` can recognise our files.
    use_install_name
        If True, use :attr:`Skill.install_name` (with the ``tvbo-`` prefix);
        otherwise use the raw canonical ``name`` (for in-repo rendering).
    """
    target_name = skill.install_name if use_install_name else skill.name
    fm: dict = {"name": target_name, "description": skill.description}
    if managed:
        fm["managed-by"] = "tvbo"
        if tvbo_version:
            fm["tvbo-version"] = tvbo_version
    out = dest_dir / target_name / "SKILL.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_wrap(fm, skill.body), encoding="utf-8")
    _sync_assets(skill.assets_dir, out.parent)
    return out


def render_copilot(
    skill: Skill,
    dest_dir: Path,
    *,
    managed: bool = False,
    tvbo_version: str | None = None,
    use_install_name: bool = False,
) -> Path:
    """Render a skill as a GitHub Copilot ``<name>.instructions.md`` file.

    Parameters
    ----------
    managed
        If True, stamp ``managed-by: tvbo`` and ``tvbo-version`` into the
        frontmatter so :func:`uninstall_managed` can recognise our files.
    use_install_name
        If True, use :attr:`Skill.install_name` (with the ``tvbo-`` prefix);
        otherwise use the raw canonical ``name`` (for in-repo rendering).
    """
    target_name = skill.install_name if use_install_name else skill.name
    apply_to = ",".join(skill.applies_to) if skill.applies_to else "**"
    fm: dict = {"applyTo": apply_to}
    if managed:
        fm["managed-by"] = "tvbo"
        if tvbo_version:
            fm["tvbo-version"] = tvbo_version
    out = dest_dir / f"{target_name}.instructions.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_wrap(fm, flat_body(skill)), encoding="utf-8")
    return out


def render_cursor(
    skill: Skill,
    dest_dir: Path,
    *,
    managed: bool = False,
    tvbo_version: str | None = None,
    use_install_name: bool = False,
) -> Path:
    """Render a skill as a Cursor ``<name>.mdc`` file."""
    target_name = skill.install_name if use_install_name else skill.name
    fm: dict = {
        "description": skill.description,
        "globs": skill.applies_to or [],
        "alwaysApply": False,
    }
    if managed:
        fm["managed-by"] = "tvbo"
        if tvbo_version:
            fm["tvbo-version"] = tvbo_version
    out = dest_dir / f"{target_name}.mdc"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_wrap(fm, flat_body(skill)), encoding="utf-8")
    return out


def render_prompt(skills: list[Skill], dest: Path | None = None) -> str:
    """Render a single concatenated markdown document for raw-API system prompts."""
    parts: list[str] = ["# TVBO — Agent System Prompt", ""]
    for skill in skills:
        parts.append(f"## {skill.name}")
        if skill.description:
            parts.append(f"*{skill.description}*")
            parts.append("")
        parts.append(flat_body(skill).rstrip())
        parts.append("")
    text = "\n".join(parts).rstrip() + "\n"
    if dest is not None:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text, encoding="utf-8")
    return text


def render_agents_md(skills: list[Skill], dest: Path) -> Path:
    """Rewrite the skills-index region of ``AGENTS.md`` in place.

    The region is delimited by :data:`AGENTS_MD_BEGIN` / :data:`AGENTS_MD_END`.
    Prose outside the markers is left untouched. If ``dest`` does not exist, a minimal stub is created so the generator has something to update.
    """
    maintainer = [s for s in skills if s.audience in {"maintainer", "both"}]
    user = [s for s in skills if s.audience in {"user", "both"}]

    lines: list[str] = [AGENTS_MD_BEGIN, ""]
    lines.append("### Maintainer skills (this repo)")
    lines.append("")
    if maintainer:
        lines.append("| Skill | Description | Location |")
        lines.append("|-------|-------------|----------|")
        for s in maintainer:
            lines.append(f"| `{s.name}` | {s.description} | `.claude/skills/{s.name}/SKILL.md` |")
    else:
        lines.append("_(none)_")
    lines.append("")
    lines.append("### User skills (shipped via `pip install tvbo`)")
    lines.append("")
    lines.append("Install with: `tvbo skills install --target claude-code` (or `--target cursor` / `--target prompt`).")
    lines.append("")
    if user:
        lines.append("| Skill | Description | Canonical source |")
        lines.append("|-------|-------------|------------------|")
        for s in user:
            lines.append(f"| `{s.install_name}` | {s.description} | `tvbo/skills/canonical/{s.name}/SKILL.md` |")
    else:
        lines.append("_(none)_")
    lines.append("")
    lines.append(AGENTS_MD_END)
    index_block = "\n".join(lines)

    if dest.exists():
        text = dest.read_text(encoding="utf-8")
        pattern = re.compile(
            re.escape(AGENTS_MD_BEGIN) + r".*?" + re.escape(AGENTS_MD_END),
            flags=re.DOTALL,
        )
        if pattern.search(text):
            new_text = pattern.sub(index_block, text)
        else:
            new_text = text.rstrip() + "\n\n## Skills\n\n" + index_block + "\n"
    else:
        new_text = "# TVBO\n\n## Skills\n\n" + index_block + "\n"
    dest.write_text(new_text, encoding="utf-8")
    return dest


def is_managed_file(path: Path) -> bool:
    """Return True iff *path* has ``managed-by: tvbo`` in its frontmatter."""
    if not path.is_file():
        return False
    try:
        fm, _ = split_frontmatter(path.read_text(encoding="utf-8"))
    except Exception:
        return False
    return fm.get("managed-by") == "tvbo"
