## Gather job generated by `tvbo workflow slurm`. Runs once, after the array
## completes (submitted with --dependency=afterok), reassembling the shard
## outputs into one result per experiment — identical to a local run.
## Inputs: plan (WorkflowPlan), block (dict = engine block), now (str).
<%
sb = block
prefix = ("singularity exec " + (plan.container_exec_flags + " " if plan.container_exec_flags else "")
          + plan.container + " ") if plan.container else ""
%>\
#!/bin/bash
#SBATCH --job-name=${plan.study_key}-${plan.experiment_key}-finalize
## Provenance tag in `squeue -o %k`; the :finalize suffix distinguishes this gather from the array it follows.
#SBATCH --comment=${sb.get("comment") or "tvbo:%s/exp_%s:finalize" % (plan.study_key, plan.experiment_key)}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
% if sb.get("mem"):
#SBATCH --mem=${sb["mem"]}
% endif
% if sb.get("partition"):
#SBATCH --partition=${sb["partition"]}
% endif
% if sb.get("account"):
#SBATCH --account=${sb["account"]}
% endif
#SBATCH --time=02:00:00
#SBATCH --output=logs/%x-%j.out
#SBATCH --error=logs/%x-%j.err

set -euo pipefail
mkdir -p logs

% for mod in (sb.get("modules") or []):
module load ${mod}
% endfor
% if sb.get("venv"):
source ${sb["venv"]}/bin/activate
% endif

## TVBO_SHARD_DIR is exported by `tvbo workflow run`; fall back to the kit's own shards/.
exec ${prefix}tvbo workflow finalize "${'${TVBO_SHARD_DIR:-shards}'}" -o ${plan.out_dir} \
    --stem ${result_stem} --spec spec/${plan.experiment_key}.yaml
