## Slurm sbatch script generated by `tvbo workflow slurm`.
## Inputs: plan (tvbo.cli._workflow.WorkflowPlan), block (dict), now (str).
<%
sb = block
%>\
#!/bin/bash
#SBATCH --job-name=${plan.study_key}-${plan.experiment_key}
#SBATCH --array=0-${plan.n_array_tasks - 1}
#SBATCH --ntasks=1
% if sb.get("cpus_per_task"):
#SBATCH --cpus-per-task=${sb["cpus_per_task"]}
% endif
% if sb.get("mem"):
#SBATCH --mem=${sb["mem"]}
% endif
% if sb.get("gres"):
#SBATCH --gres=${sb["gres"]}
% endif
% if sb.get("time"):
#SBATCH --time=${sb["time"]}
% endif
% if sb.get("partition"):
#SBATCH --partition=${sb["partition"]}
% endif
% if sb.get("account"):
#SBATCH --account=${sb["account"]}
% endif
% if sb.get("mail_type"):
#SBATCH --mail-type=${sb["mail_type"]}
% endif
% if sb.get("mail_user"):
#SBATCH --mail-user=${sb["mail_user"]}
% endif
## Passthrough for any scheduler directive the typed fields don't name.
% for _opt in (sb.get("options") or []):
#SBATCH --${_opt["name"]}=${_opt["value"]}
% endfor
#SBATCH --output=logs/%x-%A_%a.out
#SBATCH --error=logs/%x-%A_%a.err

# ------------------------------------------------------------------
# Generated by tvbo workflow slurm — ${now}
#   study      : ${plan.study_key}
#   experiment : ${plan.experiment_key}
#   backend    : ${plan.backend.name}
#   total cells: ${plan.n_workflow_cells}  array tasks: ${plan.n_array_tasks}  chunk: ${plan.chunk}
#   vectorized inside backend: ${[ax.name for ax in plan.vectorize_axes]}
#   workflow   wildcards     : ${plan.wildcards}
% if plan.overrides:
#   CLI overrides applied:
%   for ov in plan.overrides:
#     - ${ov}
%   endfor
% endif
# ------------------------------------------------------------------

set -euo pipefail
mkdir -p logs

% for mod in (sb.get("modules") or []):
module load ${mod}
% endfor
% if sb.get("venv"):
source ${sb["venv"]}/bin/activate
% endif
## env is normalized to a shell-quoted [{name, value}] list in the plan builder
## (tvbo.cli._workflow._normalize_env), so values are emitted verbatim.
% for _e in (sb.get("env") or []):
export ${_e["name"]}=${_e["value"]}
% endfor

<%
    out_pat = plan.out_dir + "/$SLURM_ARRAY_JOB_ID/$SLURM_ARRAY_TASK_ID"
    prefix = ("singularity exec " + plan.container + " ") if plan.container else ""
    run_target = spec_relpath if spec_relpath else plan.run_spec
%>\
## Each array task runs 1/N of the sweep cells; the backend vmap/pmap-s its share.
## Prefer the self-contained frozen spec (spec/…yaml); fall back to the source recipe.
exec ${prefix}tvbo run ${run_target} \
    --backend=${plan.backend.name} \
% if plan.experiment_selector and not spec_relpath:
    --experiment="${plan.experiment_selector}" \
% endif
    --shard=$SLURM_ARRAY_TASK_ID/${plan.n_array_tasks} \
    -o ${out_pat}
