## Slurm sbatch script generated by `tvbo workflow slurm`.
## Inputs: plan (tvbo.cli._workflow.WorkflowPlan), block (dict), now (str).
<%
sb = block
%>\
#!/bin/bash
#SBATCH --job-name=${plan.study_key}-${plan.experiment_key}
#SBATCH --array=0-${plan.n_array_tasks - 1}
#SBATCH --ntasks=1
% if sb.get("cpus_per_task"):
#SBATCH --cpus-per-task=${sb["cpus_per_task"]}
% endif
% if sb.get("mem"):
#SBATCH --mem=${sb["mem"]}
% endif
% if sb.get("gres"):
#SBATCH --gres=${sb["gres"]}
% endif
% if sb.get("time"):
#SBATCH --time=${sb["time"]}
% endif
% if sb.get("partition"):
#SBATCH --partition=${sb["partition"]}
% endif
% if sb.get("account"):
#SBATCH --account=${sb["account"]}
% endif
% if sb.get("mail_type"):
#SBATCH --mail-type=${sb["mail_type"]}
% endif
% if sb.get("mail_user"):
#SBATCH --mail-user=${sb["mail_user"]}
% endif
#SBATCH --output=logs/%x-%A_%a.out
#SBATCH --error=logs/%x-%A_%a.err

# ------------------------------------------------------------------
# Generated by tvbo workflow slurm — ${now}
#   study      : ${plan.study_key}
#   experiment : ${plan.experiment_key}
#   backend    : ${plan.backend.name}
#   total cells: ${plan.n_workflow_cells}  array tasks: ${plan.n_array_tasks}  chunk: ${plan.chunk}
#   vectorized inside backend: ${[ax.name for ax in plan.vectorize_axes]}
#   workflow   wildcards     : ${plan.wildcards}
% if plan.overrides:
#   CLI overrides applied:
%   for ov in plan.overrides:
#     - ${ov}
%   endfor
% endif
# ------------------------------------------------------------------

set -euo pipefail
mkdir -p logs

% for mod in (sb.get("modules") or []):
module load ${mod}
% endfor
% if sb.get("venv"):
source ${sb["venv"]}/bin/activate
% endif

<%
    out_pat = plan.out_dir + "/$SLURM_ARRAY_JOB_ID/$SLURM_ARRAY_TASK_ID"
    prefix = ("singularity exec " + plan.container + " ") if plan.container else ""
%>\
## Each array task runs 1/N of the sweep cells; the backend vmap/pmap-s its share.
exec ${prefix}tvbo run ${plan.run_spec} \
    --backend=${plan.backend.name} \
% if plan.experiment_selector:
    --experiment="${plan.experiment_selector}" \
% endif
    --slurm-chunk=$SLURM_ARRAY_TASK_ID/${plan.n_array_tasks} \
    -o ${out_pat}
